//
// Generated by dtk
// Translation Unit: d_message_paper.cpp
//

#include "d/dolzel.h" // IWYU pragma: keep
#include "d/d_message_paper.h"
#include "d/d_meter.h"
#include "d/d_kankyo.h"
#include "d/d_s_play.h"
#include "d/d_com_inf_game.h"
#include "f_op/f_op_msg.h"
#include "JSystem/J2DGraph/J2DTextBox.h"
#include "JSystem/J2DGraph/J2DOrthoGraph.h"
#include "JSystem/J2DGraph/J2DScreen.h"
#include "JSystem/J2DGraph/J2DPicture.h"
#include "JSystem/J3DGraphLoader/J3DModelLoader.h"
#include "JSystem/J3DGraphLoader/J3DAnmLoader.h"
#include "JSystem/JKernel/JKRExpHeap.h"
#include "m_Do/m_Do_controller_pad.h"
#include "m_Do/m_Do_graphic.h"
#include "m_Do/m_Do_mtx.h"
#include "stdio.h"
#include "string.h"

#if VERSION < VERSION_PAL
void dMsg3_messageDataInit(sub_msg3_class* i_Msg, int);
void dMsg3_textPosition(sub_msg3_class* i_Msg, u8 i_index);
void dMsg3_yose_select(sub_msg3_class* i_Msg, u8 i_index);
void dMsg3_setCharAlpha(sub_msg3_class* i_Msg, u8 i_index);
u8 dMsg3_aimBrightness();

static int dMsg3_popSpeed;
static J2DScreen* sScreen3[3];
static J2DPicture* bbutton_icon3[8][3];
static J2DPicture* bbutton_kage3[8][3];
static s16 bbuttonTimer3[8][3];
static dDlst_2DMSG3_c message;
static dDlst_2Dm_c board;
static dmsg3_3d_c* msg3d;

static u8 dMsg3_tex_i4_color[] = {
    0x00, 0x00, 0x00, 0x01, 0x01, 0x00, 0x02, 0x02, 0x02, 0x03, 0x04, 0x06, 0x07, 0x09, 0x0b, 0x0d, 0x0f, 0x12, 0x16, 0x1c, 0x22, 0x2a, 0x32, 0x39,
    0x41, 0x4b, 0x54, 0x5e, 0x67, 0x72, 0x7c, 0x87, 0x8f, 0x98, 0xa2, 0xac, 0xb3, 0xbb, 0xc2, 0xca, 0xd0, 0xd8, 0xdd, 0xe1, 0xe7, 0xea, 0xee, 0xf1,
    0xf3, 0xf5, 0xf7, 0xf9, 0xfb, 0xfe, 0xfd, 0xfd, 0xfd, 0xfd, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xfd, 0xfd, 0xfd,
    0xfd, 0xfb, 0xfb, 0xf9, 0xf7, 0xf5, 0xf3, 0xf1, 0xee, 0xea, 0xe7, 0xe1, 0xdd, 0xd8, 0xd0, 0xc9, 0xc2, 0xbc, 0xb3, 0xab, 0xa2, 0x99, 0x8f, 0x87,
    0x7c, 0x72, 0x68, 0x5e, 0x54, 0x4a, 0x41, 0x3a, 0x32, 0x2a, 0x22, 0x1d, 0x15, 0x12, 0x0f, 0x0d, 0x0b, 0x09, 0x07, 0x05, 0x04, 0x04, 0x03, 0x02,
};

/* 801EB128-801EB420       .text setDummyTexture__10dmsg3_3d_cFv */
void dmsg3_3d_c::setDummyTexture() {
    J3DModelData* modeldata = mpModel->getModelData();
    J3DTexture* texture = modeldata->getTexture();
    JUTNameTab* textureName = modeldata->getTextureName();
    JUT_ASSERT(146, texture != NULL);
    JUT_ASSERT(147, textureName != NULL);

    for (u16 i = 0; i < texture->getNum(); i++) {
        const char* texName = textureName->getName(i);
        if (!strcmp(texName, "0_black")) {
            texture->setResTIMG(i, *mDoGph_gInf_c::getFrameBufferTimg());
        } else if (!strcmp(texName, "1_black")) {
            texture->setResTIMG(i, *mDoGph_gInf_c::getFrameBufferTimg());
        }
    }
    mDoExt_modelTexturePatch(modeldata);
}

/* 801EB420-801EB444       .text loadModelData__FPUc */
J3DModelData* loadModelData(u8* data) {
    return J3DModelLoaderDataBase::loadBinaryDisplayList(data, 0x1020);
}

/* 801EB444-801EB464       .text loadAnmTransformData__FPUc */
J3DAnmBase* loadAnmTransformData(u8* data) {
    return J3DAnmLoaderDataBase::load(data);
}

/* 801EB464-801EB6FC       .text __ct__10dmsg3_3d_cFv */
dmsg3_3d_c::dmsg3_3d_c() {
    mpHeap = NULL;
    mpHeap = mDoExt_createSolidHeapFromGameToCurrent(0x20000, 0x20);

    mpModelBin = (u8*)mpHeap->alloc(0x1F40, 0x20);
    JKRReadTypeResource(mpModelBin, 0x1F40, 'BDLM', "hukidashi_07.bdl", dComIfGp_getMsgArchive());
    DCStoreRangeNoSync(mpModelBin, 0x1F40);

    mpAnmBin = (u8*)mpHeap->alloc(0x1388, 0x20);
    JKRReadTypeResource(mpAnmBin, 0x1388, 'BCK ', "hukidashi_07.bck", dComIfGp_getMsgArchive());
    DCStoreRangeNoSync(mpAnmBin, 0x1388);

    J3DModelData* modelData = loadModelData(mpModelBin);
    JUT_ASSERT(213, modelData != NULL);

    mpModel = mDoExt_J3DModel__create(modelData, 0x80000, 0x37441422);
    JUT_ASSERT(218, mpModel != NULL);

    J3DAnmTransform* bck = (J3DAnmTransform*)loadAnmTransformData(mpAnmBin);
    JUT_ASSERT(221, bck != NULL);

    int ok_bck = mBck.init(modelData, bck, 1, 0, 1.0f, 0, -1, false);
    JUT_ASSERT(228, ok_bck != 0);

    setDummyTexture();

    mRot.x = 0;
    mRot.y = -0x8000;
    mRot.z = 0;
    mScale.set(1.0f, 1.0f, 1.0f);
    mpModel->setBaseScale(mScale);
    set_mtx();

    mDoExt_adjustSolidHeap(mpHeap);
    mDoExt_restoreCurrentHeap();
}

/* 801EB6FC-801EB79C       .text __dt__10dmsg3_3d_cFv */
dmsg3_3d_c::~dmsg3_3d_c() {
    mpHeap->free(mpModelBin);
    mpHeap->free(mpAnmBin);
    mDoExt_destroySolidHeap(mpHeap);
}

/* 801EB79C-801EB808       .text set_mtx__10dmsg3_3d_cFv */
void dmsg3_3d_c::set_mtx() {
    mDoMtx_stack_c::transS(0.0f, 0.0f, 0.0f);
    mDoMtx_stack_c::ZXYrotM(mRot.x, mRot.y, mRot.z);
    MTXCopy(mDoMtx_stack_c::now, mpModel->getBaseTRMtx());
}

/* 801EB808-801EB840       .text exec__10dmsg3_3d_cFv */
void dmsg3_3d_c::exec() {
    mBck.play();
    set_mtx();
}

/* 801EB840-801EB8DC       .text draw__10dmsg3_3d_cFv */
void dmsg3_3d_c::draw() {
    dComIfGd_setListFilter();
    mBck.entry(mpModel->getModelData());
    mDoExt_modelUpdateDL(mpModel);
    mBck.remove(mpModel->getModelData());
    dComIfGd_setList();
}

/* 801EB8DC-801EBA18       .text dMsg3_value_init__FP14sub_msg3_classUc */
void dMsg3_value_init(sub_msg3_class* i_Msg, u8 i_index) {
    static const u32 colorTable[] = {
        0x00000000,
        0xB4000000,
        0x82828200,
        0x0000AA00,
        0xF0F01E00,
        0x82FFFF00,
        0x6400FF00,
        0x50505000,
        0xFFB40000,
    };

    char text_buf[32];
    char ruby_buf[32];
    char textSdw_buf[32];
    char rubySdw_buf[32];

    const u32 color = colorTable[i_Msg->colorNo];
    int i = i_index;

    int temp_r5 = i_Msg->msgDataProc[i].getCharAlpha();
    int temp_r6 = i_Msg->msgDataProc[i].getGradAlpha();
    int var_r30 = i_Msg->msgDataProc[i].getRCharAlpha();
    int var_r29 = i_Msg->msgDataProc[i].getRGradAlpha();

    u32 temp_a = color | temp_r5;
    u32 temp_b = color | temp_r6;
    u32 temp_c = color | var_r30;
    u32 temp_d = color | var_r29;

    sprintf(text_buf, "\x1b""CC[%08x]\x1bGC[%08x]", temp_a, temp_b);
    sprintf(ruby_buf, "\x1b""CC[%08x]\x1bGC[%08x]", temp_c, temp_d);
    sprintf(textSdw_buf, "\x1b""CC[%08x]\x1bGC[%08x]", temp_r5, temp_r6);
    sprintf(rubySdw_buf, "\x1b""CC[%08x]\x1bGC[%08x]", var_r30, var_r29);

    strcpy(i_Msg->output_text[i_index], text_buf);
    strcpy(i_Msg->output_ruby[i_index], ruby_buf);
    strcpy(i_Msg->output_textSdw[i_index], textSdw_buf);
    strcpy(i_Msg->output_rubySdw[i_index], rubySdw_buf);
}

/* 801EBA18-801EBAB4       .text dMsg3_setString__FP14sub_msg3_classUc */
void dMsg3_setString(sub_msg3_class* i_Msg, u8 i_index) {
    ((J2DTextBox*)i_Msg->text_pane[i_index].pane)->setString(i_Msg->output_text[i_index]);
    ((J2DTextBox*)i_Msg->ruby_pane[i_index].pane)->setString(i_Msg->output_ruby[i_index]);
    ((J2DTextBox*)i_Msg->textSdw_pane[i_index].pane)->setString(i_Msg->output_textSdw[i_index]);
    ((J2DTextBox*)i_Msg->rubySdw_pane[i_index].pane)->setString(i_Msg->output_rubySdw[i_index]);
}

/* 801EBAB4-801EBAD8       .text dMsg3_messagePaneShow__FP14sub_msg3_classUc */
void dMsg3_messagePaneShow(sub_msg3_class* i_Msg, u8 i_index) {
    i_Msg->text_pane[i_index].pane->show();
    i_Msg->ruby_pane[i_index].pane->show();
}

/* 801EBAD8-801EBAFC       .text dMsg3_messagePaneHide__FP14sub_msg3_classUc */
void dMsg3_messagePaneHide(sub_msg3_class* i_Msg, u8 i_index) {
    i_Msg->text_pane[i_index].pane->hide();
    i_Msg->ruby_pane[i_index].pane->hide();
}

/* 801EBAFC-801EBBD0       .text dMsg3_outFontHide__FUc */
void dMsg3_outFontHide(u8 i_index) {
    for (int i = 0; i < 8; i++) {
        bbutton_icon3[i][i_index]->hide();
        bbutton_kage3[i][i_index]->hide();

        bbutton_icon3[i][i_index]->rotate(0.0f);
        bbutton_kage3[i][i_index]->rotate(0.0f);

        bbuttonTimer3[i][i_index] = -1;
    }
}

/* 801EBBD0-801EBC08       .text dMsg3_arrowUpShow__FP14sub_msg3_class */
void dMsg3_arrowUpShow(sub_msg3_class* i_Msg) {
    fopMsgM_setInitAlpha(&i_Msg->field_0xbac);
    fopMsgM_setInitAlpha(&i_Msg->field_0xbe4);
}

/* 801EBC08-801EBC40       .text dMsg3_arrowUpHide__FP14sub_msg3_class */
void dMsg3_arrowUpHide(sub_msg3_class* i_Msg) {
    fopMsgM_setNowAlphaZero(&i_Msg->field_0xbac);
    fopMsgM_setNowAlphaZero(&i_Msg->field_0xbe4);
}

/* 801EBC40-801EBC78       .text dMsg3_arrowDownShow__FP14sub_msg3_class */
void dMsg3_arrowDownShow(sub_msg3_class* i_Msg) {
    fopMsgM_setInitAlpha(&i_Msg->field_0xc1c);
    fopMsgM_setInitAlpha(&i_Msg->field_0xc54);
}

/* 801EBC78-801EBCB0       .text dMsg3_arrowDownHide__FP14sub_msg3_class */
void dMsg3_arrowDownHide(sub_msg3_class* i_Msg) {
    fopMsgM_setNowAlphaZero(&i_Msg->field_0xc1c);
    fopMsgM_setNowAlphaZero(&i_Msg->field_0xc54);
}

/* 801EBCB0-801EBCE8       .text dMsg3_dotShow__FP14sub_msg3_class */
void dMsg3_dotShow(sub_msg3_class* i_Msg) {
    fopMsgM_setInitAlpha(&i_Msg->field_0xc8c);
    fopMsgM_setInitAlpha(&i_Msg->field_0xcc4);
}

/* 801EBCE8-801EBD20       .text dMsg3_dotHide__FP14sub_msg3_class */
void dMsg3_dotHide(sub_msg3_class* i_Msg) {
    fopMsgM_setNowAlphaZero(&i_Msg->field_0xc8c);
    fopMsgM_setNowAlphaZero(&i_Msg->field_0xcc4);
}

/* 801EBD20-801EBDE4       .text dMsg3_multiTexInit__FP14sub_msg3_class */
void dMsg3_multiTexInit(sub_msg3_class* i_Msg) {
    JKRReadTypeResource(i_Msg->Tex[0], 0x11800, 'TIMG', "hukidashi_0212.bti", dComIfGp_getMsgArchive());
    DCStoreRangeNoSync(i_Msg->Tex[0], 0x11800);

    JKRReadTypeResource(i_Msg->Tex[1], 0x11800, 'TIMG', "hukidashi_07.bti", dComIfGp_getMsgArchive());
    DCStoreRangeNoSync(i_Msg->Tex[1], 0x11800);
    board.init(i_Msg->Tex[0], i_Msg->Tex[1], 1.0f, 1.0f);
}

/* 801EBDE4-801EBE94       .text dMsg3_fontdataInit__FP14sub_msg3_class */
void dMsg3_fontdataInit(sub_msg3_class* i_Msg) {
    i_Msg->mx = mDoExt_getMesgFont();
    JUT_ASSERT(628, i_Msg->mx != NULL);

    i_Msg->rx = mDoExt_getRubyFont();
    JUT_ASSERT(631, i_Msg->rx != NULL);
}

/* 801EBE94-801EBED8       .text dMsg3_screenDataSet__FP14sub_msg3_classUc */
void dMsg3_screenDataSet(sub_msg3_class* i_Msg, u8 i_index) {
    dMsg3_value_init(i_Msg, i_index);
    dMsg3_setString(i_Msg, i_index);
}

/* 801EBED8-801EC52C       .text dMsg3_screenDataInit__FP14sub_msg3_classUc */
void dMsg3_screenDataInit(sub_msg3_class* i_Msg, u8 i_index) {
    fopMsgM_setPaneData(&i_Msg->text_pane[i_index], sScreen3[i_index]->search('tx23'));
    fopMsgM_setPaneData(&i_Msg->ruby_pane[i_index], sScreen3[i_index]->search('tx29'));
    fopMsgM_setPaneData(&i_Msg->textSdw_pane[i_index], sScreen3[i_index]->search('tx20'));
    fopMsgM_setPaneData(&i_Msg->rubySdw_pane[i_index], sScreen3[i_index]->search('tx26'));

    i_Msg->textSdw_pane[i_index].pane->hide();
    i_Msg->rubySdw_pane[i_index].pane->hide();

    fopMsgM_setPaneData(&i_Msg->field_0xcfc[i_index], sScreen3[i_index]->search('ms22'));
    fopMsgM_setPaneData(&i_Msg->field_0xda4[i_index], sScreen3[i_index]->search('ms20'));

    sScreen3[i_index]->search('tx24')->hide();
    sScreen3[i_index]->search('tx30')->hide();
    sScreen3[i_index]->search('tx21')->hide();
    sScreen3[i_index]->search('tx27')->hide();

    ((J2DPicture*)i_Msg->field_0xcfc[i_index].pane)->setWhite(0);
    ((J2DPicture*)i_Msg->field_0xda4[i_index].pane)->setWhite(0);

    if (i_index == 0) {
        fopMsgM_setPaneData(&i_Msg->field_0xbac, sScreen3[i_index]->search('yz21'));
        fopMsgM_setPaneData(&i_Msg->field_0xc1c, sScreen3[i_index]->search('yz20'));
        fopMsgM_setPaneData(&i_Msg->field_0xc8c, sScreen3[i_index]->search('dt20'));
        fopMsgM_setPaneData(&i_Msg->field_0xbe4, sScreen3[i_index]->search('yz23'));
        fopMsgM_setPaneData(&i_Msg->field_0xc54, sScreen3[i_index]->search('yz22'));
        fopMsgM_setPaneData(&i_Msg->field_0xcc4, sScreen3[i_index]->search('dt21'));

        ((J2DPicture*)i_Msg->field_0xbe4.pane)->setWhite(0x000000FF);
        ((J2DPicture*)i_Msg->field_0xc54.pane)->setWhite(0x000000FF);
        ((J2DPicture*)i_Msg->field_0xcc4.pane)->setWhite(0x000000FF);
    } else {
        sScreen3[i_index]->search('yz21')->hide();
        sScreen3[i_index]->search('yz20')->hide();
        sScreen3[i_index]->search('dt20')->hide();
        sScreen3[i_index]->search('yz23')->hide();
        sScreen3[i_index]->search('yz22')->hide();
        sScreen3[i_index]->search('dt21')->hide();
    }

    ((J2DTextBox*)i_Msg->text_pane[i_index].pane)->setFont(i_Msg->mx);
    ((J2DTextBox*)i_Msg->ruby_pane[i_index].pane)->setFont(i_Msg->rx);
    ((J2DTextBox*)i_Msg->textSdw_pane[i_index].pane)->setFont(i_Msg->mx);
    ((J2DTextBox*)i_Msg->rubySdw_pane[i_index].pane)->setFont(i_Msg->rx);

    f32 var_f31;
    J2DTextBox::TFontSize fontSize;
    J2DTextBox::TFontSize rubySize;
    fontSize.mSizeX = g_msgHIO.field_0x70;
    fontSize.mSizeY = g_msgHIO.field_0x70;

    ((J2DTextBox*)i_Msg->text_pane[i_index].pane)->setFontSize(fontSize);
    ((J2DTextBox*)i_Msg->textSdw_pane[i_index].pane)->setFontSize(fontSize);

    ((J2DTextBox*)i_Msg->text_pane[i_index].pane)->setCharSpace(-2.0f);
    ((J2DTextBox*)i_Msg->ruby_pane[i_index].pane)->setCharSpace(-1.0f);
    ((J2DTextBox*)i_Msg->textSdw_pane[i_index].pane)->setCharSpace(-2.0f);
    ((J2DTextBox*)i_Msg->rubySdw_pane[i_index].pane)->setCharSpace(-1.0f);

    ((J2DTextBox*)i_Msg->text_pane[i_index].pane)->setLineSpace(g_msgHIO.field_0x5e);
    ((J2DTextBox*)i_Msg->textSdw_pane[i_index].pane)->setLineSpace(g_msgHIO.field_0x5e);

    i_Msg->field_0xeb0 = fontSize.mSizeX;
    i_Msg->field_0xeb4 = rubySize.mSizeX;
}

/* 801EC52C-801EC638       .text dMsg3_ScreenDataValueInit__FP14sub_msg3_class */
void dMsg3_ScreenDataValueInit(sub_msg3_class* i_Msg) {
    J2DPane* pane = i_Msg->text_pane[0].pane;
    i_Msg->field_0xeac = ((J2DTextBox*)pane)->getLineSpace() / 2;
    i_Msg->field_0xe90 = pane->getHeight() + g_messageHIO.field_0x3c;

    fopMsgM_paneTrans(&i_Msg->text_pane[0], 0.0f, 0.0f);
    fopMsgM_paneTrans(&i_Msg->text_pane[1], 0.0f, i_Msg->field_0xe90);
    fopMsgM_paneTrans(&i_Msg->text_pane[2], 0.0f, -i_Msg->field_0xe90);

    fopMsgM_setNowAlphaZero(&i_Msg->field_0xbac);
    fopMsgM_setNowAlphaZero(&i_Msg->field_0xbe4);
    fopMsgM_setNowAlphaZero(&i_Msg->field_0xc1c);
    fopMsgM_setNowAlphaZero(&i_Msg->field_0xc54);
    fopMsgM_setNowAlphaZero(&i_Msg->field_0xc8c);
    fopMsgM_setNowAlphaZero(&i_Msg->field_0xcc4);

    for (int i = 0; i < 3; i++) {
        dMsg3_messageDataInit(i_Msg, i);
    }
}

/* 801EC638-801EC690       .text dMsg3_stickInfoInit__FP14sub_msg3_class */
void dMsg3_stickInfoInit(sub_msg3_class* i_Msg) {
    if (CPad_GET_STICK_POS_Y(0) > 0.7f || CPad_GET_STICK_POS_Y(3) > 0.7f) {
        i_Msg->field_0xed9 = 1;
    } else if (CPad_GET_STICK_POS_Y(0) < 0.7f || CPad_GET_STICK_POS_Y(3) < 0.7f) {
        i_Msg->field_0xed9 = 2;
    } else {
        i_Msg->field_0xed9 = 0;
    }
}

/* 801EC690-801EC714       .text dMsg3_stickInfoCheck__FP14sub_msg3_class */
void dMsg3_stickInfoCheck(sub_msg3_class* i_Msg) {
    if (i_Msg->field_0xed9 == 1) {
        if (CPad_GET_STICK_POS_Y(0) <= 0.0f || CPad_GET_STICK_POS_Y(3) <= 0.0f) {
            i_Msg->field_0xed9 = 0;
        }
    } else if (i_Msg->field_0xed9 == 2) {
        if (CPad_GET_STICK_POS_Y(0) >= 0.0f || CPad_GET_STICK_POS_Y(3) >= 0.0f) {
            i_Msg->field_0xed9 = 0;
        }
    }
}

/* 801EC714-801EC84C       .text dMsg3_messageOut__FP14sub_msg3_classUci */
void dMsg3_messageOut(sub_msg3_class* i_Msg, u8 i_index, int i_aimLine) {
    i_Msg->field_0xec8[i_index] = 0;
    dMsg3_messagePaneShow(i_Msg, i_index);
    dMsg3_messageDataInit(i_Msg, i_index);

    i_Msg->msgDataProc[i_index].setCount(0);
    i_Msg->msgDataProc[i_index].resetNowLine();
    i_Msg->msgDataProc[i_index].setAimLine(i_aimLine);
    dMsg3_yose_select(i_Msg, i_index);
    i_Msg->msgDataProc[i_index].shortCut();
    dMsg3_setCharAlpha(i_Msg, i_index);
    i_Msg->msgDataProc[i_index].stringSet();

    for (int i = 0; i < 8; i++) {
        u8 iconNum = i_Msg->msgDataProc[i_index].getIconNum(i);
        u32 iconColor = i_Msg->msgDataProc[i_index].getIconColor(i);

        if (iconNum != fopMsgM_Icon_NONE_e && bbuttonTimer3[i][i_index] == -1) {
            fopMsgM_outFontSet(bbutton_icon3[i][i_index], bbutton_kage3[i][i_index], &bbuttonTimer3[i][i_index], iconColor, iconNum);
        }
    }

    dMsg3_setString(i_Msg, i_index);
}

/* 801EC84C-801EC8CC       .text dMsg3_yose_select__FP14sub_msg3_classUc */
void dMsg3_yose_select(sub_msg3_class* i_Msg, u8 i_index) {
    i_Msg->msgDataProc[i_index].count = i_Msg->msgDataProc[i_index].stringLength();
    i_Msg->field_0xec8[i_index] = i_Msg->msgDataProc[i_index].getLineCount();
    i_Msg->msgDataProc[i_index].setLineCount(0);
    i_Msg->msgDataProc[i_index].stringShift();
    dMsg3_textPosition(i_Msg, i_index);
}

/* 801EC8CC-801EC97C       .text dMsg3_textPosition__FP14sub_msg3_classUc */
void dMsg3_textPosition(sub_msg3_class* i_Msg, u8 i_index) {
    f32 r7 = 0.0f;
    int temp_r0 = i_Msg->field_0xeac * (2 - i_Msg->field_0xec8[i_index]);
    ((J2DTextBox*)i_Msg->text_pane[i_index].pane)->shiftSet(r7, temp_r0);
    ((J2DTextBox*)i_Msg->ruby_pane[i_index].pane)->shiftSet(r7, temp_r0);
    ((J2DTextBox*)i_Msg->textSdw_pane[i_index].pane)->shiftSet(r7, temp_r0);
    ((J2DTextBox*)i_Msg->rubySdw_pane[i_index].pane)->shiftSet(r7, temp_r0);
}

/* 801EC97C-801EC9F0       .text dMsg3_rubySet__FP14sub_msg3_class */
void dMsg3_rubySet(sub_msg3_class* i_Msg) {
    if (
        i_Msg->mStatus == fopMsgStts_MSG_UNK5_e ||
        i_Msg->mStatus == fopMsgStts_MSG_TYPING_e ||
        i_Msg->mStatus == fopMsgStts_STOP_e ||
        i_Msg->mStatus == fopMsgStts_CLOSE_WAIT_e
    ) {
        for (int i = 0; i < 3; i++) {
            if (!g_messageHIO.field_0x4b) {
                i_Msg->ruby_pane[i].pane->hide();
            } else {
                i_Msg->ruby_pane[i].pane->show();
            }
        }
    }
}

/* 801EC9F0-801ECC08       .text dMsg3_arrowMove__FP14sub_msg3_class */
void dMsg3_arrowMove(sub_msg3_class* i_Msg) {
    i_Msg->field_0xeb8++;
    if (i_Msg->field_0xeb8 > 12) {
        i_Msg->field_0xeb8 -= 12;
    }

    i_Msg->field_0xc1c.pane->move(i_Msg->field_0xc1c.mPosTopLeftOrig.x, i_Msg->field_0xc1c.mPosTopLeftOrig.y - abs(6 - i_Msg->field_0xeb8));
    i_Msg->field_0xc54.pane->move(i_Msg->field_0xc1c.mPosTopLeftOrig.x, i_Msg->field_0xc1c.mPosTopLeftOrig.y - abs(6 - i_Msg->field_0xeb8));
    i_Msg->field_0xbac.pane->move(i_Msg->field_0xbac.mPosTopLeftOrig.x, i_Msg->field_0xbac.mPosTopLeftOrig.y + abs(6 - i_Msg->field_0xeb8));
    i_Msg->field_0xbe4.pane->move(i_Msg->field_0xbac.mPosTopLeftOrig.x, i_Msg->field_0xbac.mPosTopLeftOrig.y + abs(6 - i_Msg->field_0xeb8));
}

/* 801ECC08-801ECCE4       .text dMsg3_aimAlphaSqare__FP14sub_msg3_classii */
void dMsg3_aimAlphaSqare(sub_msg3_class* i_Msg, int param_0, int param_1) {
    if (param_1 < 0) {
        param_1 = 0;
    } else if (param_1 > param_0) {
        param_1 = param_0;
    }

    f32 f31 = (((f32)param_1 * (f32)param_1) / ((f32)param_0 * (f32)param_0));
    f32 f0 = (255.0f - dMsg3_aimBrightness());
    i_Msg->field_0xea4 = 255.0f - f0 * f31;
}

/* 801ECCE4-801ECE04       .text dMsg3_aimAlphaSqrt__FP14sub_msg3_classii */
void dMsg3_aimAlphaSqrt(sub_msg3_class* i_Msg, int param_0, int param_1) {
    if (param_1 < 0) {
        param_1 = 0;
    } else if (param_1 > param_0) {
        param_1 = param_0;
    }

    f32 f31 = std::sqrtf((f32)param_1 / (f32)param_0);
    f32 f0 = (255.0f - dMsg3_aimBrightness());
    i_Msg->field_0xea4 = 255.0f - f0 * f31;
}

/* 801ECE04-801ECEA0       .text dMsg3_kankyoBrightness__Fv */
u8 dMsg3_kankyoBrightness() {
    GXColorS10* difcol = dKy_Get_DifCol();
    return (difcol->b * 0.114f) + (difcol->r * 0.299f) + (difcol->g * 0.587f);
}

/* 801ECEA0-801ECEEC       .text dMsg3_aimBrightness__Fv */
u8 dMsg3_aimBrightness() {
    u32 brightness = dMsg3_kankyoBrightness();
    if ((u8)brightness <= g_messageHIO.field_0x29) {
        return 0xFF;
    } else {
        return 0xFF - (brightness - g_messageHIO.field_0x29);
    }
}

/* 801ECEEC-801ED2C8       .text dMsg3_setCharAlpha__FP14sub_msg3_classUc */
void dMsg3_setCharAlpha(sub_msg3_class* i_Msg, u8 i_index) {
    int temp_r6 = ((J2DTextBox*)i_Msg->text_pane[0].pane)->getLineSpace();
    f32 temp_f1 = i_Msg->field_0xcfc[0].mPosTopLeftOrig.y - i_Msg->field_0xda4[0].mPosTopLeftOrig.y;

    int var_r31 = i_index;
    f32 temp_f2 = temp_f1 + i_Msg->text_pane[var_r31].mPosTopLeft.y + (i_Msg->field_0xeac * (2 - i_Msg->field_0xec8[i_index]));

    int temp_r27 = (temp_r6 * i_Msg->field_0xec8[i_index]);
    int var_r26 = (int)temp_f2 + temp_r27;
    int var_r30 = (int)(temp_f2 - g_messageHIO.field_0x38);
    int var_r29 = var_r30 + temp_r27;

    if (var_r26 < 58) {
        int temp_r3 = var_r26 + i_Msg->mx->getHeight();
        if (var_r26 >= 0) {
            i_Msg->field_0xedb[0][var_r31] = dMsg3_tex_i4_color[var_r26];
        } else {
            i_Msg->field_0xedb[0][var_r31] = 0;
        }

        if (temp_r3 >= 0) {
            i_Msg->field_0xedb[1][var_r31] = dMsg3_tex_i4_color[temp_r3];
        } else {
            i_Msg->field_0xedb[1][var_r31] = 0;
        }
    } else if (temp_r27 > 187) {
        int temp_r3 = temp_r27 + i_Msg->mx->getHeight();
        if (temp_r27 <= 239) {
            i_Msg->field_0xedb[0][var_r31] = dMsg3_tex_i4_color[temp_r27];
        } else {
            i_Msg->field_0xedb[0][var_r31] = 0;
        }

        if (temp_r3 <= 239) {
            i_Msg->field_0xedb[1][var_r31] = dMsg3_tex_i4_color[temp_r3];
        } else {
            i_Msg->field_0xedb[1][var_r31] = 0;
        }
    } else {
        i_Msg->field_0xedb[0][var_r31] = 0xFF;
        i_Msg->field_0xedb[1][var_r31] = 0xFF;
    }

    if (var_r29 < 58) {
        int temp_r3 = var_r29 + i_Msg->rx->getHeight();
        if (var_r29 >= 0) {
            i_Msg->field_0xedb[2][var_r31] = dMsg3_tex_i4_color[var_r29];
        } else {
            i_Msg->field_0xedb[2][var_r31] = 0;
        }

        if (temp_r3 >= 0) {
            i_Msg->field_0xedb[3][var_r31] = dMsg3_tex_i4_color[temp_r3];
        } else {
            i_Msg->field_0xedb[3][var_r31] = 0;
        }
    } else if (var_r30 > 187) {
        int temp_r3 = var_r30 + i_Msg->rx->getHeight();
        if (var_r30 <= 239) {
            i_Msg->field_0xedb[2][var_r31] = dMsg3_tex_i4_color[var_r30];
        } else {
            i_Msg->field_0xedb[2][var_r31] = 0;
        }

        if (temp_r3 <= 239) {
            i_Msg->field_0xedb[3][var_r31] = dMsg3_tex_i4_color[temp_r3];
        } else {
            i_Msg->field_0xedb[3][var_r31] = 0;
        }
    } else {
        i_Msg->field_0xedb[2][var_r31] = 0xFF;
        i_Msg->field_0xedb[3][var_r31] = 0xFF;
    }

    if (i_Msg->field_0xedb[0][var_r31] > (u8)i_Msg->field_0xea8) {
        i_Msg->field_0xedb[0][var_r31] = i_Msg->field_0xea8;
    }

    if (i_Msg->field_0xedb[1][var_r31] > (u8)i_Msg->field_0xea8) {
        i_Msg->field_0xedb[1][var_r31] = i_Msg->field_0xea8;
    }

    if (i_Msg->field_0xedb[2][var_r31] > (u8)i_Msg->field_0xea8) {
        i_Msg->field_0xedb[2][var_r31] = i_Msg->field_0xea8;
    }

    if (i_Msg->field_0xedb[3][var_r31] > (u8)i_Msg->field_0xea8) {
        i_Msg->field_0xedb[3][var_r31] = i_Msg->field_0xea8;
    }

    i_Msg->msgDataProc[var_r31].setCharAlpha(i_Msg->field_0xedb[0][var_r31],
                                             i_Msg->field_0xedb[1][var_r31],
                                             i_Msg->field_0xedb[2][var_r31],
                                             i_Msg->field_0xedb[3][var_r31]);
}

/* 801ED2C8-801ED37C       .text dMsg3_messageShow__FP14sub_msg3_class */
void dMsg3_messageShow(sub_msg3_class* i_Msg) {
    for (u8 i = 0; i < 3; i++) {
        dMsg3_screenDataSet(i_Msg, i);
    }

    if (i_Msg->field_0xec0 > 0) {
        dMsg3_messageOut(i_Msg, i_Msg->field_0xe98, i_Msg->field_0xec0 - i_Msg->mesgEntry.field_0x16);
    }

    dMsg3_messageOut(i_Msg, i_Msg->field_0xe99, i_Msg->field_0xec0);

    if (i_Msg->msgDataProc[i_Msg->field_0xe99].getMesgStatus() == 7) {
        dMsg3_messageOut(i_Msg, i_Msg->field_0xe9a, i_Msg->field_0xec0 + i_Msg->mesgEntry.field_0x16);
    }
}

/* 801ED37C-801ED4B4       .text dMsg3_messageDataInit__FP14sub_msg3_classi */
void dMsg3_messageDataInit(sub_msg3_class* i_Msg, int i_index) {
    int line_width = 503;
    int center_line_width = 486;
    int char_space = ((J2DTextBox*)i_Msg->text_pane[i_index].pane)->getCharSpace();
    int ruby_space = ((J2DTextBox*)i_Msg->ruby_pane[i_index].pane)->getCharSpace();

    i_Msg->msgDataProc[i_index].dataInit();
    i_Msg->msgDataProc[i_index].setBmgData(i_Msg->message);
    i_Msg->msgDataProc[i_index].setOutMessage(i_Msg->output_text[i_index], i_Msg->output_ruby[i_index], i_Msg->output_textSdw[i_index], i_Msg->output_rubySdw[i_index]);
    i_Msg->msgDataProc[i_index].setFont(i_Msg->mx);
    i_Msg->msgDataProc[i_index].setRubyFont(i_Msg->rx);
    i_Msg->msgDataProc[i_index].setCharSpace(char_space);
    i_Msg->msgDataProc[i_index].setRubyCharSpace(ruby_space);
    i_Msg->msgDataProc[i_index].setLineSpace(((J2DTextBox*)i_Msg->text_pane[i_index].pane)->getLineSpace());
    i_Msg->msgDataProc[i_index].setMesgEntry(&i_Msg->mesgEntry);
    i_Msg->msgDataProc[i_index].setFontSize(i_Msg->field_0xeb0);
    i_Msg->msgDataProc[i_index].setRubyFontSize(i_Msg->field_0xeb4);
    i_Msg->msgDataProc[i_index].setLineWidth(line_width);
    i_Msg->msgDataProc[i_index].setCenterLineWidth(center_line_width);
    i_Msg->msgDataProc[i_index].setSpaceFlagOff();
}

/* 801ED4B4-801ED608       .text dMsg3_stopProc__FP14sub_msg3_class */
int dMsg3_stopProc(sub_msg3_class* i_Msg) {
    if (i_Msg->field_0xed9 == 0) {
        if (CPad_GET_STICK_POS_Y(0) > 0.7f || CPad_GET_STICK_POS_Y(3) > 0.7f) {
            if (i_Msg->field_0xec0 != 0) {
                u8 r4 = i_Msg->field_0xe9a;
                i_Msg->field_0xed9 = 1;
                dMsg3_screenDataSet(i_Msg, r4);
                i_Msg->field_0xebc = 3;
                i_Msg->field_0xec0 -= i_Msg->mesgEntry.field_0x16;
                i_Msg->mStatus = fopMsgStts_MSG_UNK5_e;
                mDoAud_seStart(JA_SE_SCROLL_1, NULL);
            }
        } else if (CPad_CHECK_TRIG_A(0) || CPad_GET_STICK_POS_Y(0) < -0.7f || CPad_GET_STICK_POS_Y(3) < -0.7f) {
            u8 r4 = i_Msg->field_0xe98;
            i_Msg->field_0xed9 = 2;
            dMsg3_screenDataSet(i_Msg, r4);
            i_Msg->field_0xebc = 1;
            i_Msg->field_0xec0 += i_Msg->mesgEntry.field_0x16;
            i_Msg->mStatus = fopMsgStts_MSG_UNK5_e;
            mDoAud_seStart(JA_SE_SCROLL_1, NULL);
        } else {
            dMeter_Info.field_0x0 = 1;
        }
    } else {
        dMsg3_stickInfoCheck(i_Msg);
    }

    return 1;
}

/* 801ED608-801ED738       .text dMsg3_closewaitProc__FP14sub_msg3_class */
int dMsg3_closewaitProc(sub_msg3_class* i_Msg) {
    if (i_Msg->field_0xed9 == 0) {
        if (CPad_GET_STICK_POS_Y(0) > 0.7f || CPad_GET_STICK_POS_Y(3) > 0.7f) {
            if (i_Msg->field_0xec0 != 0) {
                u8 r4 = i_Msg->field_0xe9a;
                i_Msg->field_0xed9 = 1;
                dMsg3_screenDataSet(i_Msg, r4);
                i_Msg->field_0xebc = 3;
                i_Msg->field_0xec0 -= i_Msg->mesgEntry.field_0x16;
                i_Msg->mStatus = fopMsgStts_MSG_UNK5_e;
                mDoAud_seStart(JA_SE_SCROLL_1, NULL);
            }
        } else if (CPad_CHECK_TRIG_A(0) || CPad_GET_STICK_POS_Y(0) < -0.7f || CPad_GET_STICK_POS_Y(3) < -0.7f) {
            i_Msg->field_0xed9 = 2;
            mDoAud_seStart(JA_SE_TALK_WIN_CLOSE, NULL);
            i_Msg->mStatus = fopMsgStts_MSG_ENDS_e;
        } else {
            dMeter_Info.field_0x0 = 4;
        }
    } else {
        dMsg3_stickInfoCheck(i_Msg);
    }

    return 1;
}

/* 801ED738-801ED8A8       .text dMsg3_openProc__FP14sub_msg3_class */
int dMsg3_openProc(sub_msg3_class* i_Msg) {
    if (i_Msg->field_0xe94 == 0) {
        dMsg3_messageOut(i_Msg, i_Msg->field_0xe99, i_Msg->field_0xec0);
        if (i_Msg->msgDataProc[i_Msg->field_0xe99].getMesgStatus() == 7) {
            dMsg3_messageOut(i_Msg, i_Msg->field_0xe9a, i_Msg->field_0xec0 + i_Msg->mesgEntry.field_0x16);
        }
    } else if (i_Msg->field_0xe94 == dMsg3_popSpeed) {
        i_Msg->mStatus = i_Msg->msgDataProc[i_Msg->field_0xe99].getMesgStatus();
    }

    i_Msg->field_0xea8 = fopMsgM_valueIncrease(dMsg3_popSpeed, i_Msg->field_0xe94, 0) * 255.0f;
    if (i_Msg->field_0xe94 != 0) {
        dMsg3_messageShow(i_Msg);
    }

    if (i_Msg->msgDataProc[i_Msg->field_0xe99].getMesgStatus() == 7) {
        i_Msg->field_0xc1c.mNowAlpha = i_Msg->field_0xea8;
        i_Msg->field_0xc54.mNowAlpha = i_Msg->field_0xea8;
    } else {
        i_Msg->field_0xc8c.mNowAlpha = i_Msg->field_0xea8;
        i_Msg->field_0xcc4.mNowAlpha = i_Msg->field_0xea8;
    }

    dMsg3_aimAlphaSqrt(i_Msg, dMsg3_popSpeed, i_Msg->field_0xe94);
    dComIfG_setBrightness(i_Msg->field_0xea4);
    i_Msg->field_0xe94++;
    return 1;
}

/* 801ED8A8-801EDA30       .text dMsg3_closeProc__FP14sub_msg3_class */
int dMsg3_closeProc(sub_msg3_class* i_Msg) {
    if (i_Msg->field_0xe94 == 0) {
        for (u8 i = 0; i < 3; i++) {
            dMsg3_messagePaneHide(i_Msg, i);
            dMsg3_outFontHide(i);
        }

        JKRRemoveResource(i_Msg->head_p, NULL);
        i_Msg->mStatus = fopMsgStts_BOX_CLOSED_e;
    }

    i_Msg->field_0xe94--;
    if (i_Msg->field_0xe94 < 0) {
        i_Msg->field_0xe94 = 0;
    }

    i_Msg->field_0xea8 = fopMsgM_valueIncrease(dMsg3_popSpeed, i_Msg->field_0xe94, 0) * 255.0f;

    if (i_Msg->field_0xbac.mNowAlpha != 0) {
        i_Msg->field_0xbac.mNowAlpha = i_Msg->field_0xea8;
        i_Msg->field_0xbe4.mNowAlpha = i_Msg->field_0xea8;
    }

    if (i_Msg->field_0xc1c.mNowAlpha != 0) {
        i_Msg->field_0xc1c.mNowAlpha = i_Msg->field_0xea8;
        i_Msg->field_0xc54.mNowAlpha = i_Msg->field_0xea8;
    }

    if (i_Msg->field_0xc8c.mNowAlpha != 0) {
        i_Msg->field_0xc8c.mNowAlpha = i_Msg->field_0xea8;
        i_Msg->field_0xcc4.mNowAlpha = i_Msg->field_0xea8;
    }

    dMsg3_aimAlphaSqare(i_Msg, dMsg3_popSpeed, i_Msg->field_0xe94);
    dComIfG_setBrightness(i_Msg->field_0xea4);
    return 1;
}

/* 801EDA30-801EDE80       .text dMsg3_outwaitProc__FP14sub_msg3_class */
int dMsg3_outwaitProc(sub_msg3_class* i_Msg) {
    if (i_Msg->field_0xebc == 1 || i_Msg->field_0xebc == 2) {
        i_Msg->field_0xec4 += 12;
    } else if (i_Msg->field_0xebc == 3 || i_Msg->field_0xebc == 4) {
        i_Msg->field_0xec4 -= 12;
    }

    if (i_Msg->field_0xec4 > 1020) {
        i_Msg->field_0xec4 -= 2040;
    } else if (i_Msg->field_0xec4 < -1020) {
        i_Msg->field_0xec4 += 2040;
    }

    if (i_Msg->field_0xebc == 1) {
        int temp_r4 = i_Msg->field_0xe98;

        for (int i = 0; i < 3; i++) {
            i_Msg->text_pane[i].mPosTopLeft.y -= 12.0f;
        }

        i_Msg->field_0xeda -= 85;

        if (i_Msg->text_pane[temp_r4].mPosTopLeft.y < -i_Msg->field_0xe90) {
            i_Msg->field_0xebc = 2;

            u8 temp_r3 = i_Msg->field_0xe99;
            i_Msg->field_0xe99 = i_Msg->field_0xe9a;
            i_Msg->field_0xe9a = i_Msg->field_0xe98;
            i_Msg->field_0xe98 = temp_r3;

            if (i_Msg->msgDataProc[i_Msg->field_0xe99].getMesgStatus() == 7) {
                dMsg3_messageOut(i_Msg, i_Msg->field_0xe9a, i_Msg->field_0xec0 + i_Msg->mesgEntry.field_0x16);
            } else {
                dMsg3_messagePaneHide(i_Msg, i_Msg->field_0xe9a);
                dMsg3_outFontHide(i_Msg->field_0xe9a);
            }

            i_Msg->field_0xeda = 0;
            dMsg3_arrowUpHide(i_Msg);
            dMsg3_arrowDownHide(i_Msg);
            dMsg3_dotHide(i_Msg);
        }
    } else if (i_Msg->field_0xebc == 3) {
        int temp_r4 = i_Msg->field_0xe9a;

        for (int i = 0; i < 3; i++) {
            i_Msg->text_pane[i].mPosTopLeft.y += 12.0f;
        }

        i_Msg->field_0xeda -= 127;

        if (i_Msg->text_pane[temp_r4].mPosTopLeft.y > i_Msg->field_0xcfc[0].mSizeOrig.y) {
            i_Msg->field_0xebc = 4;

            u8 temp_r3 = i_Msg->field_0xe99;
            i_Msg->field_0xe99 = i_Msg->field_0xe98;
            i_Msg->field_0xe98 = i_Msg->field_0xe9a;
            i_Msg->field_0xe9a = temp_r3;

            if (i_Msg->field_0xec0 > 0) {
                dMsg3_messageOut(i_Msg, i_Msg->field_0xe98, i_Msg->field_0xec0 - i_Msg->mesgEntry.field_0x16);
            } else {
                dMsg3_messagePaneHide(i_Msg, i_Msg->field_0xe98);
                dMsg3_outFontHide(i_Msg->field_0xe98);
            }

            i_Msg->field_0xeda = 0;
            dMsg3_arrowUpHide(i_Msg);
            dMsg3_arrowDownHide(i_Msg);
            dMsg3_dotHide(i_Msg);
        }
    } else if (i_Msg->field_0xebc == 2) {
        for (int i = 0; i < 3; i++) {
            i_Msg->text_pane[i].mPosTopLeft.y -= 12.0f;
        }

        i_Msg->field_0xeda += 43;

        if (i_Msg->text_pane[i_Msg->field_0xe99].mPosTopLeft.y <= i_Msg->text_pane[0].mPosTopLeftOrig.y) {
            i_Msg->text_pane[i_Msg->field_0xe98].mPosTopLeft.y = i_Msg->text_pane[0].mPosTopLeftOrig.y - i_Msg->field_0xe90;
            i_Msg->text_pane[i_Msg->field_0xe99].mPosTopLeft.y = i_Msg->text_pane[0].mPosTopLeftOrig.y;
            i_Msg->text_pane[i_Msg->field_0xe9a].mPosTopLeft.y = i_Msg->text_pane[0].mPosTopLeftOrig.y + i_Msg->field_0xe90;

            i_Msg->field_0xebc = 0;

            if (i_Msg->msgDataProc[i_Msg->field_0xe99].getMesgStatus() == 7) {
                i_Msg->mStatus = fopMsgStts_STOP_e;
                dMsg3_arrowDownShow(i_Msg);
            } else {
                i_Msg->mStatus = fopMsgStts_MSG_DISPLAYED_e;
                dMsg3_dotShow(i_Msg);
            }

            i_Msg->field_0xeda = 0xFF;

            if (i_Msg->field_0xec0 != 0) {
                dMsg3_arrowUpShow(i_Msg);
            }
        }

        dMsg3_messageShow(i_Msg);
    } else if (i_Msg->field_0xebc == 4) {
        for (int i = 0; i < 3; i++) {
            i_Msg->text_pane[i].mPosTopLeft.y += 12.0f;
        }

        i_Msg->field_0xeda += 37;

        if (i_Msg->text_pane[i_Msg->field_0xe99].mPosTopLeft.y >= i_Msg->text_pane[0].mPosTopLeftOrig.y) {
            i_Msg->text_pane[i_Msg->field_0xe98].mPosTopLeft.y = i_Msg->text_pane[0].mPosTopLeftOrig.y - i_Msg->field_0xe90;
            i_Msg->text_pane[i_Msg->field_0xe99].mPosTopLeft.y = i_Msg->text_pane[0].mPosTopLeftOrig.y;
            i_Msg->text_pane[i_Msg->field_0xe9a].mPosTopLeft.y = i_Msg->text_pane[0].mPosTopLeftOrig.y + i_Msg->field_0xe90;

            i_Msg->field_0xebc = 0;
            i_Msg->mStatus = fopMsgStts_STOP_e;
            i_Msg->field_0xeda = 0xFF;
            dMsg3_arrowDownShow(i_Msg);

            if (i_Msg->field_0xec0 != 0) {
                dMsg3_arrowUpShow(i_Msg);
            }
        }

        dMsg3_messageShow(i_Msg);
    } else {
        dMsg3_messageShow(i_Msg);
    }

    return 1;
}

/* 801EDE80-801EDF18       .text draw__14dDlst_2DMSG3_cFv */
void dDlst_2DMSG3_c::draw() {
    J2DOrthoGraph* graf = dComIfGp_getCurrentGrafPort();
    graf->setPort();

    for (int i = 0; i < 3; i++) {
        sScreen3[i]->setScissor(true);
        sScreen3[i]->draw(0.0f, 0.0f, graf);
    }

    outFontDraw();
}

/* 801EDF18-801EE104       .text outFontDraw__14dDlst_2DMSG3_cFv */
void dDlst_2DMSG3_c::outFontDraw() {
    J2DPane* ppane = ((sub_msg3_class*)actorP)->field_0xcfc[0].pane;
    f32 var_f31 = ppane->getGlbBounds().i.y;
    f32 var_f30 = ppane->getGlbBounds().f.y;

    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 8; j++) {
            u8 iconNum = actorP->msgDataProc[i].getIconNum(j);
            int posX = actorP->msgDataProc[i].getIconPosX(j);
            int posY = actorP->msgDataProc[i].getIconPosY(j);
            int scale = actorP->msgDataProc[i].getIconScale(j);

            if (iconNum != fopMsgM_Icon_NONE_e) {
                u8 r14;
                J2DTextBox* scrn = (J2DTextBox*)actorP->text_pane[i].pane;
                int r18 = (f32)posX + scrn->getGlbBounds().i.x;

                int r17;
                if (scale > actorP->field_0xeb0) {
                    if (actorP->field_0xec8[i] > 1) {
                        f32 temp = (actorP->field_0xeac * (2 - posY));
                        r17 = temp + scrn->getGlbBounds().i.y - (f32)(int)(scale / 2);
                    } else {
                        f32 temp = actorP->field_0xeac * 3;
                        r17 = (temp + scrn->getGlbBounds().i.y - (f32)(int)(scale / 2));
                    }
                } else {
                    f32 temp = (actorP->field_0xeac * (2 - actorP->field_0xec8[i] + (posY * 2)));
                    r17 = (temp + scrn->getGlbBounds().i.y);
                }

                r14 = actorP->field_0xea8;
                JKRHeap* heap = mDoExt_setCurrentHeap(actorP->Heap);

                if ((f32)r17 > var_f31 && (f32)r17 < var_f30 - (f32)scale) {
                    fopMsgM_outFontDraw(bbutton_icon3[j][i], bbutton_kage3[j][i], r18, r17, scale, &bbuttonTimer3[j][i], r14, iconNum);
                }

                mDoExt_setCurrentHeap(heap);
            }
        }
    }
}

/* 801EE104-801EE218       .text dMsg3_Draw__FP14sub_msg3_class */
static BOOL dMsg3_Draw(sub_msg3_class* i_Msg) {
    for (int i = 0; i < 3; i++) {
        i_Msg->text_pane[i].mNowAlpha = i_Msg->field_0xea8;
        i_Msg->ruby_pane[i].mNowAlpha = i_Msg->field_0xea8;
        i_Msg->textSdw_pane[i].mNowAlpha = i_Msg->field_0xea8;
        i_Msg->rubySdw_pane[i].mNowAlpha = i_Msg->field_0xea8;

        fopMsgM_setAlpha(&i_Msg->text_pane[i]);
        fopMsgM_setAlpha(&i_Msg->ruby_pane[i]);
        fopMsgM_setAlpha(&i_Msg->textSdw_pane[i]);
        fopMsgM_setAlpha(&i_Msg->rubySdw_pane[i]);
    }

    fopMsgM_setAlpha(&i_Msg->field_0xbac);
    fopMsgM_setAlpha(&i_Msg->field_0xbe4);
    fopMsgM_setAlpha(&i_Msg->field_0xc1c);
    fopMsgM_setAlpha(&i_Msg->field_0xc54);
    fopMsgM_setAlpha(&i_Msg->field_0xc8c);
    fopMsgM_setAlpha(&i_Msg->field_0xcc4);

    dComIfGd_set2DOpa(&message);
    msg3d->draw();
    return TRUE;
}

/* 801EE218-801EE740       .text dMsg3_Execute__FP14sub_msg3_class */
static BOOL dMsg3_Execute(sub_msg3_class* i_Msg) {
    JKRHeap* heap = mDoExt_setCurrentHeap(i_Msg->Heap);
    msg3d->exec();

    if (i_Msg->mStatus == fopMsgStts_BOX_OPENING_e) {
        dMsg3_openProc(i_Msg);
    } else if (i_Msg->mStatus == fopMsgStts_MSG_UNK5_e) {
        dMsg3_outwaitProc(i_Msg);
    } else if (i_Msg->mStatus == fopMsgStts_STOP_e) {
        dMsg3_stopProc(i_Msg);
    } else if (i_Msg->mStatus == fopMsgStts_MSG_DISPLAYED_e) {
        dMsg3_closewaitProc(i_Msg);
    } else if (i_Msg->mStatus == fopMsgStts_MSG_ENDS_e) {
        dMsg3_closeProc(i_Msg);
    } else if (i_Msg->mStatus == fopMsgStts_MSG_DESTROYED_e) {
        fopMsgM_Delete(i_Msg);
    }

    dMsg3_arrowMove(i_Msg);

    for (int i = 0; i < 3; i++) {
        f32 sp64 = i_Msg->text_pane[i].mPosTopLeft.x + g_messageHIO.field_0x58;
        f32 sp74 = i_Msg->text_pane[i].mPosTopLeft.y;
        i_Msg->text_pane[i].pane->move((int)sp64, (int)sp74);
        i_Msg->ruby_pane[i].pane->move((int)sp64, (int)sp74 - g_messageHIO.field_0x38);

        i_Msg->textSdw_pane[i].pane->move((int)sp64 + 2, (int)sp74 + 2);
        i_Msg->rubySdw_pane[i].pane->move((int)sp64 + 2, (int)sp74 + 2 - g_messageHIO.field_0x38);
    }

    dMsg3_rubySet(i_Msg);

    for (int i = 0; i < 3; i++) {
        ((J2DTextBox*)i_Msg->text_pane[i].pane)->setFontColor(*(JUtility::TColor*)&g_messageHIO.field_0x5, *(JUtility::TColor*)&g_messageHIO.field_0x5);
        ((J2DTextBox*)i_Msg->ruby_pane[i].pane)->setFontColor(*(JUtility::TColor*)&g_messageHIO.field_0x1d, *(JUtility::TColor*)&g_messageHIO.field_0x1d);
        ((J2DTextBox*)i_Msg->textSdw_pane[i].pane)->setFontColor(*(JUtility::TColor*)&g_messageHIO.field_0x11, *(JUtility::TColor*)&g_messageHIO.field_0x11);
        ((J2DTextBox*)i_Msg->rubySdw_pane[i].pane)->setFontColor(*(JUtility::TColor*)&g_messageHIO.field_0x11, *(JUtility::TColor*)&g_messageHIO.field_0x11);

        ((J2DTextBox*)i_Msg->text_pane[i].pane)->setWhite(*(JUtility::TColor*)&g_messageHIO.field_0x9);
        ((J2DTextBox*)i_Msg->ruby_pane[i].pane)->setWhite(*(JUtility::TColor*)&g_messageHIO.field_0x21);
        ((J2DTextBox*)i_Msg->textSdw_pane[i].pane)->setWhite(*(JUtility::TColor*)&g_messageHIO.field_0x15);
        ((J2DTextBox*)i_Msg->rubySdw_pane[i].pane)->setWhite(*(JUtility::TColor*)&g_messageHIO.field_0x15);

        ((J2DTextBox*)i_Msg->text_pane[i].pane)->setBlack(*(JUtility::TColor*)&g_messageHIO.field_0xd);
        ((J2DTextBox*)i_Msg->ruby_pane[i].pane)->setBlack(*(JUtility::TColor*)&g_messageHIO.field_0x25);
        ((J2DTextBox*)i_Msg->textSdw_pane[i].pane)->setBlack(*(JUtility::TColor*)&g_messageHIO.field_0x19);
        ((J2DTextBox*)i_Msg->rubySdw_pane[i].pane)->setBlack(*(JUtility::TColor*)&g_messageHIO.field_0x19);
    }

    dComIfGp_setMesgStatus(i_Msg->mStatus);
    mDoExt_setCurrentHeap(heap);
    return TRUE;
}

/* 801EE740-801EE748       .text dMsg3_IsDelete__FP14sub_msg3_class */
static BOOL dMsg3_IsDelete(sub_msg3_class* i_Msg) {
    return TRUE;
}

/* 801EE748-801EE904       .text dMsg3_Delete__FP14sub_msg3_class */
static BOOL dMsg3_Delete(sub_msg3_class* i_Msg) {
    dComIfGp_setMesgStatus(0);
    dComIfG_setBrightness(0xFF);

    JKRHeap* heap = mDoExt_setCurrentHeap(i_Msg->Heap);

    for (int i = 0; i < 3; i++) {
        if (sScreen3[i] != NULL) {
            delete sScreen3[i];
        }
    }

    i_Msg->Heap->free(i_Msg->Tex[0]);
    i_Msg->Heap->free(i_Msg->Tex[1]);
    mDoExt_removeMesgFont();
    mDoExt_removeRubyFont();

    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 8; j++) {
            if (bbutton_icon3[j][i] != NULL) {
                delete bbutton_icon3[j][i];
            }
            if (bbutton_kage3[j][i] != NULL) {
                delete bbutton_kage3[j][i];
            }
        }

        i_Msg->Heap->free(i_Msg->output_text[i]);
        i_Msg->Heap->free(i_Msg->output_ruby[i]);
        i_Msg->Heap->free(i_Msg->output_textSdw[i]);
        i_Msg->Heap->free(i_Msg->output_rubySdw[i]);
    }

    if (msg3d != NULL) {
        delete msg3d;
    }
    msg3d = NULL;

    mDoExt_setCurrentHeap(heap);
    i_Msg->Heap->freeAll();
    dComIfGp_setHeapLockFlag(0);
    return TRUE;
}

/* 801EE904-801EEEFC       .text dMsg3_Create__FP9msg_class */
static cPhs_State dMsg3_Create(msg_class* i_this) {
    sub_msg3_class* i_Msg = (sub_msg3_class*)i_this;

    if (dComIfGp_isHeapLockFlag() != 0 && dComIfGp_isHeapLockFlag() != 9) {
        return cPhs_INIT_e;
    }

    i_Msg->Heap = dComIfGp_getExpHeap2D();
    dComIfGp_setHeapLockFlag(9);
    JKRHeap* heap = mDoExt_setCurrentHeap(i_Msg->Heap);

    msg3d = new dmsg3_3d_c();

    for (u8 i = 0; i < 3; i++) {
        sScreen3[i] = new J2DScreen();
        sScreen3[i]->set("hukidashi_02.blo", dComIfGp_getMsgArchive());
    }

    i_Msg->Tex[0] = (ResTIMG*)i_Msg->Heap->alloc(0x11800, 0x20);
    JUT_ASSERT(2188, i_Msg->Tex[0] != NULL);

    i_Msg->Tex[1] = (ResTIMG*)i_Msg->Heap->alloc(0x11800, 0x20);
    JUT_ASSERT(2190, i_Msg->Tex[1] != NULL);

    dMsg3_fontdataInit(i_Msg);

    for (u8 i = 0; i < 3; i++) {
        for (int j = 0; j < 8; j++) {
            bbutton_icon3[j][i] = new J2DPicture("font_07_02.bti");
            bbutton_kage3[j][i] = new J2DPicture("font_07_02.bti");
            fopMsgM_blendInit(bbutton_icon3[j][i], "font_00.bti");
            fopMsgM_blendInit(bbutton_kage3[j][i], "font_00.bti");

            bbutton_icon3[j][i]->hide();
            bbutton_kage3[j][i]->hide();
            bbutton_icon3[j][i]->setAlpha(0);
            bbutton_kage3[j][i]->setAlpha(0);

            bbuttonTimer3[j][i] = -1;
        }
    }

    for (u8 i = 0; i < 3; i++) {
        i_Msg->output_text[i] = (char*)i_Msg->Heap->alloc(1001, 4);
        JUT_ASSERT(2213, i_Msg->output_text[i] != NULL);

        i_Msg->output_ruby[i] = (char*)i_Msg->Heap->alloc(1001, 4);
        JUT_ASSERT(2216, i_Msg->output_ruby[i] != NULL);

        i_Msg->output_textSdw[i] = (char*)i_Msg->Heap->alloc(1001, 4);
        JUT_ASSERT(2219, i_Msg->output_textSdw[i] != NULL);

        i_Msg->output_rubySdw[i] = (char*)i_Msg->Heap->alloc(1001, 4);
        JUT_ASSERT(2222, i_Msg->output_rubySdw[i] != NULL);
    }

    i_Msg->head_p = i_Msg->msgGet.getMesgHeader(i_this->mMsgNo);
    JUT_ASSERT(2227, i_Msg->head_p);

    i_Msg->message = (char*)i_Msg->msgGet.getMessage(i_Msg->head_p);
    i_Msg->mesgEntry = i_Msg->msgGet.getMesgEntry(i_Msg->head_p);
    i_Msg->mesgNumber = i_Msg->msgGet.getMesgNumber();
    i_this->mStatus = fopMsgStts_BOX_OPENING_e;

    dMsg3_multiTexInit(i_Msg);

    for (u8 i = 0; i < 3; i++) {
        dMsg3_screenDataInit(i_Msg, i);
        dMsg3_screenDataSet(i_Msg, i);
        dMsg3_messagePaneHide(i_Msg, i);
    }

    dMsg3_ScreenDataValueInit(i_Msg);
    dMsg3_stickInfoInit(i_Msg);
    i_Msg->field_0xebc = 0;
    i_Msg->field_0xe98 = 2;
    i_Msg->field_0xe99 = 0;
    i_Msg->field_0xe9a = 1;

    dMsg3_popSpeed = g_messageHIO.field_0x3b;
    mDoExt_setCurrentHeap(heap);
    message.setActorP(i_Msg);
    dComIfGp_setMesgStatus(i_this->mStatus);
    return cPhs_COMPLEATE_e;
}

static msg_method_class l_dMsg3_Method = {
    (process_method_func)dMsg3_Create,
    (process_method_func)dMsg3_Delete,
    (process_method_func)dMsg3_Execute,
    (process_method_func)dMsg3_IsDelete,
    (process_method_func)dMsg3_Draw
};

msg_process_profile_definition g_profile_MSG3 = {
    /* Layer ID     */ fpcLy_CURRENT_e,
    /* List ID      */ 12,
    /* List Prio    */ fpcPi_CURRENT_e,
    /* Proc Name    */ fpcNm_MSG3_e,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(sub_msg3_class),
    /* Size Other   */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopMsg_Method,
    /* Draw Prio    */ fpcDwPi_MSG3_e,
    /* Msg SubMtd   */ &l_dMsg3_Method,
};
#endif

#if VERSION == VERSION_PAL
static BOOL dMessage_Paper_Draw(dMessage_Paper_c*) {
    /* Nonmatching */
}

static BOOL dMessage_Paper_Execute(dMessage_Paper_c*) {
    /* Nonmatching */
}

static BOOL dMessage_Paper_IsDelete(dMessage_Paper_c*) {
    /* Nonmatching */
}

static BOOL dMessage_Paper_Delete(dMessage_Paper_c*) {
    /* Nonmatching */
}

static cPhs_State dMessage_Paper_Create(msg_class*) {
    /* Nonmatching */
}

static msg_method_class l_dMessage_Paper_Method = {
    (process_method_func)dMessage_Paper_Create,
    (process_method_func)dMessage_Paper_Delete,
    (process_method_func)dMessage_Paper_Execute,
    (process_method_func)dMessage_Paper_IsDelete,
    (process_method_func)dMessage_Paper_Draw
};

msg_process_profile_definition g_profile_MSG3 = {
    /* Layer ID     */ fpcLy_CURRENT_e,
    /* List ID      */ 12,
    /* List Prio    */ fpcPi_CURRENT_e,
    /* Proc Name    */ fpcNm_MSG3_e,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(dMessage_Paper_c),
    /* Size Other   */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopMsg_Method,
    /* Draw Prio    */ fpcDwPi_MSG3_e,
    /* Msg SubMtd   */ &l_dMessage_Paper_Method,
};
#endif
