//
// Generated by dtk
// Translation Unit: d_menu_item.cpp
//

#include "d/dolzel.h" // IWYU pragma: keep
#include "d/d_menu_item.h"
#include "d/d_com_inf_game.h"
#include "d/d_item_data.h"
#include "d/d_menu_save.h"
#include "d/d_meter.h"
#include "d/d_stage.h"
#include "JSystem/J2DGraph/J2DOrthoGraph.h"
#include "JSystem/J2DGraph/J2DPicture.h"
#include "JSystem/J2DGraph/J2DTextBox.h"
#include "JSystem/JKernel/JKRArchive.h"
#include "JSystem/JUtility/JUTAssert.h"
#include "JAZelAudio/JAZelAudio_SE.h"
#include "dolphin/types.h"
#include "f_op/f_op_msg_mng.h"
#include "m_Do/m_Do_audio.h"
#include "m_Do/m_Do_controller_pad.h"
#include "string.h"

void dMeter_subWinFlagOff();
void dMeter_subWinFlagOn();
void dMeter_itemMoveSet(fopMsgM_pane_class*, u8, u8);
u8 dMeter_itemMoveFlagCheck();

dMi_HIO_c g_miHIO;

/* 801C7B4C-801C7C7C       .text __ct__9dMi_HIO_cFv */
dMi_HIO_c::dMi_HIO_c() {
    field_0x08 = 0.8f;
    field_0x0C = 15;

    for (int i = 0; i < ARR_SIZE; i++) {
        arr_0x0E[i] = 0;
        arr_0x1A[i] = 10;
    }

    field_0x18 = 0;
    field_0x24 = 1;
    field_0x26 = -100;
    field_0x28 = -100;
    field_0x2A = -45;
    field_0x2C = 50;
    field_0x2E = 30;
    field_0x30 = -3;
    field_0x32 = 10;
    field_0x34 = 7;
    field_0x36 = 14;
    field_0x38 = 5;
    field_0x3A = 12;
    field_0x3C = 10;
    field_0x40 = 320;
    field_0x42 = 240;
    field_0x3E = 200;
    field_0x46 = 0;
    field_0x48 = 20;
    field_0x44 = -120;

    // Light Yellow-Green
    mClothColor.r = 0xE3;
    mClothColor.g = 0xFF;
    mClothColor.b = 0xB3;
    mClothColor.a = 0xDC;

    // Transparent
    mShadowColor.r = 0x00;
    mShadowColor.g = 0x00;
    mShadowColor.b = 0x00;
    mShadowColor.a = 0x00;

    field_0x5C = 130;

    mBlackColor.set(0x00, 0x00, 0x00, 0xFF); // Black
    // mWhiteColor stays as default.
}

/* 801C7C7C-801C7DC4       .text initialize__12dMenu_Item_cFv */
void dMenu_Item_c::initialize() {
    itemBitCheck(true);

    mTimer = 0;
    m858.mUserArea = 10;
    mA18[0].mUserArea = 0;
    m2422 = 0;

    noteInit();
    outFontInit();
    checkMove();
    itemNumberSet();

    m970.mInitAlpha = g_miHIO.field_0x5C;
    m23FA = 0;
    m23FC = 0;

    ((J2DWindow*)m14D0.pane)->getContentsColor(m2320);

    m231C->insertChild(m1460.pane, mA18[3].pane);
    m231C->insertChild(mA18[3].pane, mA18[2].pane);
    m231C->insertChild(mA18[2].pane, mA18[1].pane);
    m231C->insertChild(mA18[1].pane, mA18[0].pane);
}

/* 801C7DC4-801C8724       .text screenSet__12dMenu_Item_cFv */
void dMenu_Item_c::screenSet() {
    static const u32 l_ft[] = {
        'ft00', 'ft01', 'ft02', 'ft03', 'ft04', 'ft05', 'ft06', 'ft07',
        'ft08', 'ft09', 'ft10', 'ft11', 'ft12', 'ft13', 'ft14',
    };
    static const u32 l_no[] = {
        'no23', 'no13', 'no22', 'no12', 'no21', 'no11',
    };
    static const u32 l_car[] = {
        'car1', 'car2', 'car3', 'car4',
    };
    static const u32 l_sin_01[] = {
        '2401', '2501', '2801', '2601', '2701', '2901', '3001', '3101',
    };
    static const u32 l_sin_10[] = {
        '2410', '2510', '2810', '2610', '2710', '2910', '3010', '3110',
    };
    static const u32 l_sit[] = {
        'it21', 'it22', 'it25', 'it23', 'it24', 'it26', 'it27', 'it28', 'it29',
    };
    static const u32 l_sik[] = {
        'ik21', 'ik22', 'ik25', 'ik23', 'ik24', 'ik26', 'ik27', 'ik28', 'ik29',
    };
    static const u32 l_sb[] = {
        'sb00', 'sb01', 'sb02', 'sb03', 'sb04', 'sb05', 'sb06', 'sb07', 'sb08',
    };
    static const u32 l_it[] = {
        'it00', 'it01', 'it02', 'it03', 'it04', 'it05', 'it06', 'it07',
        'it08', 'it09', 'it10', 'it11', 'it12', 'it13', 'it14', 'it15',
        'it16', 'it17', 'it18', 'it19', 'it20',
    };
    static const u32 l_ik[] = {
        'ik00', 'ik01', 'ik02', 'ik03', 'ik04', 'ik05', 'ik06', 'ik07',
        'ik08', 'ik09', 'ik10', 'ik11', 'ik12', 'ik13', 'ik14', 'ik15',
        'ik16', 'ik17', 'ik18', 'ik19', 'ik20',
    };
    static const u32 l_ip[] = {
        'ip01', 'ip03', 'ip05', 'ip07', 'ip09', 'ip11',
    };
    static const u32 l_fd[] = {
        'fd00', 'fd01', 'fd02', 'fd03', 'fd04', 'fd05', 'fd06', 'fd07',
        'fd08', 'fd09', 'fd10', 'fd11', 'fd12', 'fd13', 'fd14',
    };

    m231C = scrn->search('ROOT');

    fopMsgM_setPaneData(&m008, scrn, 'ft15');
    fopMsgM_setPaneData(&m040, scrn, 'ft16');
    fopMsgM_setPaneData(&m078, scrn, 'ft17');

    for (int i = 0; i < 15; i++) {
        fopMsgM_setPaneData(&m0B0[i], scrn->search(l_ft[i]));
        fopMsgM_setPaneData(&m3F8[i], scrn->search(l_fd[i]));
        m0B0[i].mUserArea = -1;
    }

    fopMsgM_setPaneData(&m740, scrn, 'str0');
    fopMsgM_setPaneData(&m778, scrn, 'st00');

    if (dComIfGs_getOptRuby() != 0) {
        fopMsgM_paneTrans(&m778, 0.0f, -4.0f);
    }

    fopMsgM_setPaneData(&m7B0, scrn, 'nt00');
    fopMsgM_setPaneData(&m7E8, scrn, 'nk00');
    fopMsgM_setPaneData(&m820, scrn, 'no11');

    m820.mUserArea = m820.pane->getRotate();

    ((J2DTextBox*)m740.pane)->setFont(mRFont);
    ((J2DTextBox*)m778.pane)->setFont(mFont);

    ((J2DTextBox*)m740.pane)->setWhite(0xFFFFFFFF);
    ((J2DTextBox*)m740.pane)->setCharColor(0x000000FF);
    ((J2DTextBox*)m740.pane)->setGradColor(0x000000FF);

    ((J2DTextBox*)m778.pane)->setWhite(0xFFFFFFFF);
    ((J2DTextBox*)m778.pane)->setCharColor(0x000000FF);
    ((J2DTextBox*)m778.pane)->setGradColor(0x000000FF);

    fopMsgM_setPaneData(&m858, scrn, 'wd');
    m858.pane->show();
    ((J2DTextBox*)m858.pane)->setFont(mFont);

    outFont->setPane(mFont, &m858, &m008, &m040, &m078);

    fopMsgM_setPaneData(&m890[0], scrn, 'nm00');
    ((J2DTextBox*)m890[0].pane)->setFont(mFont);

    fopMsgM_setPaneData(&m890[1], scrn, 'nm01');
    ((J2DTextBox*)m890[1].pane)->setFont(mFont);

    fopMsgM_setPaneData(&m900, scrn, 'itnm');
    fopMsgM_setPaneData(&m938, scrn, 'itnk');
    fopMsgM_setPaneData(&m970, scrn, 'msk0');
    fopMsgM_setPaneData(&m9A8, scrn, 'tl00');
    fopMsgM_setPaneData(&m9E0, scrn, 'tk00');

    for (int i = 0; i < 4; i++) {
        fopMsgM_setPaneData(&mA18[i], scrn, l_car[i]);
    }

    for (int i = 0; i < 8; i++) {
        fopMsgM_setPaneData(&mAF8[i], scrn, l_sin_01[i]);
        fopMsgM_setPaneData(&mCB8[i], scrn, l_sin_10[i]);
        fopMsgM_setPaneData(&mE78[i], scrn, l_sit[i]);
        fopMsgM_setPaneData(&m1070[i], scrn, l_sik[i]);
    }

    fopMsgM_setPaneData(&m1038, scrn, 'it29');
    fopMsgM_setPaneData(&m1230, scrn, 'ik29');

    for (int i = 0; i < 9; i++) {
        fopMsgM_setPaneData(&m1268[i], scrn, l_sb[i]);
    }

    fopMsgM_setPaneData(&m1460, scrn, 'blak');
    fopMsgM_setPaneData(&m1498, scrn, 'wdsv');
    fopMsgM_setPaneData(&m14D0, scrn, 'wk01');
    fopMsgM_setPaneData(&m1508, scrn, 'wk00');
    fopMsgM_setPaneData(&m1540, scrn, '0301');
    fopMsgM_setPaneData(&m1578, scrn, '1301');
    fopMsgM_setPaneData(&m15B0, scrn, '1310');
    fopMsgM_setPaneData(&m15E8, scrn, '1401');
    fopMsgM_setPaneData(&m1620, scrn, '1410');

    for (int i = 0; i < 21; i++) {
        fopMsgM_setPaneData(&m1658[i], scrn, l_it[i]);
        fopMsgM_setPaneData(&m1AF0[i], scrn, l_ik[i]);
    }

    fopMsgM_setPaneData(&m1F88[0], scrn, 'bwl1');
    fopMsgM_setPaneData(&m1F88[1], scrn, 'bwl2');
    fopMsgM_setPaneData(&m1F88[2], scrn, 'bwl3');
    m1F88[0].pane->hide();
    m1F88[1].pane->hide();
    m1F88[2].pane->hide();

    fopMsgM_setPaneData(&m2030[0], scrn, 'chk1');
    fopMsgM_setPaneData(&m2030[1], scrn, 'chk2');
    fopMsgM_setPaneData(&m2030[2], scrn, 'chk3');

    for (int i = 0; i < 6; i++) {
        fopMsgM_setPaneData(&m20D8[i], scrn, l_ip[i]);
    }

    fopMsgM_setPaneData(&m2228, scrn, 'cc35');
    fopMsgM_setPaneData(&m2260, scrn, 'cc22');
    fopMsgM_setPaneData(&m2298, scrn, 'cc11');
    fopMsgM_setPaneData(&m22D0, scrn, 'cc00');

    for (int i = 0; i < 21; i++) {
        u8 itemNo = dComIfGs_getItem(i);
        if (itemNo == 0xFF) {
            continue;
        }

        if (itemNo == dItemNo_MAGIC_ARROW_e) {
            m1F88[0].pane->show();
            m1F88[1].pane->show();
            m1F88[2].pane->hide();
            itemNo = dItemNo_BOW_e;
        } else if (itemNo == dItemNo_LIGHT_ARROW_e) {
            m1F88[0].pane->show();
            m1F88[1].pane->show();
            m1F88[2].pane->show();
            itemNo = dItemNo_BOW_e;
        }

        JKRArchive* archive = dComIfGp_getItemIconArchive();
        JKRReadTypeResource(mItemTexBuffer[i], 0xc00, 'TIMG', dItem_data::getTexture(itemNo), archive);
        DCStoreRangeNoSync(mItemTexBuffer[i], 0xc00);
        ((J2DPicture*)m1658[i].pane)->changeTexture((ResTIMG*)mItemTexBuffer[i], 0);
        ((J2DPicture*)m1AF0[i].pane)->changeTexture((ResTIMG*)mItemTexBuffer[i], 0);
    }

    for (int i = 0; i < 8; i++) {
        if (dComIfGs_getItemBeast((u8)i) == 0xFF) {
            continue;
        }

        JKRArchive* archive = dComIfGp_getItemIconArchive();
        JKRReadTypeResource(mSubItemTexBuffer[i], 0xc00, 'TIMG', dItem_data::getTexture(dComIfGs_getItemBeast(i)), archive);
        DCStoreRangeNoSync(mSubItemTexBuffer[i], 0xc00);
        ((J2DPicture*)mE78[i].pane)->changeTexture((ResTIMG*)mSubItemTexBuffer[i], 0);
        ((J2DPicture*)m1070[i].pane)->changeTexture((ResTIMG*)mSubItemTexBuffer[i], 0);
    }

    {
        JKRArchive* archive = dComIfGp_getItemIconArchive();
        JKRReadTypeResource(mSubItemTexBuffer[8], 0xc00, 'TIMG', "cover_return.bti", archive);
        DCStoreRangeNoSync(mSubItemTexBuffer[8], 0xc00);
        ((J2DPicture*)m1038.pane)->changeTexture((ResTIMG*)mSubItemTexBuffer[8], 0);
        ((J2DPicture*)m1230.pane)->changeTexture((ResTIMG*)mSubItemTexBuffer[8], 0);
    }
}

/* 801C8724-801C8B14       .text cursorAnime__12dMenu_Item_cFv */
void dMenu_Item_c::cursorAnime() {
    s16 x_trans;
    s16 y_trans;
    u8 now = mNowItem;

    if (now == 0x15) {
        mA18[0].mPosCenterOrig.x = m1498.mPosCenter.x - m1498.mSize.x / 2.0f;
        mA18[0].mPosCenterOrig.y = m1498.mPosCenter.y + m1498.mSize.y / 2.0f;

        mA18[1].mPosCenterOrig.x = m1498.mPosCenter.x + m1498.mSize.x / 2.0f;
        mA18[1].mPosCenterOrig.y = m1498.mPosCenter.y + m1498.mSize.y / 2.0f;

        mA18[2].mPosCenterOrig.x = m1498.mPosCenter.x - m1498.mSize.x / 2.0f;
        mA18[2].mPosCenterOrig.y = m1498.mPosCenter.y - m1498.mSize.y / 2.0f;

        mA18[3].mPosCenterOrig.x = m1498.mPosCenter.x + m1498.mSize.x / 2.0f;
        mA18[3].mPosCenterOrig.y = m1498.mPosCenter.y - m1498.mSize.y / 2.0f;
    } else if (now >= 0x18) {
        u8 idx;
        if (now == 0xFF) {
            idx = 8;
        } else {
            idx = now - m2400;
        }

        for (int i = 0; i < 4; i++) {
            mA18[i].mPosCenterOrig.x = mE78[idx].mPosCenter.x + m23C0[i];
            mA18[i].mPosCenterOrig.y = mE78[idx].mPosCenter.y + m23D0[i];
        }
    } else {
        for (int i = 0; i < 4; i++) {
            mA18[i].mPosCenterOrig.x = m1658[now].mPosCenter.x + m23C0[i];
            mA18[i].mPosCenterOrig.y = m1658[now].mPosCenter.y + m23D0[i];
        }
    }

    if (mA18[0].mUserArea < g_miHIO.field_0x32) {
        for (int i = 0; i < 4; i++) {
            J2DPicture* picture = (J2DPicture*)mA18[i].pane;
            picture->setBlendColorRatio(1.0f, 0.0f, 1.0f, 1.0f);
            picture->setBlendAlphaRatio(1.0f, 0.0f, 1.0f, 1.0f);
        }

        x_trans = g_miHIO.field_0x34;
        y_trans = g_miHIO.field_0x34;
    } else if (mA18[0].mUserArea < g_miHIO.field_0x32 * 2) {
        for (int i = 0; i < 4; i++) {
            J2DPicture* picture = (J2DPicture*)mA18[i].pane;
            picture->setBlendColorRatio(0.0f, 1.0f, 1.0f, 1.0f);
            picture->setBlendAlphaRatio(0.0f, 1.0f, 1.0f, 1.0f);
        }

        x_trans = g_miHIO.field_0x36;
        y_trans = g_miHIO.field_0x36;
    }

    fopMsgM_paneTrans(&mA18[0], -x_trans, y_trans);
    fopMsgM_paneTrans(&mA18[1], x_trans, y_trans);
    fopMsgM_paneTrans(&mA18[2], -x_trans, -y_trans);
    fopMsgM_paneTrans(&mA18[3], x_trans, -y_trans);

    mA18[0].mUserArea++;

    if (mA18[0].mUserArea >= g_miHIO.field_0x32 * 2) {
        mA18[0].mUserArea = 0;
    }
}

/* 801C8B14-801C8CA0       .text cursorMainMove__12dMenu_Item_cFv */
void dMenu_Item_c::cursorMainMove() {
    stick->checkTrigger();
    u8 oldItem = mNowItem;

    if (stick->checkRightTrigger()) {
        if (mNowItem != 0x15) {
            if (mNowItem % 7 == 6) {
                mNowItem -= 6;
            } else {
                mNowItem += 1;
            }
        }
    } else if (stick->checkLeftTrigger()) {
        if (mNowItem != 0x15) {
            if (mNowItem % 7 == 0) {
                mNowItem += 6;
            } else {
                mNowItem -= 1;
            }
        }
    }

    if (stick->checkUpTrigger()) {
        if (mNowItem == 0x15) {
            mNowItem = 0xE;
        } else if (mNowItem > 6) {
            mNowItem -= 7;
        }
    } else if (stick->checkDownTrigger()) {
        if (mNowItem < 0xE) {
            mNowItem += 7;
        } else if (mNowItem >= 0xE) {
            if (mNowItem <= 0x14) {
                mNowItem = 0x15;
            }
        }
    }

    if (mNowItem != oldItem) {
        m858.mUserArea = 0;
        itemnameSet();
        mDoAud_seStart(JA_SE_ITM_MENU_CURSOR);
    }
}

/* 801C8CA0-801C8E60       .text cursorSubMove__12dMenu_Item_cFv */
void dMenu_Item_c::cursorSubMove() {
    s16 maxItems = g_menuHIO.field_0x82;
    u8 idx;

    if (mNowItem == 0xFF) {
        idx = 8;
    } else {
        idx = mNowItem - m2400;
    }

    stick->checkTrigger();

    if (stick->checkRightTrigger()) {
        if (idx % 3 != 2) {
            if (idx <= maxItems - 1) {
                idx += 1;
            }
        }
    } else if (stick->checkLeftTrigger()) {
        if (idx % 3 != 0) {
            idx -= 1;
        }
    }

    if (stick->checkUpTrigger()) {
        if (idx >= 3) {
            idx -= 3;
        }
    } else if (stick->checkDownTrigger()) {
        if ((u8)(idx + 3) <= maxItems) {
            idx += 3;
        }
    }

    if (idx != (u8)(mNowItem - m2400)) {
        if (idx == 8) {
            if (mNowItem != 0xFF) {
                mNowItem = 0xFF;
                mDoAud_seStart(JA_SE_ITM_MENU_CURSOR);
            }
        } else {
            mNowItem = idx + m2400;
            mDoAud_seStart(JA_SE_ITM_MENU_CURSOR);
        }

        m858.mUserArea = 0;
        itemnameSet();
    }
}

/* 801C8E60-801C9124       .text checkMove__12dMenu_Item_cFv */
void dMenu_Item_c::checkMove() {
    for (int i = 0; i < 3; i++) {
        u8 sel = dComIfGs_getSelectItem(i);

        if (sel != 0xFF) {
            m2030[i].pane->show();

            if (dMeter_subWinFlag()) {
                if (sel >= dInvSlot_ReserveFirst_e) {
                    if (m2405 == 2) {
                        u8 idx = sel - dInvSlot_ReserveFirst_e;
                        m2030[i].mPosCenter.x = mE78[idx].mPosCenter.x;
                        m2030[i].mPosCenter.y = mE78[idx].mPosCenter.y;
                        m231C->insertChild(m1230.pane, m2030[i].pane);
                    } else {
                        u8 slot = fopMsgM_itemNum(dItemNo_DELIVERY_BAG_e);
                        m2030[i].mPosCenter.x = m1658[slot].mPosCenterOrig.x;
                        m2030[i].mPosCenter.y = m1658[slot].mPosCenterOrig.y;
                        m231C->insertChild(m1AF0[20].pane, m2030[i].pane);
                    }
                } else if (sel >= dInvSlot_BaitFirst_e) {
                    if (m2405 == 1) {
                        u8 idx = sel - dInvSlot_BaitFirst_e;
                        m2030[i].mPosCenter.x = mE78[idx].mPosCenter.x;
                        m2030[i].mPosCenter.y = mE78[idx].mPosCenter.y;
                        m231C->insertChild(m1230.pane, m2030[i].pane);
                    } else {
                        u8 slot = fopMsgM_itemNum(dItemNo_BAIT_BAG_e);
                        m2030[i].mPosCenter.x = m1658[slot].mPosCenterOrig.x;
                        m2030[i].mPosCenter.y = m1658[slot].mPosCenterOrig.y;
                        m231C->insertChild(m1AF0[20].pane, m2030[i].pane);
                    }
                } else if (sel >= dInvSlot_BeastFirst_e) {
                    if (m2405 == 0) {
                        u8 idx = sel - dInvSlot_BeastFirst_e;
                        m2030[i].mPosCenter.x = mE78[idx].mPosCenter.x;
                        m2030[i].mPosCenter.y = mE78[idx].mPosCenter.y;
                        m231C->insertChild(m1230.pane, m2030[i].pane);
                    } else {
                        u8 slot = fopMsgM_itemNum(dItemNo_SPOILS_BAG_e);
                        m2030[i].mPosCenter.x = m1658[slot].mPosCenterOrig.x;
                        m2030[i].mPosCenter.y = m1658[slot].mPosCenterOrig.y;
                        m231C->insertChild(m1AF0[20].pane, m2030[i].pane);
                    }
                } else {
                    m2030[i].mPosCenter.x = m1658[sel].mPosCenterOrig.x;
                    m2030[i].mPosCenter.y = m1658[sel].mPosCenterOrig.y;
                    m231C->insertChild(m1AF0[20].pane, m2030[i].pane);
                }
            } else {
                if (sel >= dInvSlot_ReserveFirst_e) {
                    sel = fopMsgM_itemNum(dItemNo_DELIVERY_BAG_e);
                } else if (sel >= dInvSlot_BaitFirst_e) {
                    sel = fopMsgM_itemNum(dItemNo_BAIT_BAG_e);
                } else if (sel >= dInvSlot_BeastFirst_e) {
                    sel = fopMsgM_itemNum(dItemNo_SPOILS_BAG_e);
                }

                m2030[i].mPosCenter.x = m1658[sel].mPosCenterOrig.x;
                m2030[i].mPosCenter.y = m1658[sel].mPosCenterOrig.y;
                m231C->insertChild(m1AF0[20].pane, m2030[i].pane);
            }

            m2030[i].mPosCenterOrig.x = m2030[i].mPosCenter.x;
            m2030[i].mPosCenterOrig.y = m2030[i].mPosCenter.y;
            fopMsgM_cposMove(&m2030[i]);
        } else {
            m2030[i].pane->hide();
        }
    }
}

/* 801C9124-801C95FC       .text itemplaceCheck__12dMenu_Item_cFi */
u8 dMenu_Item_c::itemplaceCheck(int i_place) {
    static const int event[] = {0, 1, 2, 3};
    static const int attack[] = {7, 8, 9, 10};
    static const int bottle[] = {14, 15, 16, 17};
    static const int bag[] = {4, 11, 18};
    static const int wepon1[] = {5, 12, 19};
    static const int wepon2[] = {6, 13, 20};

    switch (i_place) {
    case 0:
        for (int i = 0; i < 4; i++) {
            if (dComIfGs_getItem(event[i]) != dItemNo_NONE_e) {
                return 1;
            }
        }
        break;
    case 1:
        for (int i = 0; i < 4; i++) {
            if (dComIfGs_getItem(attack[i]) != dItemNo_NONE_e) {
                return 1;
            }
        }
        break;
    case 2:
        for (int i = 0; i < 4; i++) {
            if (dComIfGs_getItem(bottle[i]) != dItemNo_NONE_e) {
                return 1;
            }
        }
        break;
    case 3:
        for (int i = 0; i < 3; i++) {
            if (dComIfGs_getItem(bag[i]) != dItemNo_NONE_e) {
                return 1;
            }
        }
        break;
    case 4:
        for (int i = 0; i < 3; i++) {
            if (dComIfGs_getItem(wepon1[i]) != dItemNo_NONE_e) {
                return 1;
            }
        }
        break;
    case 5:
        for (int i = 0; i < 3; i++) {
            if (dComIfGs_getItem(wepon2[i]) != dItemNo_NONE_e) {
                return 1;
            }
        }
        break;
    }

    return 0;
}

/* 801C95FC-801C9DF4       .text itemDecide__12dMenu_Item_cFv */
void dMenu_Item_c::itemDecide() {
    u8 other1;
    u8 other2;

    if (m2404 != 3) {
        dComIfGs_setSelectItem(m2404, m2401);
        dComIfGp_setSelectItem(m2404);
        m2404 = 3;

        if (m2403 != 3) {
            dComIfGs_setSelectItem(m2403, m2402);
            dComIfGp_setSelectItem(m2403);
            m2403 = 3;
        }

        mDoAud_seStart(JA_SE_ITM_MENU_SET);
    }

    if (CPad_CHECK_TRIG_X(0)) {
        m2404 = 0;
    } else if (CPad_CHECK_TRIG_Y(0)) {
        m2404 = 1;
    } else if (CPad_CHECK_TRIG_Z(0)) {
        m2404 = 2;
    }

    if (dComIfGs_getItem(mNowItem) == dItemNo_SPOILS_BAG_e) {
        m2405 = 0;
        subWindowInit();
        m2404 = 3;
        m2403 = 3;
        mDoAud_seStart(JA_SE_ITM_MENU_DECIDE);
        return;
    }

    if (dComIfGs_getItem(mNowItem) == dItemNo_BAIT_BAG_e) {
        m2405 = 1;
        subWindowInit();
        m2404 = 3;
        m2403 = 3;
        mDoAud_seStart(JA_SE_ITM_MENU_DECIDE);
        return;
    }

    if (dComIfGs_getItem(mNowItem) == dItemNo_DELIVERY_BAG_e) {
        m2405 = 2;
        subWindowInit();
        m2404 = 3;
        m2403 = 3;
        mDoAud_seStart(JA_SE_ITM_MENU_DECIDE);
        return;
    }

    if (m2404 == 0) {
        other1 = 1;
        other2 = 2;
    }
    if (m2404 == 1) {
        other1 = 2;
        other2 = 0;
    } else if (m2404 == 2) {
        other1 = 0;
        other2 = 1;
    }

    if (mNowItem == dComIfGs_getSelectItem(other1)) {
        m2403 = other1;
        m2402 = dComIfGs_getSelectItem(m2404);
        if (dMeter_subWinFlag()) {
            subWindowDelete();
        }
    } else if (mNowItem == dComIfGs_getSelectItem(other2)) {
        m2403 = other2;
        m2402 = dComIfGs_getSelectItem(m2404);
        if (dMeter_subWinFlag()) {
            subWindowDelete();
        }
    }

    m2401 = mNowItem;
    dMeter_itemMoveSet(&m1658[m2401], m2404, m2401);
    mDoAud_seStart(JA_SE_ITM_MENU_DECIDE);
}

/* 801C9DF4-801CA18C       .text itemMove__12dMenu_Item_cFv */
void dMenu_Item_c::itemMove() {
    if (dMeter_itemMoveFlagCheck() != 2) {
        return;
    }

    dComIfGs_setSelectItem(m2404, m2401);
    dComIfGp_setSelectItem(m2404);
    m2404 = 3;

    if (m2403 != 3) {
        dComIfGs_setSelectItem(m2403, m2402);
        dComIfGp_setSelectItem(m2403);
        m2403 = 3;
    }

    mDoAud_seStart(JA_SE_ITM_MENU_SET);
}

/* 801CA18C-801CA3F4       .text itemScale__12dMenu_Item_cFv */
void dMenu_Item_c::itemScale() {
    if (mNowItem == 0x15) {
        for (int i = 0; i < 21; i++) {
            fopMsgM_paneScaleXY(&m1658[i], 1.0f);
            fopMsgM_paneScaleXY(&m1AF0[i], 1.0f);
        }

        for (int i = 0; i < 8; i++) {
            fopMsgM_paneScaleXY(&mE78[i], 1.0f);
            fopMsgM_paneScaleXY(&m1070[i], 1.0f);
        }
    } else {
        int slot;
        if (mNowItem >= 0x30) {
            slot = 0x30;
        } else if (mNowItem >= 0x24) {
            slot = 0x2c;
        } else if (mNowItem >= 0x18) {
            slot = 0x24;
        } else {
            slot = mNowItem;
        }

        for (int i = 0; i < 21; i++) {
            if (i == slot && m2404 == 3) {
                fopMsgM_paneScaleXY(&m1658[i], g_menuHIO.field_0x8);
                fopMsgM_paneScaleXY(&m1AF0[i], g_menuHIO.field_0x8);

                if (slot == 0xC) {
                    for (int j = 0; j < 3; j++) {
                        m1F88[j].mPosCenter.x = m1658[i].mPosCenter.x + g_menuHIO.field_0x8 * (m1F88[j].mPosCenterOrig.x - m1658[i].mPosCenterOrig.x);
                        m1F88[j].mPosCenter.y = m1658[i].mPosCenter.y + g_menuHIO.field_0x8 * (m1F88[j].mPosCenterOrig.y - m1658[i].mPosCenterOrig.y);
                    }
                }
            } else {
                fopMsgM_paneScaleXY(&m1658[i], 1.0f);
                fopMsgM_paneScaleXY(&m1AF0[i], 1.0f);
            }
        }

        if (mNowItem == 0xFF) {
            for (int i = 0; i < 8; i++) {
                fopMsgM_paneScaleXY(&mE78[i], 1.0f);
                fopMsgM_paneScaleXY(&m1070[i], 1.0f);
            }
        } else if (mNowItem >= 0x15) {
            int sub = mNowItem - m2400;
            for (int i = 0; i < 8; i++) {
                if (i == sub && m2404 == 3) {
                    fopMsgM_paneScaleXY(&mE78[i], g_menuHIO.field_0x8);
                    fopMsgM_paneScaleXY(&m1070[i], g_menuHIO.field_0x8);
                } else {
                    fopMsgM_paneScaleXY(&mE78[i], 1.0f);
                    fopMsgM_paneScaleXY(&m1070[i], 1.0f);
                }
            }
        }
    }
}

/* 801CA3F4-801CAA04       .text subWindowInit__12dMenu_Item_cFv */
void dMenu_Item_c::subWindowInit() {
    dMeter_subWinFlagOn();
    m858.mUserArea = 0;

    if (m2405 == 0) {
        m2400 = 0x18;
        mNowItem = m2400;

        for (int i = 0; i < 8; i++) {
            u8 itemNo = dComIfGs_getItemBeast(i);
            if (itemNo != 0xFF) {
                mE78[i].mUserArea = 1;
                JKRArchive* archive = dComIfGp_getItemIconArchive();
                JKRReadTypeResource(mSubItemTexBuffer[i], 0xc00, 'TIMG', dItem_data::getTexture(itemNo), archive);
                DCStoreRangeNoSync(mSubItemTexBuffer[i], 0xc00);
                ((J2DPicture*)mE78[i].pane)->changeTexture((ResTIMG*)mSubItemTexBuffer[i], 0);
                ((J2DPicture*)m1070[i].pane)->changeTexture((ResTIMG*)mSubItemTexBuffer[i], 0);
                mE78[i].pane->show();
                m1070[i].pane->show();
                mCB8[i].pane->show();
                mAF8[i].pane->show();
            } else {
                mE78[i].mUserArea = 0;
                mE78[i].pane->hide();
                m1070[i].pane->hide();
                mCB8[i].pane->hide();
                mAF8[i].pane->hide();
            }

            u8 num = dComIfGs_getBeastNum(equipBeastItem(i));
            if (num == 0) {
                numberColor(mCB8[i].pane, 2);
                numberColor(mAF8[i].pane, 2);
            } else if (num == 0x63) {
                numberColor(mCB8[i].pane, 1);
                numberColor(mAF8[i].pane, 1);
            } else {
                numberColor(mCB8[i].pane, 0);
                numberColor(mAF8[i].pane, 0);
            }

            if (num < 10) {
                mCB8[i].pane->hide();
            } else {
                numberSet(mCB8[i].pane, num / 10);
            }

            numberSet(mAF8[i].pane, num % 10);
        }
    } else if (m2405 == 1) {
        m2400 = 0x24;
        mNowItem = m2400 + 3;

        for (int i = 0; i < 8; i++) {
            mCB8[i].pane->hide();
            u8 itemNo = dComIfGs_getItemBait(i);
            if (itemNo != 0xFF) {
                mE78[i].mUserArea = 1;
                JKRArchive* archive = dComIfGp_getItemIconArchive();
                JKRReadTypeResource(mSubItemTexBuffer[i], 0xc00, 'TIMG', dItem_data::getTexture(itemNo), archive);
                DCStoreRangeNoSync(mSubItemTexBuffer[i], 0xc00);
                ((J2DPicture*)mE78[i].pane)->changeTexture((ResTIMG*)mSubItemTexBuffer[i], 0);
                ((J2DPicture*)m1070[i].pane)->changeTexture((ResTIMG*)mSubItemTexBuffer[i], 0);
                mE78[i].pane->show();
                m1070[i].pane->show();
                if (itemNo == dItemNo_BIRD_BAIT_5_e) {
                    mAF8[i].pane->show();
                } else {
                    mAF8[i].pane->hide();
                }
            } else {
                mE78[i].mUserArea = 0;
                mE78[i].pane->hide();
                m1070[i].pane->hide();
                mAF8[i].pane->hide();
            }

            u8 num = dComIfGs_getBaitNum(i);
            if (num == 0) {
                numberColor(mCB8[i].pane, 2);
                numberColor(mAF8[i].pane, 2);
            } else if (num == 3) {
                numberColor(mCB8[i].pane, 1);
                numberColor(mAF8[i].pane, 1);
            } else {
                numberColor(mCB8[i].pane, 0);
                numberColor(mAF8[i].pane, 0);
            }

            numberSet(mAF8[i].pane, num % 10);
        }
    } else {
        m2400 = 0x30;
        mNowItem = m2400 + 6;

        for (int i = 0; i < 8; i++) {
            mCB8[i].pane->hide();
            mAF8[i].pane->hide();
            u8 itemNo = dComIfGs_getItemReserve(i);
            if (itemNo != 0xFF) {
                mE78[i].mUserArea = 1;
                JKRArchive* archive = dComIfGp_getItemIconArchive();
                JKRReadTypeResource(mSubItemTexBuffer[i], 0xc00, 'TIMG', dItem_data::getTexture(itemNo), archive);
                DCStoreRangeNoSync(mSubItemTexBuffer[i], 0xc00);
                ((J2DPicture*)mE78[i].pane)->changeTexture((ResTIMG*)mSubItemTexBuffer[i], 0);
                ((J2DPicture*)m1070[i].pane)->changeTexture((ResTIMG*)mSubItemTexBuffer[i], 0);
                mE78[i].pane->show();
                m1070[i].pane->show();
            } else {
                mE78[i].mUserArea = 0;
                mE78[i].pane->hide();
                m1070[i].pane->hide();
            }
        }
    }

    itemnameSet();

    for (int i = 0; i < 8; i++) {
        fopMsgM_paneScaleXY(&mE78[i], 1.0f);
        fopMsgM_paneScaleXY(&m1070[i], 1.0f);
    }

    for (int i = 0; i < 8; i++) {
        fopMsgM_setInitAlpha(&mAF8[i]);
        fopMsgM_setInitAlpha(&mCB8[i]);
        fopMsgM_setInitAlpha(&mE78[i]);
        fopMsgM_setInitAlpha(&m1070[i]);
    }

    fopMsgM_setInitAlpha(&m1038);
    fopMsgM_setInitAlpha(&m1230);

    for (int i = 0; i < 9; i++) {
        fopMsgM_setInitAlpha(&m1268[i]);
    }

    fopMsgM_setInitAlpha(&m1460);

    m231C->insertChild(mCB8[7].pane, mA18[3].pane);
    m231C->insertChild(mA18[3].pane, mA18[2].pane);
    m231C->insertChild(mA18[2].pane, mA18[1].pane);
    m231C->insertChild(mA18[1].pane, mA18[0].pane);
}

/* 801CAA04-801CAB48       .text subWindowDelete__12dMenu_Item_cFv */
void dMenu_Item_c::subWindowDelete() {
    m858.mUserArea = 0;

    if (m2405 == 0) {
        mNowItem = fopMsgM_itemNum(dItemNo_SPOILS_BAG_e);
    } else if (m2405 == 1) {
        mNowItem = fopMsgM_itemNum(dItemNo_BAIT_BAG_e);
    } else {
        mNowItem = fopMsgM_itemNum(dItemNo_DELIVERY_BAG_e);
    }

    itemnameSet();
    itemScale();
    dMeter_subWinFlagOff();

    for (int i = 0; i < 8; i++) {
        fopMsgM_setNowAlphaZero(&mAF8[i]);
        fopMsgM_setNowAlphaZero(&mCB8[i]);
        fopMsgM_setNowAlphaZero(&mE78[i]);
        fopMsgM_setNowAlphaZero(&m1070[i]);
    }

    fopMsgM_setNowAlphaZero(&m1038);
    fopMsgM_setNowAlphaZero(&m1230);

    for (int i = 0; i < 9; i++) {
        fopMsgM_setNowAlphaZero(&m1268[i]);
    }

    fopMsgM_setNowAlphaZero(&m1460);

    m231C->insertChild(m1460.pane, mA18[3].pane);
    m231C->insertChild(mA18[3].pane, mA18[2].pane);
    m231C->insertChild(mA18[2].pane, mA18[1].pane);
    m231C->insertChild(mA18[1].pane, mA18[0].pane);
}

/* 801CAB48-801CB020       .text subItemDecide__12dMenu_Item_cFv */
void dMenu_Item_c::subItemDecide() {
    u8 other1;
    u8 other2;

    if (m2404 != 3) {
        dComIfGs_setSelectItem(m2404, m2401);
        dComIfGp_setSelectItem(m2404);
        m2404 = 3;

        if (m2403 != 3) {
            dComIfGs_setSelectItem(m2403, m2402);
            dComIfGp_setSelectItem(m2403);
            m2403 = 3;
        }

        mDoAud_seStart(JA_SE_ITM_MENU_SET);
    }

    if (CPad_CHECK_TRIG_X(0)) {
        m2404 = 0;
    } else if (CPad_CHECK_TRIG_Y(0)) {
        m2404 = 1;
    } else if (CPad_CHECK_TRIG_Z(0)) {
        m2404 = 2;
    }

    if (m2404 == 0) {
        other1 = 1;
        other2 = 2;
    } else if (m2404 == 1) {
        other1 = 2;
        other2 = 0;
    } else if (m2404 == 2) {
        other1 = 0;
        other2 = 1;
    }

    if (mNowItem == dComIfGs_getSelectItem(other1)) {
        m2403 = other1;
        m2402 = dComIfGs_getSelectItem(m2404);
    } else if (mNowItem == dComIfGs_getSelectItem(other2)) {
        m2403 = other2;
        m2402 = dComIfGs_getSelectItem(m2404);
    }

    m2401 = mNowItem;
    dMeter_itemMoveSet(&mE78[m2401 - m2400], m2404, m2401);
    mDoAud_seStart(JA_SE_ITM_MENU_DECIDE);

    if (dMeter_subWinFlag()) {
        subWindowDelete();
    }
}

/* 801CB020-801CB168       .text itemnameMove__12dMenu_Item_cFv */
void dMenu_Item_c::itemnameMove() {
    m858.mUserArea++;

    if (m858.mUserArea > 0x82) {
        m858.mUserArea = 0x0B;
    }

    int timer = m858.mUserArea;

    if (timer <= 10) {
        f32 t = fopMsgM_valueIncrease(10, timer, 0);
        fopMsgM_setNowAlpha(&m890[0], t);
        fopMsgM_setNowAlpha(&m890[1], 1.0f - t);
        fopMsgM_setNowAlphaZero(&m858);
    } else if (timer <= 60) {
        fopMsgM_setInitAlpha(&m890[0]);
        fopMsgM_setNowAlphaZero(&m858);
    } else if (timer <= 70) {
        f32 t = fopMsgM_valueIncrease(10, timer - 60, 0);
        fopMsgM_setNowAlpha(&m890[0], 1.0f - t);
        fopMsgM_setNowAlpha(&m858, t);
    } else if (timer <= 120) {
        fopMsgM_setNowAlphaZero(&m890[0]);
        fopMsgM_setInitAlpha(&m858);
    } else if (timer <= 130) {
        f32 t = fopMsgM_valueIncrease(10, timer - 120, 0);
        fopMsgM_setNowAlpha(&m890[0], t);
        fopMsgM_setNowAlpha(&m858, 1.0f - t);
    }

    outFont->move();
}

/* 801CB168-801CB7C0       .text itemnameSet__12dMenu_Item_cFv */
void dMenu_Item_c::itemnameSet() {
    fopMsgM_itemMsgGet_c msgGet;
    u32 msgNo = 0;
    int r30 = 0;
    int i = 0;

    J2DTextBox::TFontSize initialFontSize;
    initialFontSize.mSizeY = 29.0f;
    initialFontSize.mSizeX = 29.0f;
    ((J2DTextBox*)m858.pane)->setFontSize(initialFontSize);

    J2DTextBox::TFontSize copiedFontSize;
    ((J2DTextBox*)m890[0].pane)->getFontSize(copiedFontSize);
    ((J2DTextBox*)m890[1].pane)->setFontSize(copiedFontSize);
    ((J2DTextBox*)m890[1].pane)->setCharSpace(((J2DTextBox*)m890[0].pane)->getCharSpace());

    while (name[0][i] != 0) {
        name[1][i] = name[0][i];
        i++;
    }
    name[1][i] = 0;
    ((J2DTextBox*)m890[1].pane)->setString(name[1]);
    strcpy(name[0], "");

    if (mNowItem == 0x15) {
        msgNo = 0x1F8;
    } else if (dComIfGs_getItem(mNowItem) == dItemNo_NONE_e) {
        return;
    } else {
        msgNo = dItem_data::getItemMesgNum(dComIfGs_getItem(mNowItem));
        if (msgNo == 0) {
            msgNo = 0x19C;
        }
    }

    mesg_header* head_p = msgGet.getMesgHeader(msgNo);
    JUT_ASSERT(0x565, head_p);

    J2DTextBox::TFontSize fontSize;
    ((J2DTextBox*)m890[0].pane)->getFontSize(fontSize);
    fontSize.mSizeX = fontSize.mSizeY;

    char* src;
    f32 strWidth;
    char* mesg = (char*)msgGet.getMessage(head_p);
    bool first = false;
    f32 scale = fontSize.mSizeY / mFont->getCellWidth();
    src = mesg;

    while ((s8)*src != 0) {
        char charStr[3];
        int byte = 0;
        charStr[2] = byte;
        charStr[1] = byte;
        charStr[0] = byte;

        u32 c = (u8)(*(u8*)src);
        if (c == 0x1A) {
            src++;
            src += (s8)*src - 1;
        } else {
            int charCode;
            int hi_nibble = (c >> 4) & 0xF;
            if (hi_nibble == 8 || hi_nibble == 9) {
                byte = (u8)src[0];
                c = (u8)src[1];
                charCode = c;
                charCode |= byte << 8;
                charStr[0] = byte;
                charStr[1] = c;
                charStr[2] = 0;
                src += 2;
            } else {
                charCode = c;
                charStr[0] = c;
                charStr[1] = byte;
                src += 1;
            }

            int width = mFont->getWidth(charCode);
            strcat(name[0], charStr);
            if (!first) {
                strWidth = scale * (width + mFont->getOffset(charCode));
                first = true;
            } else {
                strWidth += width * scale;
            }
        }
    }

    if (((J2DTextBox*)m890[0].pane)->getWidth() < strWidth) {
        fontSize.mSizeX = (int)(fontSize.mSizeX * ((J2DTextBox*)m890[0].pane)->getWidth() / strWidth);
    }

    ((J2DTextBox*)m890[0].pane)->setFontSize(fontSize);
    ((J2DTextBox*)m890[0].pane)->setCharSpace((f32)r30);
    ((J2DTextBox*)m890[0].pane)->setString(name[0]);

    if (mNowItem == 0x15) {
        outFont->messageSet(0x1FC);
    } else if (mNowItem == 4 || mNowItem == 0xB || mNowItem == 0x12) {
        outFont->messageSet(0x1F5);
    } else {
        outFont->messageSet(0x1F9);
    }

    outFont->setLeftUpPos(m858.mPosTopLeft.x, m858.mPosTopLeft.y);
}

/* 801CB7C0-801CBEBC       .text itemnoteSet__12dMenu_Item_cFv */
void dMenu_Item_c::itemnoteSet() {
    fopMsgM_itemMsgGet_c msgGet;
    fopMsgM_msgDataProc_c msgProc;
    u32 msgNo;

    strcpy(note[0], "");
    strcpy(note[1], "");
    strcpy(dummy[0], "");
    strcpy(dummy[1], "");

    outFontInit();

    if (dComIfGs_getOptRuby()) {
        m740.pane->hide();
    } else {
        m740.pane->show();
    }

    f32 rubySize = ((J2DTextBox*)m740.pane)->mFontSizeX;
    J2DTextBox::TFontSize fontSize;
    fontSize.mSizeX = g_msgHIO.field_0x70;
    fontSize.mSizeY = g_msgHIO.field_0x70;
    ((J2DTextBox*)m778.pane)->setFontSize(fontSize);
    ((J2DTextBox*)m778.pane)->setLineSpace(g_msgHIO.field_0x5e);

    if (dComIfGs_getItem(mNowItem) == dItemNo_NONE_e) {
        return;
    }

    msgNo = dItem_data::getItemMesgNum(dComIfGs_getItem(mNowItem));
    if (msgNo == 0) {
        msgNo = 0x264;
    } else {
        msgNo = msgNo + 0xC8;
    }

    mesg_header* head_p = msgGet.getMesgHeader(msgNo);
    JUT_ASSERT(0x5F1, head_p);

    const char* mesg = msgGet.getMessage(head_p);
    JMSMesgEntry_c msg_entry;
    msg_entry = msgGet.getMesgEntry(head_p);

    msgProc.dataInit();
    msgProc.setBmgData((char*)mesg);
    msgProc.setOutMessage(note[0], note[1], dummy[0], dummy[1]);
    msgProc.setFont(mFont);
    msgProc.setRubyFont(mRFont);
    msgProc.setCharSpace(((J2DTextBox*)m778.pane)->getCharSpace());
    msgProc.setRubyCharSpace(((J2DTextBox*)m740.pane)->getCharSpace());
    msgProc.setLineSpace(((J2DTextBox*)m778.pane)->getLineSpace());
    msgProc.setMesgEntry(&msg_entry);
    msgProc.setFontSize(fontSize.mSizeX);
    msgProc.setRubyFontSize(rubySize);
    msgProc.setLineWidth(0x1FE);
    msgProc.setCenterLineWidth(0x1E6);
    msgProc.setSendSpeed(2);
    msgProc.setSpaceTimer(0);
    msgProc.shortCut();
    msgProc.setSpaceFlagOff();

    msgProc.stringLength();
    msgProc.stringShift();
    msgProc.iconIdxRefresh();

    s16 lineCount = msgProc.getLineCount();
    msgProc.setLineCount(0);
    f32 lineSpace = ((J2DTextBox*)m778.pane)->getLineSpace();
    int unusedLines = 3 - lineCount;
    f32 shiftY = unusedLines * (lineSpace / 2.0f);
    ((J2DTextBox*)m740.pane)->shiftSet(0.0f, shiftY);
    ((J2DTextBox*)m778.pane)->shiftSet(0.0f, shiftY);
    msgProc.stringSet();

    ((J2DTextBox*)m778.pane)->setString(note[0]);
    ((J2DTextBox*)m740.pane)->setString(note[1]);

    int halfSpace = ((J2DTextBox*)m778.pane)->getLineSpace() / 2.0f;
    for (int i = 0; i < 15; i++) {
        u8 iconNo = msgProc.getIconNum(i);
        u32 color = msgProc.getIconColor(i);
        if (color == 0xFFFFFFFF) {
            color = 0xFF;
        }
        if (iconNo == 0xFF) {
            continue;
        }
        if (m0B0[i].mUserArea != -1) {
            continue;
        }
        if (iconNo == fopMsgM_Icon_INPUT_e) {
            continue;
        }
        m0B0[i].mPosTopLeft.x = (f32)msgProc.getIconPosX(i);
        m0B0[i].mPosTopLeft.y = (f32)(halfSpace * (unusedLines + msgProc.getIconPosY(i) * 2));
        m0B0[i].mPosTopLeftOrig.y = (f32)iconNo;

        fopMsgM_outFontSet((J2DPicture*)m0B0[i].pane, &m0B0[i].mUserArea, color, iconNo);
    }
}

/* 801CBEBC-801CBF44       .text outFontInit__12dMenu_Item_cFv */
void dMenu_Item_c::outFontInit() {
    for (int i = 0; i < 15; i++) {
        m0B0[i].mUserArea = -1;
        m0B0[i].pane->rotate(0.0f);
        fopMsgM_setNowAlphaZero(&m0B0[i]);
    }
}

/* 801CBF44-801CC030       .text outFontMove__12dMenu_Item_cFv */
void dMenu_Item_c::outFontMove() {
    for (int i = 0; i < 15; i++) {
        if (m0B0[i].mUserArea != -1) {
            m3F8[i].mPosTopLeft.x = m0B0[i].mPosTopLeft.x + (m778.mPosTopLeft.x + (m820.mPosTopLeft.x + m7B0.mPosTopLeft.x));
            m3F8[i].mPosTopLeft.y = m0B0[i].mPosTopLeft.y + (m778.mPosTopLeft.y + (m820.mPosTopLeft.y + m7B0.mPosTopLeft.y));

            f32 rotOffX = m820.mPosCenter.x - m3F8[i].mPosTopLeft.x;
            f32 rotOffY = m820.mPosCenter.y - m3F8[i].mPosTopLeft.y;
            m3F8[i].pane->rotate(rotOffX, rotOffY, ROTATE_Z, m820.pane->getRotate());
        } else {
            fopMsgM_setNowAlphaZero(&m0B0[i]);
        }
    }
}

/* 801CC030-801CC0F8       .text outFontDraw__12dMenu_Item_cFv */
void dMenu_Item_c::outFontDraw() {
    for (int i = 0; i < 15; i++) {
        if (m0B0[i].mUserArea != -1) {
            m0B0[i].mNowAlpha = m778.pane->getAlpha();
            fopMsgM_outFontDraw2(
                (J2DPicture*)m0B0[i].pane,
                (J2DPicture*)m3F8[i].pane,
                (int)m3F8[i].mPosTopLeft.x,
                (int)m3F8[i].mPosTopLeft.y,
                g_msgHIO.field_0x70,
                g_msgHIO.field_0x70,
                &m0B0[i].mUserArea,
                m0B0[i].mNowAlpha,
                m0B0[i].mPosTopLeftOrig.y
            );
        } else {
            fopMsgM_setAlpha(&m0B0[i]);
        }
    }
}

/* 801CC0F8-801CC10C       .text noteCheck__12dMenu_Item_cFv */
u8 dMenu_Item_c::noteCheck() {
    return m7E8.mUserArea == 1;
}

/* 801CC10C-801CC1AC       .text noteInit__12dMenu_Item_cFv */
void dMenu_Item_c::noteInit() {
    m7E8.mUserArea = 0;
    m7B0.mUserArea = 0;

    m820.pane->rotate(m820.mSizeOrig.x / 2.0f, m820.mSizeOrig.y / 2.0f, ROTATE_Z, m820.mUserArea);
    fopMsgM_paneTrans(&m820, 0.0f, 0.0f);
}

/* 801CC1AC-801CC278       .text noteAppear__12dMenu_Item_cFv */
void dMenu_Item_c::noteAppear() {
    s16 threshold = g_miHIO.field_0x38 + g_miHIO.field_0x3A;

    if (m7E8.mUserArea == 1) {
        if (m7B0.mUserArea <= threshold) {
            noteOpen();
        } else if (m7B0.mUserArea > threshold + 1) {
            noteClose();
        } else {
            u8 alpha = g_miHIO.field_0x5C;
            m970.mNowAlpha = alpha;
            m970.mInitAlpha = alpha;

            if (CPad_CHECK_TRIG_A(0) || CPad_CHECK_TRIG_B(0)) {
                m7B0.mUserArea++;
                mDoAud_seStart(JA_SE_ITM_MENU_EXP_OUT);
            }
        }
    }
}

/* 801CC278-801CC4F8       .text noteOpen__12dMenu_Item_cFv */
void dMenu_Item_c::noteOpen() {
    s16 angle_target = g_miHIO.field_0x30;
    s16 threshold = g_miHIO.field_0x38 + g_miHIO.field_0x3A;
    f32 dx = g_miHIO.field_0x40 - m820.mPosCenterOrig.x;
    f32 dy = g_miHIO.field_0x42 - m820.mPosCenterOrig.y;
    f32 t = 1.0f - fopMsgM_valueIncrease(threshold, threshold - m7B0.mUserArea, 0);

    if (m7B0.mUserArea >= threshold) {
        fopMsgM_setInitAlpha(&m970);
        fopMsgM_setInitAlpha(&m740);
        fopMsgM_setInitAlpha(&m778);
        mDoAud_seStart(JA_SE_ITM_MENU_EXP_IN);
    } else {
        fopMsgM_setNowAlpha(&m970, t);
        fopMsgM_setNowAlpha(&m740, t);
        fopMsgM_setNowAlpha(&m778, t);
    }

    m820.pane->rotate(m820.mSize.x / 2.0f, m820.mSize.y / 2.0f, ROTATE_Z, m820.mUserArea + t * (angle_target - m820.mUserArea));

    f32 scale;
    if (m7B0.mUserArea < g_miHIO.field_0x38) {
        scale = (g_miHIO.field_0x08 * m7B0.mUserArea) / g_miHIO.field_0x38;
    } else {
        scale = (1.0f - fopMsgM_valueIncrease(g_miHIO.field_0x3A, threshold - m7B0.mUserArea, 0)) * (1.0f - g_miHIO.field_0x08) + g_miHIO.field_0x08;
    }

    fopMsgM_paneTrans(&m820, dx * scale, dy * scale);
    m7B0.mUserArea++;
}

/* 801CC4F8-801CC7D4       .text noteClose__12dMenu_Item_cFv */
void dMenu_Item_c::noteClose() {
    s16 angle_start = g_miHIO.field_0x30;
    s16 angle_end = g_miHIO.field_0x44;
    s16 threshold = g_miHIO.field_0x38 + g_miHIO.field_0x3A;
    s16 close_frames = g_miHIO.field_0x3C;
    f32 cx = g_miHIO.field_0x40;
    f32 cy = g_miHIO.field_0x42;
    f32 fVar2 = (2.0f * cx - m820.mPosCenterOrig.x) - cx;
    f32 fVar3 = (2.0f * cy - m820.mPosCenterOrig.y) - cy;
    f32 fVar4 = cx - m820.mPosCenterOrig.x;
    f32 fVar5 = cy - m820.mPosCenterOrig.y;
    f32 t = fopMsgM_valueIncrease(close_frames, m7B0.mUserArea - (threshold + 1), 0);

    fopMsgM_paneTrans(&m820, fVar4 + fVar2 * t, fVar5 + fVar3 * t);
    m820.pane->rotate(m820.mSize.x / 2.0f, m820.mSize.y / 2.0f, ROTATE_Z, angle_start + t * (angle_end - angle_start));
    m7B0.mUserArea++;

    if (m7B0.mUserArea > threshold + 1 + close_frames) {
        fopMsgM_setInitAlpha(&m7B0);
        fopMsgM_setInitAlpha(&m7E8);
        fopMsgM_setInitAlpha(&m820);
        fopMsgM_setNowAlphaZero(&m970);
        fopMsgM_setNowAlphaZero(&m740);
        fopMsgM_setNowAlphaZero(&m778);

        m7E8.mUserArea = 0;
        m7B0.mUserArea = 0;

        m820.pane->rotate(m820.mSize.x / 2.0f, m820.mSize.y / 2.0f, ROTATE_Z, m820.mUserArea);
        fopMsgM_paneTrans(&m820, 0.0f, 0.0f);
    } else {
        fopMsgM_setNowAlpha(&m7B0, 1.0f - t);
        fopMsgM_setNowAlpha(&m7E8, 1.0f - t);
        fopMsgM_setNowAlpha(&m820, 1.0f - t);
        fopMsgM_setNowAlpha(&m970, 1.0f - t);
        fopMsgM_setNowAlpha(&m740, 1.0f - t);
        fopMsgM_setNowAlpha(&m778, 1.0f - t);
    }
}

/* 801CC7D4-801CC9D8       .text mainTrans__12dMenu_Item_cFff */
void dMenu_Item_c::mainTrans(float i_transX, float i_transY) {
    fopMsgM_paneTrans(&m1498, i_transX, i_transY);
    fopMsgM_paneTrans(&m14D0, i_transX, i_transY);
    fopMsgM_paneTrans(&m1508, i_transX, i_transY);
    fopMsgM_paneTrans(&m1540, i_transX, i_transY);
    fopMsgM_paneTrans(&m1578, i_transX, i_transY);
    fopMsgM_paneTrans(&m15B0, i_transX, i_transY);
    fopMsgM_paneTrans(&m15E8, i_transX, i_transY);
    fopMsgM_paneTrans(&m1620, i_transX, i_transY);

    for (int i = 0; i < 21; i++) {
        fopMsgM_paneTrans(&m1658[i], i_transX, i_transY);
        fopMsgM_paneTrans(&m1AF0[i], i_transX, i_transY);
    }

    for (int i = 0; i < 3; i++) {
        fopMsgM_paneTrans(&m1F88[i], i_transX, i_transY);
    }

    for (int i = 0; i < 6; i++) {
        fopMsgM_paneTrans(&m20D8[i], i_transX, i_transY);
    }

    fopMsgM_paneTrans(&m2228, i_transX, i_transY);
    fopMsgM_paneTrans(&m2260, i_transX, i_transY);
    fopMsgM_paneTrans(&m2298, i_transX, i_transY);
    fopMsgM_paneTrans(&m22D0, i_transX, i_transY);

    for (int i = 0; i < 4; i++) {
        fopMsgM_paneTrans(&mA18[i], i_transX, i_transY);
    }

    for (int i = 0; i < 3; i++) {
        if (dComIfGp_getSelectItem(i) == 0xFF) {
            continue;
        }

        fopMsgM_paneTrans(&m2030[i], i_transX, i_transY);
    }
}

/* 801CC9D8-801CC9FC       .text titleTrans__12dMenu_Item_cFff */
void dMenu_Item_c::titleTrans(float i_transX, float i_transY) {
    fopMsgM_paneTrans(&m9E0, i_transX, i_transY);
}

/* 801CC9FC-801CCA88       .text noteRotate__12dMenu_Item_cFff */
void dMenu_Item_c::noteRotate(float i_transY, float i_angle) {
    fopMsgM_paneTrans(&m820, 0.0f, i_transY);
    m820.pane->rotate(m820.mSize.x / 2.0f, m820.mSize.y / 2.0f, ROTATE_Z, i_angle);
}

/* 801CCA88-801CCB3C       .text nameTrans__12dMenu_Item_cFff */
void dMenu_Item_c::nameTrans(float i_transX, float i_transY) {
    fopMsgM_paneTrans(&m858, i_transX, i_transY);

    outFont->setLeftUpPos(m858.mPosTopLeft.x, m858.mPosTopLeft.y);
    outFont->move();

    fopMsgM_paneTrans(&m890[0], i_transX, i_transY);
    fopMsgM_paneTrans(&m890[1], i_transX, i_transY);
    fopMsgM_paneTrans(&m900, i_transX, i_transY);
    fopMsgM_paneTrans(&m938, i_transX, i_transY);
}

/* 801CCB3C-801CCD74       .text mainOpenProc__12dMenu_Item_cFsss */
void dMenu_Item_c::mainOpenProc(short i_step, short i_max, short i_offset) {
    if (i_max >= i_step) {
        float open_t = fopMsgM_valueIncrease(i_max, i_step, 0);

        mainTrans(i_offset * fopMsgM_valueIncrease(i_max, i_max - i_step, 0), 0.0f);

        fopMsgM_setNowAlpha(&m1498, open_t);
        fopMsgM_setNowAlpha(&m14D0, open_t);
        fopMsgM_setNowAlpha(&m1508, open_t);
        fopMsgM_setNowAlpha(&m1540, open_t);
        fopMsgM_setNowAlpha(&m1578, open_t);
        fopMsgM_setNowAlpha(&m15B0, open_t);
        fopMsgM_setNowAlpha(&m15E8, open_t);
        fopMsgM_setNowAlpha(&m1620, open_t);

        for (int i = 0; i < 21; i++) {
            fopMsgM_setNowAlpha(&m1658[i], open_t);
            fopMsgM_setNowAlpha(&m1AF0[i], open_t);
        }

        for (int i = 0; i < 6; i++) {
            if (itemplaceCheck(i)) {
                fopMsgM_setNowAlpha(&m20D8[i], open_t);
            }
        }

        fopMsgM_setNowAlpha(&m2228, open_t);
        fopMsgM_setNowAlpha(&m2260, open_t);
        fopMsgM_setNowAlpha(&m2298, open_t);
        fopMsgM_setNowAlpha(&m22D0, open_t);

        for (int i = 0; i < 4; i++) {
            fopMsgM_setNowAlpha(&mA18[i], open_t);
        }

        for (int i = 0; i < 3; i++) {
            fopMsgM_setNowAlpha(&m1F88[i], open_t);
            fopMsgM_setNowAlpha(&m2030[i], open_t);

            if (dComIfGp_getSelectItem(i) != 0xFF) {
                m2030[i].pane->show();
            } else {
                m2030[i].pane->hide();
            }
        }
    }
}

/* 801CCD74-801CCE5C       .text titleOpenProc__12dMenu_Item_cFss */
void dMenu_Item_c::titleOpenProc(short i_step, short i_max) {
    int trans = g_miHIO.field_0x28;

    if (i_max >= i_step) {
        fopMsgM_valueIncrease(i_max, i_step, 0);
        titleTrans(0.0f, fopMsgM_valueIncrease(i_max, i_max - i_step, 0) * (s16)trans);

        fopMsgM_setInitAlpha(&m9A8);
        fopMsgM_setInitAlpha(&m9E0);

        if (i_step == 1) {
            mDoAud_seStart(JA_SE_ITM_MENU_PANEL_IN);
        }
    }
}

/* 801CCE5C-801CCF50       .text noteOpenProc__12dMenu_Item_cFss */
void dMenu_Item_c::noteOpenProc(short i_step, short i_max) {
    s16 angle_target = g_miHIO.field_0x2A;
    s16 trans = g_miHIO.field_0x3E;

    if (i_max >= i_step) {
        fopMsgM_valueIncrease(i_max, i_step, 0);
        f32 t = fopMsgM_valueIncrease(i_max, i_max - i_step, 0);
        f32 angle = m820.mUserArea + t * (angle_target - m820.mUserArea);

        noteRotate(trans * t, angle);

        for (int i = 0; i < 6; i++) {
            fopMsgM_setInitAlpha(&m7B0);
            fopMsgM_setInitAlpha(&m7E8);
        }
    }
}

/* 801CCF50-801CD004       .text nameOpenProc__12dMenu_Item_cFss */
void dMenu_Item_c::nameOpenProc(short i_step, short i_max) {
    int trans = g_miHIO.field_0x2C;

    if (i_max >= i_step) {
        fopMsgM_valueIncrease(i_max, i_step, 0);
        nameTrans(0.0f, fopMsgM_valueIncrease(i_max, i_max - i_step, 0) * (s16)trans);

        fopMsgM_setInitAlpha(&m890[0]);
        fopMsgM_setInitAlpha(&m900);
        fopMsgM_setInitAlpha(&m938);
    }
}

/* 801CD004-801CD04C       .text numberSet__12dMenu_Item_cFP7J2DPaneUc */
void dMenu_Item_c::numberSet(J2DPane* pane, unsigned char num) {
    static char* number[] = {
        "count_num_0.bti",
        "count_num_1.bti",
        "count_num_2.bti",
        "count_num_3.bti",
        "count_num_4.bti",
        "count_num_5.bti",
        "count_num_6.bti",
        "count_num_7.bti",
        "count_num_8.bti",
        "count_num_9.bti",
    };

    if (num >= 10) {
        num = 0;
    }

    ((J2DPicture*)pane)->changeTexture(number[num], 0);
}

/* 801CD04C-801CD194       .text numberColor__12dMenu_Item_cFP7J2DPaneUc */
void dMenu_Item_c::numberColor(J2DPane* pane, unsigned char num) {
    J2DPicture* pic = (J2DPicture*)pane;

    switch (num) {
    case 1:
        pic->setWhite(0xFFC832FF);
        pic->setBlack(0x1E1E1E00);
        break;
    case 2:
        pic->setWhite(0xB4B4B4FF);
        pic->setBlack(0x1E1E1E00);
        break;
    default:
        pic->setWhite(0xFFFFFFFF);
        pic->setBlack(0x00000000);
        break;
    }
}

/* 801CD194-801CD3FC       .text itemNumberSet__12dMenu_Item_cFv */
void dMenu_Item_c::itemNumberSet() {
    numberSet(m1540.pane, dComIfGs_getPictureNum());

    if (dComIfGs_getPictureNum() == 0) {
        numberColor(m1540.pane, 2);
    } else if (dComIfGs_getPictureNum() == 3) {
        numberColor(m1540.pane, 1);
    } else {
        numberColor(m1540.pane, 0);
    }

    m241E = dComIfGs_getPictureNum();

    if (dComIfGs_getArrowNum() == 0) {
        numberColor(m1578.pane, 2);
        numberColor(m15B0.pane, 2);
    } else if (dComIfGs_getArrowNum() == dComIfGs_getArrowMax()) {
        numberColor(m1578.pane, 1);
        numberColor(m15B0.pane, 1);
    } else {
        numberColor(m1578.pane, 0);
        numberColor(m15B0.pane, 0);
    }

    if (dComIfGs_getArrowNum() < 10) {
        m15B0.pane->hide();
    } else {
        numberSet(m15B0.pane, dComIfGs_getArrowNum() / 10);
    }

    numberSet(m1578.pane, dComIfGs_getArrowNum() % 10);
    m241F = dComIfGs_getArrowNum();

    if (dComIfGs_getBombNum() == 0) {
        numberColor(m15E8.pane, 2);
        numberColor(m1620.pane, 2);
    } else if (dComIfGs_getBombNum() == dComIfGs_getBombMax()) {
        numberColor(m15E8.pane, 1);
        numberColor(m1620.pane, 1);
    } else {
        numberColor(m15E8.pane, 0);
        numberColor(m1620.pane, 0);
    }

    if (dComIfGs_getBombNum() < 10) {
        m1620.pane->hide();
    } else {
        numberSet(m1620.pane, dComIfGs_getBombNum() / 10);
    }

    numberSet(m15E8.pane, dComIfGs_getBombNum() % 10);
    m2420 = dComIfGs_getBombNum();
}

/* 801CD3FC-801CDA14       .text itemCheck__12dMenu_Item_cFi */
void dMenu_Item_c::itemCheck(int i_slot) {
    u8 itemNo = dComIfGs_getItem(i_slot);

    if (itemNo != dItemNo_NONE_e) {
        if (recollectBossCheck() && (
            itemNo == dItemNo_WATER_BOTTLE_e ||
            itemNo == dItemNo_FIREFLY_BOTTLE_e ||
            itemNo == dItemNo_FOREST_WATER_e))
        {
            m1658[i_slot].pane->hide();
            m1AF0[i_slot].pane->hide();
        }

        if (itemNo == dItemNo_MAGIC_ARROW_e) {
            m1F88[0].pane->show();
            m1F88[1].pane->show();
            m1F88[2].pane->hide();
            itemNo = dItemNo_BOW_e;
        } else if (itemNo == dItemNo_LIGHT_ARROW_e) {
            m1F88[0].pane->show();
            m1F88[1].pane->show();
            m1F88[2].pane->show();
            itemNo = dItemNo_BOW_e;
        } else if (itemNo == dItemNo_FOREST_WATER_e) {
            if (!(recollectBossCheck() && (
                itemNo == dItemNo_WATER_BOTTLE_e ||
                ((u8)(itemNo - dItemNo_FIREFLY_BOTTLE_e) <= 1))))
            {
                cXyz pos;
                pos.x = m1658[i_slot].mPosCenter.x - 320.0f;
                pos.y = m1658[i_slot].mPosCenter.y - 240.0f;
                pos.z = 0.0f;

                if (m23B8[0] == NULL) {
                    m23B8[0] = dComIfGp_particle_set2DmenuFore(0x2D, &pos);
                }
                if (m23B8[1] == NULL) {
                    m23B8[1] = dComIfGp_particle_set2DmenuFore(0x2D, &pos);
                }
            }
        }

        JKRArchive* archive = dComIfGp_getItemIconArchive();
        JKRReadTypeResource(mItemTexBuffer[i_slot], 0xc00, 'TIMG', dItem_data::getTexture(itemNo), archive);
        DCStoreRangeNoSync(mItemTexBuffer[i_slot], 0xc00);
        ((J2DPicture*)m1658[i_slot].pane)->changeTexture((ResTIMG*)mItemTexBuffer[i_slot], 0);
        ((J2DPicture*)m1AF0[i_slot].pane)->changeTexture((ResTIMG*)mItemTexBuffer[i_slot], 0);

        if (i_slot == 8) {
            u8 picto = dComIfGs_getItem(i_slot);
            if (picto == dItemNo_PICTO_BOX_e) {
                m1658[i_slot].pane->show();
                m1AF0[i_slot].pane->show();
                m1540.pane->show();
            } else if (picto == dItemNo_DELUXE_PICTO_BOX_e) {
                m1658[i_slot].pane->show();
                m1AF0[i_slot].pane->show();
                m1540.pane->show();
            } else {
                m1658[i_slot].pane->hide();
                m1AF0[i_slot].pane->hide();
                m1540.pane->hide();
            }
        }

        mItemSlot[i_slot] = dComIfGs_getItem(i_slot);
    } else {
        m1658[i_slot].pane->hide();
        m1AF0[i_slot].pane->hide();

        if (i_slot == 8) {
            m1540.pane->hide();
        } else if (i_slot == 0xC) {
            m1578.pane->hide();
            m15B0.pane->hide();
        } else if (i_slot == 0xD) {
            m15E8.pane->hide();
            m1620.pane->hide();
        }
    }
}

/* 801CDA14-801CDB14       .text itemBitCheck__12dMenu_Item_cFb */
void dMenu_Item_c::itemBitCheck(bool force) {
    for (int i = 0; i < 21; i++) {
        u8 itemNo = dComIfGs_getItem(i);
        if (mItemSlot[i] != itemNo || force) {
            itemCheck(i);
        }
    }
}

/* 801CDB14-801CDC34       .text arrowLightAnime__12dMenu_Item_cFv */
void dMenu_Item_c::arrowLightAnime() {
    m1F88[0].mUserArea++;
    if (m1F88[0].mUserArea >= 0x78) {
        m1F88[0].mUserArea = 0;
    }

    f32 t;
    if (m1F88[0].mUserArea < 0x3C) {
        t = fopMsgM_valueIncrease(0x3C, m1F88[0].mUserArea, 0);
    } else {
        t = fopMsgM_valueIncrease(0x3C, 0x78 - m1F88[0].mUserArea, 0);
    }

    f32 scale = 1.0f - 0.39999998f * t;
    f32 alpha = m1F88[0].mInitAlpha - (m1F88[0].mInitAlpha - 50.0f) * t;

    for (int i = 0; i < 3; i++) {
        fopMsgM_paneScaleXY(&m1F88[i], scale);
        m1F88[i].mNowAlpha = alpha;
    }
}

/* 801CDC34-801CDCF0       .text bottleFwaterCheck__12dMenu_Item_cFv */
u8 dMenu_Item_c::bottleFwaterCheck() {
    for (int i = 0; i < 4; i++) {
        int slot = i + 0xE;
        if (dComIfGs_getItem(slot) == dItemNo_FOREST_WATER_e) {
            return slot;
        }
    }

    return 0;
}

/* 801CDCF0-801CDDC0       .text recollectBossCheck__12dMenu_Item_cFv */
u8 dMenu_Item_c::recollectBossCheck() {
    if (dStage_stagInfo_GetSTType(dComIfGp_getStage().getStagInfo()) == dStageType_BOSS_e) {
        if (strcmp(dComIfGp_getStartStageName(), "Xboss0") == 0 ||
            strcmp(dComIfGp_getStartStageName(), "Xboss1") == 0 ||
            strcmp(dComIfGp_getStartStageName(), "Xboss2") == 0 ||
            strcmp(dComIfGp_getStartStageName(), "Xboss3") == 0)
        {
            return TRUE;
        }
    }

    return FALSE;
}

/* 801CDDC0-801CF08C       .text cornerMove__12dMenu_Item_cFv */
void dMenu_Item_c::cornerMove() {
    int r4 = 0xF0;
    J2DWindow::TContentsColor outColor;
    JUtility::TColor sp1C;

    m23FA++;

    if (m23FA >= r4) {
        m23FA = 0;
    }

    int r4_2 = m23FA % 60;
    f32 t = fopMsgM_valueIncrease(60, r4_2, 2);

    if (m23FA < 60) {
        outColor.mTL.r = m2320.mTL.r + (m2320.mBL.r - m2320.mTL.r) * t;
        outColor.mTL.g = m2320.mTL.g + (m2320.mBL.g - m2320.mTL.g) * t;
        outColor.mTL.b = m2320.mTL.b + (m2320.mBL.b - m2320.mTL.b) * t;
        outColor.mTL.a = m2320.mTL.a + (m2320.mBL.a - m2320.mTL.a) * t;
        outColor.mTR.r = m2320.mTR.r + (m2320.mTL.r - m2320.mTR.r) * t;
        outColor.mTR.g = m2320.mTR.g + (m2320.mTL.g - m2320.mTR.g) * t;
        outColor.mTR.b = m2320.mTR.b + (m2320.mTL.b - m2320.mTR.b) * t;
        outColor.mTR.a = m2320.mTR.a + (m2320.mTL.a - m2320.mTR.a) * t;
        outColor.mBL.r = m2320.mBL.r + (m2320.mBR.r - m2320.mBL.r) * t;
        outColor.mBL.g = m2320.mBL.g + (m2320.mBR.g - m2320.mBL.g) * t;
        outColor.mBL.b = m2320.mBL.b + (m2320.mBR.b - m2320.mBL.b) * t;
        outColor.mBL.a = m2320.mBL.a + (m2320.mBR.a - m2320.mBL.a) * t;
        outColor.mBR.r = m2320.mBR.r + (m2320.mTR.r - m2320.mBR.r) * t;
        outColor.mBR.g = m2320.mBR.g + (m2320.mTR.g - m2320.mBR.g) * t;
        outColor.mBR.b = m2320.mBR.b + (m2320.mTR.b - m2320.mBR.b) * t;
        outColor.mBR.a = m2320.mBR.a + (m2320.mTR.a - m2320.mBR.a) * t;
    } else if (m23FA < 120) {
        outColor.mTR.r = m2320.mTL.r + (m2320.mBL.r - m2320.mTL.r) * t;
        outColor.mTR.g = m2320.mTL.g + (m2320.mBL.g - m2320.mTL.g) * t;
        outColor.mTR.b = m2320.mTL.b + (m2320.mBL.b - m2320.mTL.b) * t;
        outColor.mTR.a = m2320.mTL.a + (m2320.mBL.a - m2320.mTL.a) * t;
        outColor.mBR.r = m2320.mTR.r + (m2320.mTL.r - m2320.mTR.r) * t;
        outColor.mBR.g = m2320.mTR.g + (m2320.mTL.g - m2320.mTR.g) * t;
        outColor.mBR.b = m2320.mTR.b + (m2320.mTL.b - m2320.mTR.b) * t;
        outColor.mBR.a = m2320.mTR.a + (m2320.mTL.a - m2320.mTR.a) * t;
        outColor.mTL.r = m2320.mBL.r + (m2320.mBR.r - m2320.mBL.r) * t;
        outColor.mTL.g = m2320.mBL.g + (m2320.mBR.g - m2320.mBL.g) * t;
        outColor.mTL.b = m2320.mBL.b + (m2320.mBR.b - m2320.mBL.b) * t;
        outColor.mTL.a = m2320.mBL.a + (m2320.mBR.a - m2320.mBL.a) * t;
        outColor.mBL.r = m2320.mBR.r + (m2320.mTR.r - m2320.mBR.r) * t;
        outColor.mBL.g = m2320.mBR.g + (m2320.mTR.g - m2320.mBR.g) * t;
        outColor.mBL.b = m2320.mBR.b + (m2320.mTR.b - m2320.mBR.b) * t;
        outColor.mBL.a = m2320.mBR.a + (m2320.mTR.a - m2320.mBR.a) * t;
    } else if (m23FA < 180) {
        outColor.mBR.r = m2320.mTL.r + (m2320.mBL.r - m2320.mTL.r) * t;
        outColor.mBR.g = m2320.mTL.g + (m2320.mBL.g - m2320.mTL.g) * t;
        outColor.mBR.b = m2320.mTL.b + (m2320.mBL.b - m2320.mTL.b) * t;
        outColor.mBR.a = m2320.mTL.a + (m2320.mBL.a - m2320.mTL.a) * t;
        outColor.mBL.r = m2320.mTR.r + (m2320.mTL.r - m2320.mTR.r) * t;
        outColor.mBL.g = m2320.mTR.g + (m2320.mTL.g - m2320.mTR.g) * t;
        outColor.mBL.b = m2320.mTR.b + (m2320.mTL.b - m2320.mTR.b) * t;
        outColor.mBL.a = m2320.mTR.a + (m2320.mTL.a - m2320.mTR.a) * t;
        outColor.mTR.r = m2320.mBL.r + (m2320.mBR.r - m2320.mBL.r) * t;
        outColor.mTR.g = m2320.mBL.g + (m2320.mBR.g - m2320.mBL.g) * t;
        outColor.mTR.b = m2320.mBL.b + (m2320.mBR.b - m2320.mBL.b) * t;
        outColor.mTR.a = m2320.mBL.a + (m2320.mBR.a - m2320.mBL.a) * t;
        outColor.mTL.r = m2320.mBR.r + (m2320.mTR.r - m2320.mBR.r) * t;
        outColor.mTL.g = m2320.mBR.g + (m2320.mTR.g - m2320.mBR.g) * t;
        outColor.mTL.b = m2320.mBR.b + (m2320.mTR.b - m2320.mBR.b) * t;
        outColor.mTL.a = m2320.mBR.a + (m2320.mTR.a - m2320.mBR.a) * t;
    } else {
        outColor.mBL.r = m2320.mTL.r + (m2320.mBL.r - m2320.mTL.r) * t;
        outColor.mBL.g = m2320.mTL.g + (m2320.mBL.g - m2320.mTL.g) * t;
        outColor.mBL.b = m2320.mTL.b + (m2320.mBL.b - m2320.mTL.b) * t;
        outColor.mBL.a = m2320.mTL.a + (m2320.mBL.a - m2320.mTL.a) * t;
        outColor.mTL.r = m2320.mTR.r + (m2320.mTL.r - m2320.mTR.r) * t;
        outColor.mTL.g = m2320.mTR.g + (m2320.mTL.g - m2320.mTR.g) * t;
        outColor.mTL.b = m2320.mTR.b + (m2320.mTL.b - m2320.mTR.b) * t;
        outColor.mTL.a = m2320.mTR.a + (m2320.mTL.a - m2320.mTR.a) * t;
        outColor.mBR.r = m2320.mBL.r + (m2320.mBR.r - m2320.mBL.r) * t;
        outColor.mBR.g = m2320.mBL.g + (m2320.mBR.g - m2320.mBL.g) * t;
        outColor.mBR.b = m2320.mBL.b + (m2320.mBR.b - m2320.mBL.b) * t;
        outColor.mBR.a = m2320.mBL.a + (m2320.mBR.a - m2320.mBL.a) * t;
        outColor.mTR.r = m2320.mBR.r + (m2320.mTR.r - m2320.mBR.r) * t;
        outColor.mTR.g = m2320.mBR.g + (m2320.mTR.g - m2320.mBR.g) * t;
        outColor.mTR.b = m2320.mBR.b + (m2320.mTR.b - m2320.mBR.b) * t;
        outColor.mTR.a = m2320.mBR.a + (m2320.mTR.a - m2320.mBR.a) * t;
    }

    ((J2DWindow*)m14D0.pane)->setContentsColor(outColor);

    m23FC++;

    if (m23FC >= 0x28) {
        m23FC = 0;
    }

    f32 pulse;
    if (m23FC < 0x14) {
        pulse = fopMsgM_valueIncrease(0x14, m23FC, 0);
    } else {
        pulse = fopMsgM_valueIncrease(0x14, 0x28 - m23FC, 0);
    }

    sp1C.r = 0xFF;
    sp1C.g = 128.0f - (-42.0f * pulse);
    sp1C.b = 0;
    sp1C.a = 0xFF;
    ((J2DWindow*)m14D0.pane)->setWhite(sp1C);
}

/* 801CF08C-801CF12C       .text equipBeastItem__12dMenu_Item_cFi */
u8 dMenu_Item_c::equipBeastItem(int i_idx) {
    u8 itemNo = dComIfGs_getItemBeast(i_idx);
    int ret = 0;

    switch (itemNo) {
    case dItemNo_SKULL_NECKLACE_e:
        ret = dBeastIdx_SKULL_NECKLACE_e;
        break;
    case dItemNo_BOKOBABA_SEED_e:
        ret = dBeastIdx_BOKOBABA_SEED_e;
        break;
    case dItemNo_GOLDEN_FEATHER_e:
        ret = dBeastIdx_GOLDEN_FEATHER_e;
        break;
    case dItemNo_KNIGHTS_CREST_e:
        ret = dBeastIdx_KNIGHTS_CREST_e;
        break;
    case dItemNo_RED_JELLY_e:
        ret = dBeastIdx_RED_JELLY_e;
        break;
    case dItemNo_GREEN_JELLY_e:
        ret = dBeastIdx_GREEN_JELLY_e;
        break;
    case dItemNo_BLUE_JELLY_e:
        ret = dBeastIdx_BLUE_JELLY_e;
        break;
    case dItemNo_JOY_PENDANT_e:
        ret = dBeastIdx_JOY_PENDANT_e;
        break;
    }

    return ret;
}

/* 801CF12C-801CF510       .text _create__12dMenu_Item_cFv */
void dMenu_Item_c::_create() {
    scrn = new J2DScreen();
    JUT_ASSERT(0xa57, scrn != 0);
    scrn->set("menu_item_02.blo", mpArc);

    stick = new STControl(5, 2, 3, 2);
    JUT_ASSERT(0xa5b, stick != 0);

    stick->setWaitParm(5, 2, 3, 2, 0.9f, 0.5f, 0, 0x800);

    outFont = new dDlst_2DOutFont_c();
    JUT_ASSERT(0xa5f, outFont != 0);

    outFont->m74 = 1;

    dMs_c = new dMenu_save_c();
    JUT_ASSERT(0xa63, dMs_c != 0);

    dMs_c->setUseType(0);
    dMs_c->_create();

    mItemMode = 0;
    m23B8[0] = NULL;
    m23B8[1] = NULL;

    screenSet();
    initialize();

    g_miHIO.mNo = mDoHIO_createChild("アイテム画面", &g_miHIO); // "Item Screen"

    for (int i = 0; i < 4; i++) {
        ((J2DPicture*)mA18[i].pane)->append("cursor_00_02.bti", 1.0f);

        m23C0[i] = mA18[i].mPosCenterOrig.x - m1658[0].mPosCenterOrig.x;
        m23D0[i] = mA18[i].mPosCenterOrig.y - m1658[0].mPosCenterOrig.y;
    }

    for (int i = 0; i < 15; i++) {
        ((J2DPicture*)m0B0[i].pane)->changeTexture("font_07_02.bti", 0);
        fopMsgM_blendInit(&m0B0[i], "font_00.bti");
    }

    m2400 = 0;
    m2401 = 0;
    m2402 = 0;
    m2420 = 0;
    m241F = 0;
    m241E = 0;
    m2404 = 3;
    m2403 = 3;
    m2405 = 3;

    for (int i = 0; i < 21; i++) {
        itemCheck(i);
    }

    cursorAnime();
}

/* 801CF510-801CF618       .text _delete__12dMenu_Item_cFv */
void dMenu_Item_c::_delete() {
    for (int i = 0; i < 2; i++) {
        if (m23B8[i] != NULL) {
            m23B8[i]->becomeInvalidEmitter();
            m23B8[i]->quitImmortalEmitter();
            m23B8[i] = NULL;
        }
    }

    delete scrn;
    delete stick;

    if (outFont != NULL) {
        delete outFont;
    }

    dMs_c->_delete();
    delete dMs_c;

    mpArc->removeResourceAll();
    mDoHIO_deleteChild(g_miHIO.mNo);
}

/* 801CF618-801D0524       .text _move__12dMenu_Item_cFv */
void dMenu_Item_c::_move() {
    u8 prevItem = mNowItem;

    itemBitCheck(false);

    if (mItemMode == 0) {
        if (!noteCheck()) {
            if (!CPad_CHECK_TRIG_START(0) && !mDoCPd_R_LOCK_BUTTON(0) && !mDoCPd_L_LOCK_BUTTON(0)) {
                if (CPad_CHECK_TRIG_A(0)) {
                    if (dMeter_subWinFlag() && mNowItem == 0xFF) {
                        subWindowDelete();
                        mDoAud_seStart(JA_SE_ITM_MENU_CANCEL);
                    } else if (mNowItem == 0x15) {
                        mItemMode = 1;
                        dMs_c->initialize();
                        mDoAud_seStart(JA_SE_ITM_MENU_OPT_IN);
                    } else if (dComIfGs_getItem(mNowItem) != dItemNo_NONE_e) {
                        if (!(recollectBossCheck() && (
                            dComIfGs_getItem(mNowItem) == dItemNo_WATER_BOTTLE_e ||
                            dComIfGs_getItem(mNowItem) == dItemNo_FIREFLY_BOTTLE_e ||
                            dComIfGs_getItem(mNowItem) == dItemNo_FOREST_WATER_e)))
                        {
                            fopMsgM_setInitAlpha(&m740);
                            fopMsgM_setInitAlpha(&m778);
                            fopMsgM_setInitAlpha(&m7B0);
                            fopMsgM_setInitAlpha(&m7E8);
                            fopMsgM_setInitAlpha(&m820);
                            m820.mUserArea = 1;
                            m7E8.mUserArea = 1;
                            itemnoteSet();
                            mDoAud_seStart(JA_SE_ITEM_EXP_OPEN);
                        }
                    }
                } else if (CPad_CHECK_TRIG_B(0)) {
                    if (dMeter_subWinFlag()) {
                        subWindowDelete();
                        mDoAud_seStart(JA_SE_ITM_MENU_CANCEL);
                    }
                } else if (CPad_CHECK_TRIG_X(0) || CPad_CHECK_TRIG_Y(0) || CPad_CHECK_TRIG_Z(0)) {
                    if (dMeter_subWinFlag() && mNowItem == 0xFF) {
                        subWindowDelete();
                        mDoAud_seStart(JA_SE_ITM_MENU_CANCEL);
                    } else if (mNowItem != 0x15 && dComIfGs_getItem(mNowItem) != dItemNo_NONE_e) {
                        if (dMeter_subWinFlag()) {
                            if (mNowItem == 0xFF) {
                                subWindowDelete();
                                mDoAud_seStart(JA_SE_ITM_MENU_CANCEL);
                            } else {
                                subItemDecide();
                            }
                        } else if (!(recollectBossCheck() && (
                            dComIfGs_getItem(mNowItem) == dItemNo_WATER_BOTTLE_e ||
                            dComIfGs_getItem(mNowItem) == dItemNo_FIREFLY_BOTTLE_e ||
                            dComIfGs_getItem(mNowItem) == dItemNo_FOREST_WATER_e)))
                        {
                            itemDecide();
                        }
                    }
                } else {
                    if (dMeter_subWinFlag()) {
                        cursorSubMove();
                    } else {
                        cursorMainMove();
                    }

                    itemScale();

                    if (mNowItem != prevItem && prevItem == 0xC) {
                        for (int i = 0; i < 3; i++) {
                            fopMsgM_paneTrans(&m1F88[i], 0.0f, 0.0f);
                        }
                    }
                }
            }
        } else {
            noteAppear();
        }

        if (m2404 != 3) {
            itemMove();
        }

        if (mNowItem == 0x15) {
            itemnameMove();
        } else if (recollectBossCheck() && (
            dComIfGs_getItem(mNowItem) == dItemNo_WATER_BOTTLE_e ||
            dComIfGs_getItem(mNowItem) == dItemNo_FIREFLY_BOTTLE_e ||
            dComIfGs_getItem(mNowItem) == dItemNo_FOREST_WATER_e))
        {
            fopMsgM_setNowAlphaZero(&m890[0]);
            fopMsgM_setNowAlphaZero(&m890[1]);
            fopMsgM_setNowAlphaZero(&m858);
        } else {
            itemnameMove();
        }

        outFontMove();
        cursorAnime();
        cornerMove();

        if (dComIfGs_getItem(0xC) == dItemNo_MAGIC_ARROW_e || dComIfGs_getItem(0xC) == dItemNo_LIGHT_ARROW_e) {
            arrowLightAnime();
        }

        checkMove();

        u8 bottleSlot = bottleFwaterCheck();
        if (bottleSlot != 0) {
            for (int i = 0; i < 2; i++) {
                if (m23B8[i] != NULL) {
                    f32 x = m1658[bottleSlot].mPosCenterOrig.x - 320.0f;
                    f32 y = m1658[bottleSlot].mPosCenterOrig.y - 240.0f;
                    m23B8[i]->setGlobalTranslation(x, y, 0.0f);
                    m23B8[i]->playDrawParticle();
                    m23B8[i]->setGlobalAlpha(0xFF);
                }
            }
        }
    } else if (mItemMode == 1) {
        switch (dMs_c->getSaveStatus()) {
        case 0:
            mItemMode = 0;
            break;
        case 1:
            dMs_c->_open();
            break;
        case 2:
            dMs_c->_move();
            break;
        case 3:
            dMs_c->_close();
            break;
        }

        if (bottleFwaterCheck() != 0) {
            for (int i = 0; i < 2; i++) {
                if (m23B8[i] != NULL) {
                    m23B8[i]->setGlobalAlpha(0);
                }
            }
        }

        dComIfGp_setAStatusForce(dActStts_RETURN_e);
    }

    if (mNowItem == 0x15) {
        dComIfGp_setDoStatusForce(dActStts_CHOOSE_e);
    } else if (dComIfGs_getItem(mNowItem) != dItemNo_NONE_e) {
        dComIfGp_setDoStatusForce(dActStts_INFO_e);
    } else {
        dComIfGp_setDoStatusForce(dActStts_BLANK_e);
        dComIfGp_setDoStatus(dActStts_BLANK_e);
    }
}

/* 801D0524-801D0F50       .text _draw__12dMenu_Item_cFv */
void dMenu_Item_c::_draw() {
    if (m2422 == 0) {
        fopMsgM_setAlpha(&m740);
        fopMsgM_setAlpha(&m778);
        fopMsgM_setAlpha(&m7B0);
        fopMsgM_setAlpha(&m7E8);
        fopMsgM_setAlpha(&m820);
        outFont->setAlpha(m858.mNowAlpha);
        fopMsgM_setAlpha(&m890[0]);
        fopMsgM_setAlpha(&m890[1]);
        fopMsgM_setAlpha(&m900);
        fopMsgM_setAlpha(&m938);
        fopMsgM_setAlpha(&m970);
        fopMsgM_setAlpha(&m9A8);
        fopMsgM_setAlpha(&m9E0);

        for (int i = 0; i < 4; i++) {
            fopMsgM_setAlpha(&mA18[i]);
        }

        for (int i = 0; i < 8; i++) {
            fopMsgM_setAlpha(&mAF8[i]);
            fopMsgM_setAlpha(&mCB8[i]);
            fopMsgM_setAlpha(&mE78[i]);
            fopMsgM_setAlpha(&m1070[i]);
        }

        fopMsgM_setAlpha(&m1038);
        fopMsgM_setAlpha(&m1230);

        for (int i = 0; i < 9; i++) {
            fopMsgM_setAlpha(&m1268[i]);
        }

        fopMsgM_setAlpha(&m1460);
        fopMsgM_setAlpha(&m1498);
        fopMsgM_setAlpha(&m14D0);
        fopMsgM_setAlpha(&m1508);
        fopMsgM_setAlpha(&m1540);
        fopMsgM_setAlpha(&m1578);
        fopMsgM_setAlpha(&m15B0);
        fopMsgM_setAlpha(&m15E8);
        fopMsgM_setAlpha(&m1620);

        for (int i = 0; i < 21; i++) {
            fopMsgM_setAlpha(&m1658[i]);
            fopMsgM_setAlpha(&m1AF0[i]);
        }

        for (int i = 0; i < 3; i++) {
            fopMsgM_setAlpha(&m1F88[i]);
            fopMsgM_setAlpha(&m2030[i]);
        }

        for (int i = 0; i < 6; i++) {
            fopMsgM_setAlpha(&m20D8[i]);
        }

        fopMsgM_setAlpha(&m2228);
        fopMsgM_setAlpha(&m2260);
        fopMsgM_setAlpha(&m2298);
        fopMsgM_setAlpha(&m22D0);
    } else {
        f32 alpha_scale = fopMsgM_valueIncrease(10, mTimer, 0);

        if (mTriggerInfo != 1 && mTriggerInfo != 2) {
            m740.pane->setAlpha(m740.mNowAlpha * alpha_scale);
            m778.pane->setAlpha(m778.mNowAlpha * alpha_scale);
            m7B0.pane->setAlpha(m7B0.mNowAlpha * alpha_scale);
            m7E8.pane->setAlpha(m7E8.mNowAlpha * alpha_scale);
            m820.pane->setAlpha(m820.mNowAlpha * alpha_scale);
            outFont->setAlpha(m858.mNowAlpha * alpha_scale);
            m890[0].pane->setAlpha(m890[0].mNowAlpha * alpha_scale);
            m890[1].pane->setAlpha(m890[1].mNowAlpha * alpha_scale);
            m900.pane->setAlpha(m900.mNowAlpha * alpha_scale);
            m938.pane->setAlpha(m938.mNowAlpha * alpha_scale);
            m9A8.pane->setAlpha(m9A8.mNowAlpha * alpha_scale);
            m9E0.pane->setAlpha(m9E0.mNowAlpha * alpha_scale);
        }

        m970.pane->setAlpha(m970.mNowAlpha * alpha_scale);

        for (int i = 0; i < 4; i++) {
            mA18[i].pane->setAlpha(mA18[i].mNowAlpha * alpha_scale);
        }

        for (int i = 0; i < 8; i++) {
            mAF8[i].pane->setAlpha(mAF8[i].mNowAlpha * alpha_scale);
            mCB8[i].pane->setAlpha(mCB8[i].mNowAlpha * alpha_scale);
            mE78[i].pane->setAlpha(mE78[i].mNowAlpha * alpha_scale);
            m1070[i].pane->setAlpha(m1070[i].mNowAlpha * alpha_scale);
        }

        m1038.pane->setAlpha(m1038.mNowAlpha * alpha_scale);
        m1230.pane->setAlpha(m1230.mNowAlpha * alpha_scale);

        for (int i = 0; i < 9; i++) {
            m1268[i].pane->setAlpha(m1268[i].mNowAlpha * alpha_scale);
        }

        m1460.pane->setAlpha(m1460.mNowAlpha * alpha_scale);
        m1498.pane->setAlpha(m1498.mNowAlpha * alpha_scale);
        m14D0.pane->setAlpha(m14D0.mNowAlpha * alpha_scale);
        m1508.pane->setAlpha(m1508.mNowAlpha * alpha_scale);
        m1540.pane->setAlpha(m1540.mNowAlpha * alpha_scale);
        m1578.pane->setAlpha(m1578.mNowAlpha * alpha_scale);
        m15B0.pane->setAlpha(m15B0.mNowAlpha * alpha_scale);
        m15E8.pane->setAlpha(m15E8.mNowAlpha * alpha_scale);
        m1620.pane->setAlpha(m1620.mNowAlpha * alpha_scale);

        for (int i = 0; i < 21; i++) {
            m1658[i].pane->setAlpha(m1658[i].mNowAlpha * alpha_scale);
            m1AF0[i].pane->setAlpha(m1AF0[i].mNowAlpha * alpha_scale);
        }

        for (int i = 0; i < 3; i++) {
            m1F88[i].pane->setAlpha(m1F88[i].mNowAlpha * alpha_scale);
            m2030[i].pane->setAlpha(m2030[i].mNowAlpha * alpha_scale);
        }

        for (int i = 0; i < 6; i++) {
            m20D8[i].pane->setAlpha(m20D8[i].mNowAlpha * alpha_scale);
        }

        m2228.pane->setAlpha(m2228.mNowAlpha * alpha_scale);
        m2260.pane->setAlpha(m2260.mNowAlpha * alpha_scale);
        m2298.pane->setAlpha(m2298.mNowAlpha * alpha_scale);
        m22D0.pane->setAlpha(m22D0.mNowAlpha * alpha_scale);
    }

    outFontDraw();

    J2DOrthoGraph* graph = dComIfGp_getCurrentGrafPort();
    graph->setPort();
    scrn->draw(0.0f, 0.0f, graph);
    dMs_c->_draw();
}

/* 801D0F50-801D1438       .text _open__12dMenu_Item_cFv */
bool dMenu_Item_c::_open() {
    s16 main_off = g_miHIO.field_0x26;
    bool ret = false;

    if (mTimer == 0) {
        for (int i = 0; i < 2; i++) {
            strcpy(name[i], "");
            strcpy(note[i], "");
            ((J2DTextBox*)m890[i].pane)->setString(name[i]);
        }

        ((J2DTextBox*)m778.pane)->setString(note[0]);
        ((J2DTextBox*)m740.pane)->setString(note[1]);

        itemnameSet();

        if (mNowItem == 0x15 || (recollectBossCheck() && (
            dComIfGs_getItem(mNowItem) == dItemNo_WATER_BOTTLE_e ||
            dComIfGs_getItem(mNowItem) == dItemNo_FIREFLY_BOTTLE_e ||
            dComIfGs_getItem(mNowItem) == dItemNo_FOREST_WATER_e)))
        {
            dComIfGp_setDoStatusForce(dActStts_CHOOSE_e);
        } else {
            itemnoteSet();

            if (dComIfGs_getItem(mNowItem) != dItemNo_NONE_e) {
                dComIfGp_setDoStatusForce(dActStts_INFO_e);
            } else {
                dComIfGp_setDoStatusForce(dActStts_BLANK_e);
                dComIfGp_setDoStatus(dActStts_BLANK_e);
            }
        }
    }

    mTimer++;

    if (mTimer <= 10 && mTimer > 0) {
        if (mTriggerInfo == 2) {
            mainOpenProc(mTimer, 10, main_off);
        } else {
            mainOpenProc(mTimer, 10, -main_off);
        }

        titleOpenProc(mTimer, 10);
        noteOpenProc(mTimer, 10);
        nameOpenProc(mTimer, 10);
    }

    if (mTimer >= 10) {
        ret = true;
        mDoAud_seStart(JA_SE_ITM_MENU_ITEMS_IN);
    }

    return ret;
}

/* 801D1438-801D1CD4       .text _close__12dMenu_Item_cFv */
bool dMenu_Item_c::_close() {
    bool ret = false;

    mTimer--;

    f32 main = g_miHIO.field_0x26 * fopMsgM_valueIncrease(10, 10 - mTimer, 0);
    f32 title = g_miHIO.field_0x28 * fopMsgM_valueIncrease(10, 10 - mTimer, 0);
    f32 name = g_miHIO.field_0x2C * fopMsgM_valueIncrease(10, 10 - mTimer, 0);
    f32 note_t = fopMsgM_valueIncrease(10, 10 - mTimer, 0);
    u8 alpha = 255.0f * fopMsgM_valueIncrease(10, mTimer, 0);

    for (int i = 0; i < 2; i++) {
        if (m23B8[i] != NULL) {
            m23B8[i]->setGlobalAlpha(alpha);
        }
    }

    if (mTriggerInfo == 2) {
        mainTrans(-main, 0.0f);
        titleTrans(0.0f, title);
        noteRotate(g_miHIO.field_0x3E * note_t, m820.mUserArea + note_t * (g_miHIO.field_0x2A - m820.mUserArea));
        nameTrans(0.0f, name);
    } else if (mTriggerInfo == 1) {
        mainTrans(main, 0.0f);
        titleTrans(0.0f, title);
        noteRotate(g_miHIO.field_0x3E * note_t, m820.mUserArea + note_t * (g_miHIO.field_0x2A - m820.mUserArea));
        nameTrans(0.0f, name);
    }

    if (mTimer > 0) {
        m2422 = 1;
    } else {
        ret = true;
        m2422 = 0;

        for (int i = 0; i < 15; i++) {
            fopMsgM_setNowAlphaZero(&m0B0[i]);
        }

        fopMsgM_setNowAlphaZero(&m740);
        fopMsgM_setNowAlphaZero(&m778);
        fopMsgM_setNowAlphaZero(&m7B0);
        fopMsgM_setNowAlphaZero(&m7E8);
        fopMsgM_setNowAlphaZero(&m820);
        fopMsgM_setNowAlphaZero(&m858);
        fopMsgM_setNowAlphaZero(&m890[0]);
        fopMsgM_setNowAlphaZero(&m890[1]);
        fopMsgM_setNowAlphaZero(&m900);
        fopMsgM_setNowAlphaZero(&m938);
        fopMsgM_setNowAlphaZero(&m970);
        fopMsgM_setNowAlphaZero(&m9A8);
        fopMsgM_setNowAlphaZero(&m9E0);

        for (int i = 0; i < 4; i++) {
            fopMsgM_setNowAlphaZero(&mA18[i]);
        }

        for (int i = 0; i < 8; i++) {
            fopMsgM_setNowAlphaZero(&mAF8[i]);
            fopMsgM_setNowAlphaZero(&mCB8[i]);
            fopMsgM_setNowAlphaZero(&mE78[i]);
            fopMsgM_setNowAlphaZero(&m1070[i]);
        }

        fopMsgM_setNowAlphaZero(&m1038);
        fopMsgM_setNowAlphaZero(&m1230);

        for (int i = 0; i < 9; i++) {
            fopMsgM_setNowAlphaZero(&m1268[i]);
        }

        fopMsgM_setNowAlphaZero(&m1460);
        fopMsgM_setNowAlphaZero(&m1498);
        fopMsgM_setNowAlphaZero(&m14D0);
        fopMsgM_setNowAlphaZero(&m1508);
        fopMsgM_setNowAlphaZero(&m1540);
        fopMsgM_setNowAlphaZero(&m1578);
        fopMsgM_setNowAlphaZero(&m15B0);
        fopMsgM_setNowAlphaZero(&m15E8);
        fopMsgM_setNowAlphaZero(&m1620);

        for (int i = 0; i < 21; i++) {
            fopMsgM_setNowAlphaZero(&m1658[i]);
            fopMsgM_setNowAlphaZero(&m1AF0[i]);
        }

        for (int i = 0; i < 3; i++) {
            fopMsgM_setNowAlphaZero(&m2030[i]);
        }

        for (int i = 0; i < 6; i++) {
            fopMsgM_setNowAlphaZero(&m20D8[i]);
        }

        fopMsgM_setNowAlphaZero(&m2228);
        fopMsgM_setNowAlphaZero(&m2260);
        fopMsgM_setNowAlphaZero(&m2298);
        fopMsgM_setNowAlphaZero(&m22D0);

        if (m2404 != 3) {
            dComIfGs_setSelectItem(m2404, m2401);
            dComIfGp_setSelectItem(m2404);
            m2404 = 3;

            if (m2403 != 3) {
                dComIfGs_setSelectItem(m2403, m2402);
                dComIfGp_setSelectItem(m2403);
                m2403 = 3;
            }

            mDoAud_seStart(JA_SE_ITM_MENU_SET);
        }

        if (dMeter_subWinFlag()) {
            subWindowDelete();
        }
    }

    return ret;
}

/* 801D1CD4-801D21A0       .text _open2__12dMenu_Item_cFv */
bool dMenu_Item_c::_open2() {
    s16 main_off = g_miHIO.field_0x26;
    s16 frames = g_menuHIO.field_0x92;
    bool ret = false;

    if (mTimer == 0) {
        for (int i = 0; i < 2; i++) {
            strcpy(name[i], "");
            strcpy(note[i], "");
            ((J2DTextBox*)m890[i].pane)->setString(name[i]);
        }

        ((J2DTextBox*)m778.pane)->setString(note[0]);
        ((J2DTextBox*)m740.pane)->setString(note[1]);

        itemnameSet();

        if (mNowItem == 0x15 || (recollectBossCheck() && (
            dComIfGs_getItem(mNowItem) == dItemNo_WATER_BOTTLE_e ||
            dComIfGs_getItem(mNowItem) == dItemNo_FIREFLY_BOTTLE_e ||
            dComIfGs_getItem(mNowItem) == dItemNo_FOREST_WATER_e)))
        {
            dComIfGp_setDoStatusForce(dActStts_CHOOSE_e);
        } else {
            itemnoteSet();

            if (dComIfGs_getItem(mNowItem) != dItemNo_NONE_e) {
                dComIfGp_setDoStatusForce(dActStts_INFO_e);
            } else {
                dComIfGp_setDoStatusForce(dActStts_BLANK_e);
                dComIfGp_setDoStatus(dActStts_BLANK_e);
            }
        }
    }

    mTimer++;

    if (mTimer <= frames && mTimer > 0) {
        if (mTriggerInfo == 2) {
            mainOpenProc(mTimer, frames, main_off);
        } else {
            mainOpenProc(mTimer, frames, -main_off);
        }

        titleOpenProc(mTimer, frames);
        noteOpenProc(mTimer, frames);
        nameOpenProc(mTimer, frames);
    }

    if (mTimer >= frames) {
        ret = true;
    }

    return ret;
}

/* 801D21A0-801D2A4C       .text _close2__12dMenu_Item_cFv */
bool dMenu_Item_c::_close2() {
    bool ret = false;

    mTimer--;

    s16 frames = g_menuHIO.field_0x92;
    f32 main = g_miHIO.field_0x26 * fopMsgM_valueIncrease(frames, frames - mTimer, 0);
    f32 title = g_miHIO.field_0x28 * fopMsgM_valueIncrease(frames, frames - mTimer, 0);
    f32 name = g_miHIO.field_0x2C * fopMsgM_valueIncrease(frames, frames - mTimer, 0);
    f32 note_t = fopMsgM_valueIncrease(frames, frames - mTimer, 0);
    u8 alpha = 255.0f * fopMsgM_valueIncrease(frames, mTimer, 0);

    for (int i = 0; i < 2; i++) {
        if (m23B8[i] != NULL) {
            m23B8[i]->setGlobalAlpha(alpha);
        }
    }

    if (mTriggerInfo == 2) {
        mainTrans(-main, 0.0f);
        titleTrans(0.0f, title);
        noteRotate(g_miHIO.field_0x3E * note_t, m820.mUserArea + note_t * (g_miHIO.field_0x2A - m820.mUserArea));
        nameTrans(0.0f, name);
    } else if (mTriggerInfo == 1) {
        mainTrans(main, 0.0f);
        titleTrans(0.0f, title);
        noteRotate(g_miHIO.field_0x3E * note_t, m820.mUserArea + note_t * (g_miHIO.field_0x2A - m820.mUserArea));
        nameTrans(0.0f, name);
    }

    if (mTimer > 0) {
        m2422 = 1;
    } else {
        ret = true;
        m2422 = 0;

        for (int i = 0; i < 15; i++) {
            fopMsgM_setNowAlphaZero(&m0B0[i]);
        }

        fopMsgM_setNowAlphaZero(&m740);
        fopMsgM_setNowAlphaZero(&m778);
        fopMsgM_setNowAlphaZero(&m7B0);
        fopMsgM_setNowAlphaZero(&m7E8);
        fopMsgM_setNowAlphaZero(&m820);
        fopMsgM_setNowAlphaZero(&m858);
        fopMsgM_setNowAlphaZero(&m890[0]);
        fopMsgM_setNowAlphaZero(&m890[1]);
        fopMsgM_setNowAlphaZero(&m900);
        fopMsgM_setNowAlphaZero(&m938);
        fopMsgM_setNowAlphaZero(&m970);
        fopMsgM_setNowAlphaZero(&m9A8);
        fopMsgM_setNowAlphaZero(&m9E0);

        for (int i = 0; i < 4; i++) {
            fopMsgM_setNowAlphaZero(&mA18[i]);
        }

        for (int i = 0; i < 8; i++) {
            fopMsgM_setNowAlphaZero(&mAF8[i]);
            fopMsgM_setNowAlphaZero(&mCB8[i]);
            fopMsgM_setNowAlphaZero(&mE78[i]);
            fopMsgM_setNowAlphaZero(&m1070[i]);
        }

        fopMsgM_setNowAlphaZero(&m1038);
        fopMsgM_setNowAlphaZero(&m1230);

        for (int i = 0; i < 9; i++) {
            fopMsgM_setNowAlphaZero(&m1268[i]);
        }

        fopMsgM_setNowAlphaZero(&m1460);
        fopMsgM_setNowAlphaZero(&m1498);
        fopMsgM_setNowAlphaZero(&m14D0);
        fopMsgM_setNowAlphaZero(&m1508);
        fopMsgM_setNowAlphaZero(&m1540);
        fopMsgM_setNowAlphaZero(&m1578);
        fopMsgM_setNowAlphaZero(&m15B0);
        fopMsgM_setNowAlphaZero(&m15E8);
        fopMsgM_setNowAlphaZero(&m1620);

        for (int i = 0; i < 21; i++) {
            fopMsgM_setNowAlphaZero(&m1658[i]);
            fopMsgM_setNowAlphaZero(&m1AF0[i]);
        }

        for (int i = 0; i < 3; i++) {
            fopMsgM_setNowAlphaZero(&m1F88[i]);
            fopMsgM_setNowAlphaZero(&m2030[i]);
        }

        for (int i = 0; i < 6; i++) {
            fopMsgM_setNowAlphaZero(&m20D8[i]);
        }

        fopMsgM_setNowAlphaZero(&m2228);
        fopMsgM_setNowAlphaZero(&m2260);
        fopMsgM_setNowAlphaZero(&m2298);
        fopMsgM_setNowAlphaZero(&m22D0);

        if (m2404 != 3) {
            dComIfGs_setSelectItem(m2404, m2401);
            dComIfGp_setSelectItem(m2404);
            m2404 = 3;

            if (m2403 != 3) {
                dComIfGs_setSelectItem(m2403, m2402);
                dComIfGp_setSelectItem(m2403);
                m2403 = 3;
            }

            mDoAud_seStart(JA_SE_ITM_MENU_SET);
        }

        if (dMeter_subWinFlag()) {
            subWindowDelete();
        }
    }

    return ret;
}
