//
// Generated by dtk
// Translation Unit: d_a_npc_auction.cpp
//

#include "d/dolzel_rel.h" // IWYU pragma: keep
#include "d/actor/d_a_npc_auction.h"
#include "d/actor/d_a_auction.h"
#include "d/d_com_inf_game.h"
#include "d/d_com_lib_game.h"
#include "d/d_item_data.h"
#include "d/d_particle_name.h"
#include "d/d_snap.h"
#include "JSystem/JParticle/JPAParticle.h"
#include "f_op/f_op_actor_mng.h"
#include "m_Do/m_Do_audio.h"
#include "m_Do/m_Do_ext.h"
#include "m_Do/m_Do_mtx.h"
#include "SSystem/SComponent/c_lib.h"
#include "SSystem/SComponent/c_math.h"
#include "JSystem/J3DGraphAnimator/J3DNode.h"
#include "JSystem/J3DGraphAnimator/J3DModel.h"
#include "JSystem/JUtility/JUTAssert.h"
#include "res/Object/Auc.h"
#include "res/Object/Rs2.h"

class daNpc_Auction2_HIO_c : public dNpc_HIO_c {
public:
    daNpc_Auction2_HIO_c(f32 p04, s16 maxHX, s16 maxBX, s16 maxHY, s16 maxBY, s16 minHX, s16 minBX,
                         s16 minHY, s16 minBY, s16 turn, s16 vel, f32 attnY, s16 attnAng, u8 unk22,
                         f32 dist, f32 e1, f32 e2, f32 e3) {
        m04 = p04;
        mMaxHeadX = maxHX;
        mMaxBackboneX = maxBX;
        mMaxHeadY = maxHY;
        mMaxBackboneY = maxBY;
        mMinHeadX = minHX;
        mMinBackboneX = minBX;
        mMinHeadY = minHY;
        mMinBackboneY = minBY;
        mMaxTurnStep = turn;
        mMaxHeadTurnVel = vel;
        mAttnYOffset = attnY;
        mMaxAttnAngleY = attnAng;
        m22 = unk22;
        mMaxAttnDistXZ = dist;
        field_0x28 = e1;
        field_0x2C = e2;
        field_0x30 = e3;
    }
    ~daNpc_Auction2_HIO_c() {}
    /* 0x28 */ f32 field_0x28;
    /* 0x2C */ f32 field_0x2C;
    /* 0x30 */ f32 field_0x30;
}; // Size: 0x34

const char daNpcAuction_c::m_arcname[] = "Auc";

static const char* l_arcname_tbl[] = {
    "Auc", "Auc", "Auc", "Auc", "Auc", "Auc", "Auc", "Auc", "Auc", "Auc", "Rs2", "Rs2",
};

static const int l_bmd_ix_tbl[] = {
    dRes_ID_AUC_BDL_UM_e,
    dRes_ID_AUC_BDL_UW_e,
    dRes_ID_AUC_BDL_UO_e,
    dRes_ID_AUC_BDL_UO_e,
    dRes_ID_AUC_BDL_UO_e,
    dRes_ID_AUC_BDL_UB_e,
    dRes_ID_AUC_BDL_UB_e,
    dRes_ID_AUC_BDL_UB_e,
    dRes_ID_AUC_BDL_UB_e,
    dRes_ID_AUC_BDL_SA_e,
    dRes_ID_RS2_BDL_RS_e,
    dRes_ID_RS2_BDL_RS_e,
};

static const int l_head_bmd_ix_tbl[] = {
    dRes_ID_AUC_BDL_UM01_HEAD_e,
    dRes_ID_AUC_BDL_UW02_HEAD_e,
    dRes_ID_AUC_BDL_UO01_HEAD_e,
    dRes_ID_AUC_BDL_UO02_HEAD_e,
    dRes_ID_AUC_BDL_UO03_HEAD_e,
    dRes_ID_AUC_BDL_UB01_HEAD_e,
    dRes_ID_AUC_BDL_UB02_HEAD_e,
    dRes_ID_AUC_BDL_UB03_HEAD_e,
    dRes_ID_AUC_BDL_UB04_HEAD_e,
    dRes_ID_AUC_BDL_SA02_HEAD_e,
    -1,
    -1,
};

static const char l_photo_no[] = {'d', 'g', 'h', 'i', 'j', 'k', 'k', 'l', 'm', 'n', '_', '_'};

static const int l_bck_ix_tbl[12][10] = {
    {0x42, 0x41, 0x3D, 0x3A, 0x3C, 0x3B, 0x42, 0x42, 0x46, 0x42},
    {0x2C, 0x2B, 0x0F, 0x0C, 0x0E, 0x0D, 0x2C, 0x2C, 0x48, 0x47},
    {0x0B, 0x0A, 0x09, 0x06, 0x08, 0x07, 0x0B, 0x0B, 0x0A, 0x0B},
    {0x0B, 0x0A, 0x09, 0x06, 0x08, 0x07, 0x0B, 0x0B, 0x0A, 0x0B},
    {0x0B, 0x0A, 0x09, 0x06, 0x08, 0x07, 0x0B, 0x0B, 0x0A, 0x0B},
    {0x05, 0x04, 0x03, 0x00, 0x02, 0x01, 0x05, 0x05, 0x04, 0x45},
    {0x05, 0x04, 0x03, 0x00, 0x02, 0x01, 0x05, 0x05, 0x04, 0x45},
    {0x05, 0x04, 0x03, 0x00, 0x02, 0x01, 0x05, 0x05, 0x04, 0x45},
    {0x05, 0x04, 0x03, 0x00, 0x02, 0x01, 0x05, 0x05, 0x04, 0x45},
    {0x2E, 0x49, 0x39, 0x36, 0x38, 0x37, 0x2E, 0x2E, 0x49, 0x2E},
    {0x07, 0x03, 0x04, 0x05, 0x02, 0x06, 0x00, 0x07, 0x07, 0x00},
    {0x08, 0x03, 0x04, 0x05, 0x02, 0x06, 0x00, 0x08, 0x08, 0x00},
};

static const int l_btp_ix_tbl[] = {
    dRes_ID_AUC_BTP_UM01_MABA_e,
    dRes_ID_AUC_BTP_UW02_MABA_e,
    dRes_ID_AUC_BTP_UO01_MABA_e,
    dRes_ID_AUC_BTP_UO02_MABA_e,
    dRes_ID_AUC_BTP_UO03_MABA_e,
    dRes_ID_AUC_BTP_UB01_MABA_e,
    dRes_ID_AUC_BTP_UB02_MABA_e,
    dRes_ID_AUC_BTP_UB03_MABA_e,
    dRes_ID_AUC_BTP_UB04_MABA_e,
    dRes_ID_AUC_BTP_SA02_MABA_e,
    dRes_ID_RS2_BTP_RS_MABA01_e,
    dRes_ID_RS2_BTP_RS_MABA01_e,
};

static const int l_bmt_ix_tbl[] = {
    -1,
    dRes_ID_AUC_BMT_UW02_e,
    -1,
    dRes_ID_AUC_BMT_UO02_e,
    dRes_ID_AUC_BMT_UO03_e,
    -1,
    dRes_ID_AUC_BMT_UB02_e,
    dRes_ID_AUC_BMT_UB03_e,
    dRes_ID_AUC_BMT_UB04_e,
    dRes_ID_AUC_BMT_SA02_e,
    -1,
    -1,
};

static const u32 l_diff_flag_tbl[] = {
    0x11000002, 0x15021222, 0x11000002, 0x15021222,
    0x15021222, 0x11000002, 0x15021222, 0x15021222,
    0x15021222, 0x15021222, 0x11020022, 0x11020022,
};

static const int l_kind_max[][2] = {
    {10, 10}, {0, 1}, {2, 4}, {2, 4}, {5, 8}, {5, 8}, {9, 9}, {11, 11},
};

static sAnmDat l_npc_anm_0[] = {{0, 8, -1}};
static sAnmDat l_npc_anm_2[] = {{1, 8, -1}};
static sAnmDat l_npc_anm_3[] = {{2, 8, -1}};
static sAnmDat l_npc_anm_4[] = {{2, 8, 2}, {0, 8, -1}};
static sAnmDat l_npc_anm_5[] = {{3, 8, -1}};
static sAnmDat l_npc_anm_6[] = {{5, 8, 5}, {6, 8, 1}, {0, 8, -1}};
static sAnmDat l_npc_anm_7[] = {{4, 8, -1}};
static sAnmDat l_npc_anm_wait[] = {{0, 8, -1}};
static sAnmDat l_npc_anm_talk[] = {{1, 8, -1}};
static sAnmDat l_npc_anm_talk2[] = {{9, 8, 1}, {1, 8, -1}};
static sAnmDat l_npc_anm_kuyasi[] = {{4, 8, -1}};
static sAnmDat l_npc_anm_happy[] = {{8, 8, -1}};
static sAnmDat l_npc_anm_dousho[] = {{3, 8, -1}};

static u32 l_npc_msg_id[12][3] = {
    {0x1D26, 0x1D27, 0x1D28},
    {0x1D29, 0x1D2A, 0x1D2B},
    {0x1D2C, 0x1D2D, 0x1D2E},
    {0x1D2F, 0x1D30, 0x1D31},
    {0x1D32, 0x1D33, 0x1D34},
    {0x3391, 0x3392, 0x3393},
    {0x3394, 0x3395, 0x3396},
    {0x3397, 0x3398, 0x3399},
    {0x339A, 0x339B, 0x339C},
    {0x1D38, 0x1D39, 0x1D39},
    {0, 0, 0},
    {0, 0, 0},
};

static char* l_npc_staff_id[] = {
    "Auc7", "Auc1", "Auc2", "Auc3", "Auc4", "Auc5", "Auc6", "Auc0",
};

static BOOL daNpc_Auction_nodeCallBack1(J3DNode*, int);
static BOOL daNpc_Auction_nodeCallBack2(J3DNode*, int);

static J3DNodeCallBack l_node_call_back_tbl[] = {
    daNpc_Auction_nodeCallBack1,
    daNpc_Auction_nodeCallBack2,
    daNpc_Auction_nodeCallBack2,
    daNpc_Auction_nodeCallBack2,
    daNpc_Auction_nodeCallBack2,
    daNpc_Auction_nodeCallBack2,
    daNpc_Auction_nodeCallBack2,
    daNpc_Auction_nodeCallBack1,
};

static daNpc_Auction2_HIO_c l_npc_dat[12] = {
    daNpc_Auction2_HIO_c(0.0f, 4000, 0, 8000, 8000, -3700, 0, -8000, -8000, 1500, 1700, 195.0f, 0x7FFF, 0, 0.0f, 160.0f, 10.0f, 185.0f),
    daNpc_Auction2_HIO_c(0.0f, 4000, 0, 4000, 7000, -4000, 0, -7000, -8000, 1000, 1500, 180.0f, 0x7FFF, 0, 0.0f, 150.0f, 5.0f, 180.0f),
    daNpc_Auction2_HIO_c(0.0f, 4000, 0, 8000, 8000, -7000, 0, -8000, -8000, 1000, 1300, 175.0f, 0x7FFF, 0, 0.0f, 150.0f, 0.0f, 175.0f),
    daNpc_Auction2_HIO_c(0.0f, 4000, 0, 5000, 8000, -3500, 0, -5000, -8000, 1000, 1500, 170.0f, 0x7FFF, 0, 0.0f, 150.0f, 0.0f, 170.0f),
    daNpc_Auction2_HIO_c(0.0f, 4000, 0, 9000, 5000, -5000, 0, -9000, -5000, 2000, 1500, 175.0f, 0x7FFF, 0, 0.0f, 150.0f, 0.0f, 175.0f),
    daNpc_Auction2_HIO_c(0.0f, 2500, 0, 7000, 7000, -1000, 0, -7000, -7000, 700, 1300, 190.0f, 0x7FFF, 0, 0.0f, 150.0f, 15.0f, 190.0f),
    daNpc_Auction2_HIO_c(0.0f, 2500, 0, 7000, 7000, -1000, 0, -7000, -7000, 700, 1300, 165.0f, 0x7FFF, 0, 0.0f, 150.0f, 0.0f, 165.0f),
    daNpc_Auction2_HIO_c(0.0f, 4000, 0, 9000, 6000, -1000, 0, -9000, -6000, 2000, 1500, 175.0f, 0x7FFF, 0, 0.0f, 150.0f, 0.0f, 175.0f),
    daNpc_Auction2_HIO_c(0.0f, 4000, 0, 8000, 5000, -4000, 0, -8000, -5000, 2000, 2500, 180.0f, 0x7FFF, 0, 0.0f, 150.0f, 10.0f, 180.0f),
    daNpc_Auction2_HIO_c(0.0f, 2500, 2000, 6000, 8000, -500, -2000, -6000, -8000, 1000, 1500, 210.0f, 0x7FFF, 0, 0.0f, 180.0f, 0.0f, 210.0f),
    daNpc_Auction2_HIO_c(-20.0f, 512, 5000, 512, 6000, -512, -5000, -512, -6000, 4096, 2048, 165.0f, 0x7FFF, 0, 400.0f, 80.0f, 0.0f, 120.0f),
    daNpc_Auction2_HIO_c(-20.0f, 512, 5000, 512, 6000, -512, -5000, -512, -6000, 4096, 2048, 140.0f, 0x7FFF, 0, 0.0f, 80.0f, 0.0f, 120.0f),
};

/* 000000EC-00000268       .text __ct__14daNpcAuction_cFv */
daNpcAuction_c::daNpcAuction_c() {
    m745 = 0;
    mpEmitter = NULL;
    m704 = NULL;
    m747 = 0;
    mpAnmDat = NULL;
    mAnmNo = 0;
    m744 = 1;
    mSeTimer = 0;
}

/* 00000618-00000730       .text daNpc_Auction_nodeCallBack1__FP7J3DNodei */
static BOOL daNpc_Auction_nodeCallBack1(J3DNode* node, int calcTiming) {
    if (calcTiming == J3DNodeCBCalcTiming_In) {
        J3DJoint* joint = (J3DJoint*)node;
        J3DModel* model = j3dSys.getModel();
        daNpcAuction_c* i_this = (daNpcAuction_c*)model->getUserArea();
        s32 jntNo = joint->getJntNo();
        MTXCopy(model->getAnmMtx(jntNo), *calc_mtx);

        if (jntNo == i_this->m_jnt.getHeadJntNum()) {
            cMtx_YrotM(*calc_mtx, (s16)-i_this->m_jnt.getHead_y());
            cMtx_ZrotM(*calc_mtx, (s16)-i_this->m_jnt.getHead_x());
        }
        if (jntNo == i_this->m_jnt.getBackboneJntNum()) {
            cMtx_XrotM(*calc_mtx, (s16)i_this->m_jnt.getBackbone_y());
            cMtx_ZrotM(*calc_mtx, (s16)i_this->m_jnt.getBackbone_x());
        }

        model->setAnmMtx(jntNo, *calc_mtx);
        MTXCopy(*calc_mtx, J3DSys::mCurrentMtx);
    }
    return TRUE;
}

/* 00000730-00000848       .text daNpc_Auction_nodeCallBack2__FP7J3DNodei */
static BOOL daNpc_Auction_nodeCallBack2(J3DNode* node, int calcTiming) {
    if (calcTiming == J3DNodeCBCalcTiming_In) {
        J3DJoint* joint = (J3DJoint*)node;
        J3DModel* model = j3dSys.getModel();
        daNpcAuction_c* i_this = (daNpcAuction_c*)model->getUserArea();
        s32 jntNo = joint->getJntNo();
        MTXCopy(model->getAnmMtx(jntNo), *calc_mtx);

        if (jntNo == i_this->m_jnt.getHeadJntNum()) {
            cMtx_XrotM(*calc_mtx, (s16)i_this->m_jnt.getHead_y());
            cMtx_ZrotM(*calc_mtx, (s16)-i_this->m_jnt.getHead_x());
        }
        if (jntNo == i_this->m_jnt.getBackboneJntNum()) {
            cMtx_XrotM(*calc_mtx, (s16)i_this->m_jnt.getBackbone_y());
            cMtx_ZrotM(*calc_mtx, (s16)-i_this->m_jnt.getBackbone_x());
        }

        model->setAnmMtx(jntNo, *calc_mtx);
        MTXCopy(*calc_mtx, J3DSys::mCurrentMtx);
    }
    return TRUE;
}

/* 00000848-00000868       .text CheckCreateHeap__FP10fopAc_ac_c */
static BOOL CheckCreateHeap(fopAc_ac_c* i_this) {
    return static_cast<daNpcAuction_c*>(i_this)->createHeap();
}

/* 00000868-00000ACC       .text phase_1__FP14daNpcAuction_c */
static cPhs_State phase_1(daNpcAuction_c* i_this) {
    fopAcM_ct(i_this, daNpcAuction_c);

    daAuction_c* auction;
    if (!fopAcM_SearchByName(fpcNm_AUCTION_e, (fopAc_ac_c**)&auction)) {
        return cPhs_INIT_e;
    }
    if (auction == NULL) {
        return cPhs_INIT_e;
    }

    u8 prmNo = i_this->getPrmNpcNo();
    u8 npcNo = auction->getAucNpcNo(prmNo);
    i_this->setNpcNo(npcNo);

    if (!auction->setNpcID(npcNo, fopAcM_GetID(i_this))) {
        return cPhs_INIT_e;
    }

    int minKind = l_kind_max[npcNo][0];
    int maxKind = l_kind_max[npcNo][1];
    u8 kind;
    if (npcNo == 2 || npcNo == 3) {
        if (auction->getKind(0) == 0xFF) {
            kind = minKind + i_this->getRand(maxKind - minKind + 1);
            auction->setKind(0, kind);
        } else {
            kind = minKind + i_this->getRand(maxKind - minKind + 1);
            if (kind == auction->getKind(0)) {
                if (kind == (u8)maxKind) {
                    kind--;
                } else {
                    kind++;
                }
            }
        }
    } else if (npcNo == 4 || npcNo == 5) {
        if (auction->getKind(1) == 0xFF) {
            kind = minKind + i_this->getRand(maxKind - minKind + 1);
            auction->setKind(1, kind);
        } else {
            kind = minKind + i_this->getRand(maxKind - minKind + 1);
            if (kind == auction->getKind(1)) {
                if (kind == (u8)maxKind) {
                    kind--;
                } else {
                    kind++;
                }
            }
        }
    } else {
        kind = minKind + i_this->getRand(maxKind - minKind + 1);
    }

    i_this->setMdlNo(kind);
    auction->setAucMdlNo(npcNo, kind);
    i_this->setBtpNo(l_btp_ix_tbl[kind]);
    i_this->setBmtNo(l_bmt_ix_tbl[kind]);
    return cPhs_NEXT_e;
}

/* 00000ACC-00000B4C       .text phase_2__FP14daNpcAuction_c */
static cPhs_State phase_2(daNpcAuction_c* i_this) {
    cPhs_State phase_state = dComIfG_resLoad(i_this->getPhaseP(), l_arcname_tbl[i_this->getMdlNo()]);
    if (phase_state == cPhs_COMPLEATE_e) {
        if (fopAcM_entrySolidHeap(i_this, CheckCreateHeap, 0x10000)) {
            return i_this->createInit();
        } else {
#if VERSION > VERSION_DEMO
            i_this->mpMorf = NULL;
#endif
            return cPhs_ERROR_e;
        }
    }
    return phase_state;
}

inline cPhs_State daNpcAuction_c::_create() {
    static cPhs__Handler l_method[] = {
        (cPhs__Handler)phase_1,
        (cPhs__Handler)phase_2,
        NULL,
    };
    return dComLbG_PhaseHandler(&mPhs2, l_method, this);
}

/* 00000B4C-00000E74       .text createHeap__14daNpcAuction_cFv */
BOOL daNpcAuction_c::createHeap() {
    J3DModelData* modelData = (J3DModelData*)dComIfG_getObjectIDRes(l_arcname_tbl[mMdlNo], l_bmd_ix_tbl[mMdlNo]);
    mpMorf = new mDoExt_McaMorf(
        modelData,
        NULL, NULL,
        (J3DAnmTransform*)dComIfG_getObjectIDRes(l_arcname_tbl[mMdlNo], l_bck_ix_tbl[mMdlNo][mAnmNo]),
        J3DFrameCtrl::EMode_LOOP, 1.0f, 0, -1, 1,
        NULL,
        0x80000,
        l_diff_flag_tbl[mMdlNo]
    );

    if (mpMorf == NULL || mpMorf->getModel() == NULL) {
        return FALSE;
    }

    if (l_head_bmd_ix_tbl[mMdlNo] >= 0) {
        J3DModelData* headModelData = (J3DModelData*)dComIfG_getObjectIDRes(l_arcname_tbl[mMdlNo], l_head_bmd_ix_tbl[mMdlNo]);
        mpHeadModel = mDoExt_J3DModel__create(headModelData, 0x80000, 0x15020022);
        if (mpHeadModel == NULL) {
            return FALSE;
        }
    }

    m_jnt.setHeadJntNum(modelData->getJointName()->getIndex("head"));
    JUT_ASSERT(DEMO_SELECT(0x45B, 0x45C), m_jnt.getHeadJntNum() >= 0);
    m_jnt.setBackboneJntNum(modelData->getJointName()->getIndex("backbone"));
    JUT_ASSERT(DEMO_SELECT(0x45F, 0x460), m_jnt.getBackboneJntNum() >= 0);

    if (!initTexPatternAnm(false)) {
        return FALSE;
    }

    for (u16 i = 0; i < modelData->getJointNum(); i++) {
        if (i == m_jnt.getHeadJntNum() || i == m_jnt.getBackboneJntNum()) {
            modelData->getJointNodePointer(i)->setCallBack(l_node_call_back_tbl[mNpcNo]);
        }
    }
    mpMorf->getModel()->setUserArea((u32)this);
    mAcchCir.SetWall(30.0f, 30.0f);
    mObjAcch.Set(fopAcM_GetPosition_p(this), fopAcM_GetOldPosition_p(this), this, 1, &mAcchCir, fopAcM_GetSpeed_p(this), fopAcM_GetAngle_p(this), fopAcM_GetShapeAngle_p(this));
    return TRUE;
}

/* 00000E74-00000E94       .text daNpcAuction_XyCheckCB__FPvi */
static s16 daNpcAuction_XyCheckCB(void* i_this, int i_itemBtn) {
    return ((daNpcAuction_c*)i_this)->XyCheckCB(i_itemBtn);
}

/* 00000E94-00000EB4       .text daNpcAuction_XyEventCB__FPvi */
static s16 daNpcAuction_XyEventCB(void* i_this, int i_itemBtn) {
    return ((daNpcAuction_c*)i_this)->XyEventCB(i_itemBtn);
}

/* 00000EB4-00001038       .text createInit__14daNpcAuction_cFv */
cPhs_State daNpcAuction_c::createInit() {
#if VERSION == VERSION_DEMO
    mStts.Init(0xFF, 0xFF, this);
    mCyl.Set(dNpc_cyl_src);
    mCyl.SetStts(&mStts);
    setCollision(60.0f, 150.0f);
#endif
    gravity = -9.0f;
    mEventCut.setActorInfo2(l_npc_staff_id[mNpcNo], this);
#if VERSION == VERSION_DEMO
    setMtx();
#endif
    mCurrentTurnSpeed = 0;
    mTalking = 0;
    m73D = 0;
    fopAcM_SetMtx(this, mpMorf->getModel()->getBaseTRMtx());
    wait_action_init();
    if (mNpcNo == 0) {
        attention_info.distances[fopAc_Attn_TYPE_TALK_e] = 0xAD;
        attention_info.distances[fopAc_Attn_TYPE_SPEAK_e] = 0xAD;
    } else {
        attention_info.distances[fopAc_Attn_TYPE_TALK_e] = 0xA9;
        attention_info.distances[fopAc_Attn_TYPE_SPEAK_e] = 0xA9;
    }
    attention_info.flags = fopAc_Attn_LOCKON_TALK_e | fopAc_Attn_ACTION_SPEAK_e;
    mEventIdx = dComIfGp_evmng_getEventIdx("AUCTION_TALK_XY", 0xFF);
    eventInfo.setEventName("AUCTION_TALK");
    eventInfo.setXyCheckCB(&daNpcAuction_XyCheckCB);
    eventInfo.setXyEventCB(&daNpcAuction_XyEventCB);
    mMaxAttnDistXZ = l_npc_dat[mMdlNo].mMaxAttnDistXZ;
#if VERSION > VERSION_DEMO
    setMtx();
    mpMorf->getModel()->calc();
    mStts.Init(0xFF, 0xFF, this);
    mCyl.Set(dNpc_cyl_src);
    mCyl.SetStts(&mStts);
    setCollision(60.0f, 150.0f);
#endif
    return cPhs_COMPLEATE_e;
}

/* 00001038-0000105C       .text wait_action_init__14daNpcAuction_cFv */
void daNpcAuction_c::wait_action_init() {
    setAction(&daNpcAuction_c::wait_action);
}

/* 0000105C-00001194       .text wait_action__14daNpcAuction_cFv */
void daNpcAuction_c::wait_action() {
    if (m73D != 0) {
        mEventOrder = 1;
    } else {
        mEventOrder = 0;
    }
    if (mTalking == 1) {
        if (talk(1) == fopMsgStts_BOX_CLOSED_e) {
            mTalking = 0;
            setAnm2(7, 2, 8.0f);
            if (m745 == 0) {
                dComIfGp_event_reset();
            } else if (mNpcNo == 0) {
                daAuction_c* auction = (daAuction_c*)fopAcM_SearchByName(fpcNm_AUCTION_e);
                if (auction != NULL) {
                    if (m745 == 1) {
                        auction->setStart(1);
                    } else if (m745 == 2) {
                        auction->setStart(2);
                        auction->setItemNo(m743);
                    }
                }
            }
        }
        setAnmFromMsgTag();
    }
    if (mAnmNo == 0) {
        setAnm2(7, 2, 8.0f);
    }
}

/* 00001194-000011EC       .text checkOrder__14daNpcAuction_cFv */
void daNpcAuction_c::checkOrder() {
    if (eventInfo.checkCommandDemoAccrpt()) {
        mEventOrder = 0;
        return;
    }
    if (eventInfo.checkCommandTalk()) {
        if (mEventOrder == 2 || mEventOrder == 1) {
            if (mTalking == 0 && m745 == 0) {
                mTalking = 1;
            }
        }
    }
}

/* 000011EC-00001270       .text eventOrder__14daNpcAuction_cFv */
void daNpcAuction_c::eventOrder() {
    if (mEventOrder == 2 || mEventOrder == 1) {
        eventInfo.onCondition(dEvtCnd_CANTALK_e);
        if (dComIfGs_isEventBit(dSv_event_flag_c::UNK_1404)) {
            eventInfo.onCondition(dEvtCnd_CANTALKITEM_e);
        }
        if (mEventOrder == 2) {
            fopAcM_orderSpeakEvent(this);
        }
    }
}

/* 00001270-000013FC       .text eventMove__14daNpcAuction_cFv */
void daNpcAuction_c::eventMove() {
    if (dComIfGp_evmng_endCheck("AUCTION_GET_ITEM") ||
        dComIfGp_evmng_endCheck("AUCTION_NO_ITEM") ||
        dComIfGp_evmng_endCheck("AUCTION_END2"))
    {
        mMaxAttnDistXZ = 200.0f;
    } else if (dComIfGp_evmng_endCheck("AUCTION_TALK_XY")) {
        if (m745 == 0) {
            dComIfGp_event_reset();
        } else if (mNpcNo == 0) {
            daAuction_c* auction = (daAuction_c*)fopAcM_SearchByName(fpcNm_AUCTION_e);
            if (auction != NULL) {
                if (m745 == 1) {
                    auction->setStart(1);
                } else if (m745 == 2) {
                    auction->setStart(2);
                    auction->setItemNo(m743);
                }
            }
        }
        m744 = 1;
        mTalking = 0;
    } else {
        bool attn = mEventCut.getAttnFlag();
        if (mEventCut.cutProc()) {
            if (!mEventCut.getAttnFlag()) {
                mEventCut.setAttnFlag(attn);
            }
        } else {
            privateCut();
            if (mNpcNo == 7) {
                setAnmFromMsgTag();
            }
        }
    }
}

/* 000013FC-00001548       .text privateCut__14daNpcAuction_cFv */
void daNpcAuction_c::privateCut() {
    static char* cut_name_tbl[] = {"MAIN", "MES_SET"};
    int staffIdx = dComIfGp_evmng_getMyStaffId(l_npc_staff_id[mNpcNo]);
    if (staffIdx != -1) {
        mCutAct = dComIfGp_evmng_getMyActIdx(staffIdx, cut_name_tbl, 2, 1, 0);
        if (mCutAct == -1) {
            dComIfGp_evmng_cutEnd(staffIdx);
        } else {
            if (dComIfGp_evmng_getIsAddvance(staffIdx)) {
                switch (mCutAct) {
                case 0:
                    eventMainInit();
                    break;
                case 1:
                    eventMesSetInit(staffIdx);
                    break;
                }
            }
            bool done;
            switch (mCutAct) {
            case 0:
                done = eventMain();
                break;
            case 1:
                done = eventMesSet();
                break;
            default:
                done = true;
                break;
            }
            if (done) {
                dComIfGp_evmng_cutEnd(staffIdx);
            }
        }
    }
}

/* 00001548-00001554       .text eventMainInit__14daNpcAuction_cFv */
void daNpcAuction_c::eventMainInit() {
    m749 = 1;
}

/* 00001554-00001888       .text eventMain__14daNpcAuction_cFv */
bool daNpcAuction_c::eventMain() {
    daAuction_c* auction = (daAuction_c*)fopAcM_SearchByName(fpcNm_AUCTION_e);
    if (auction->isAucBet2()) {
        if ((m747 & 0x08) == 0) {
            setAnm2(3, 2, 8.0f);
            m747 |= 0x08;
        }
    } else if (mNpcNo == auction->getAnmNpcNo()) {
        if (auction->isAucBet()) {
            if ((m747 & 0x04) == 0) {
                setAnm2(2, 2, 8.0f);
                m747 |= 0x04;
            }
        } else if (auction->isAucBetA()) {
            if ((m747 & 0x10) == 0) {
                setAnm2(4, 2, 8.0f);
                m747 |= 0x10;
            }
        } else if (auction->isAucJikkyou()) {
            if ((m747 & 0x40) == 0) {
                setAnm2(6, 2, 8.0f);
                m747 |= 0x40;
            }
        } else if (auction->isAucGet()) {
            if ((m747 & 0x20) == 0) {
                setAnm2(5, 2, 8.0f);
                m747 |= 0x20;
            }
            m749 = 0;
        } else {
            m747 = 0;
            if (mAnmNo != 0) {
                setAnm2(0, 2, 8.0f);
            }
        }
    } else {
        m747 = 0;
        if (mAnmNo != 0) {
            setAnm2(0, 2, 8.0f);
        }
    }

    if (auction->isAucBet2()) {
        if (mpEmitter == NULL) {
            mpEmitter = dComIfGp_particle_set(
                dPa_name::ID_IT_SN_MD_PIYOPIYO00, &current.pos, NULL, NULL, 0xFF, NULL,
                fopAcM_GetRoomNo(this), &tevStr.mColorK0, &tevStr.mColorK0
            );
            if (mpEmitter != NULL) {
                mpEmitter->becomeImmortalEmitter();
            }
        }
        if (mpEmitter != NULL) {
            MTXCopy(mpMorf->getModel()->getAnmMtx(m_jnt.getHeadJntNum()), *calc_mtx);
            mDoMtx_ZrotM(*calc_mtx, -0x4000);
            mDoMtx_stack_c::transS(0.0f, l_npc_dat[mMdlNo].field_0x2C, 0.0f);
            mDoMtx_concat(*calc_mtx, mDoMtx_stack_c::now, *calc_mtx);
            mpEmitter->setGlobalRTMatrix(*calc_mtx);
        }
    } else {
        clrEmitter();
    }
    return FALSE;
}

/* 00001888-000018FC       .text eventMesSetInit__14daNpcAuction_cFi */
void daNpcAuction_c::eventMesSetInit(int staff) {
    int* msg = dComIfGp_evmng_getMyIntegerP(staff, "MsgNo");
    if (msg != NULL) {
        mCurrMsgNo = *msg;
    } else {
        mCurrMsgNo = getMsg();
    }
}

/* 000018FC-00001930       .text eventMesSet__14daNpcAuction_cFv */
bool daNpcAuction_c::eventMesSet() {
    return talk(0) == fopMsgStts_BOX_CLOSED_e;
}

/* 00001930-00001938       .text XyCheckCB__14daNpcAuction_cFi */
s16 daNpcAuction_c::XyCheckCB(int) {
    return 0;
}

/* 00001938-000019F8       .text XyEventCB__14daNpcAuction_cFi */
s16 daNpcAuction_c::XyEventCB(int i_itemBtn) {
    s16 eventIdx = dComIfGp_evmng_getEventIdx("DEFAULT_TALK_XY", 0xFF);
    u8 itemNo = dComIfGp_getSelectItem(i_itemBtn);
    if (itemNo == dItemNo_POSTMAN_STATUE_e) {
        if (!dComIfGs_isEventBit(dSv_event_flag_c::UNK_1008)) {
            eventIdx = mEventIdx;
            m744 = 0;
        }
    } else if (itemNo == dItemNo_SHOP_GURU_STATUE_e) {
        if (!dComIfGs_isEventBit(dSv_event_flag_c::UNK_1004)) {
            eventIdx = mEventIdx;
            m744 = 0;
        }
    }
    return eventIdx;
}

/* 000019F8-00001CD4       .text next_msgStatus__14daNpcAuction_cFPUl */
u16 daNpcAuction_c::next_msgStatus(u32* pMsgNo) {
    daAuction_c* auction = (daAuction_c*)fopAcM_SearchByName(fpcNm_AUCTION_e);
    u16 status = fopMsgStts_MSG_CONTINUES_e;
    switch (*pMsgNo) {
    case 0x27DA:
        *pMsgNo = 0x27DC;
        break;
    case 0x27DB:
        *pMsgNo = 0x27DF;
        break;
    case 0x27DC:
        *pMsgNo = 0x27DD;
        break;
    case 0x27DD:
        *pMsgNo = 0x27DE;
        break;
    case 0x27DE:
        *pMsgNo = 0x27DF;
        break;
    case 0x27DF:
        if (mpCurrMsg->mSelectNum == 0) {
            *pMsgNo = 0x27E1;
            dComIfGs_onEventBit(dSv_event_flag_c::UNK_1408);
        } else {
            *pMsgNo = 0x27E0;
        }
        break;
    case 0x27E1:
        *pMsgNo = 0x27E2;
        break;
    case 0x27E2:
        if (mpCurrMsg->mSelectNum == 0) {
            *pMsgNo = 0x27E3;
        } else {
            *pMsgNo = 0x27E4;
        }
        break;
    case 0x27E3:
        *pMsgNo = 0x27E9;
        break;
    case 0x27E4:
        *pMsgNo = 0x27E5;
        break;
    case 0x27E5:
        *pMsgNo = 0x27E6;
        break;
    case 0x27E6:
        *pMsgNo = 0x27E7;
        break;
    case 0x27E7:
        if (mpCurrMsg->mSelectNum == 0) {
            *pMsgNo = 0x27E9;
        } else {
            *pMsgNo = 0x27E8;
        }
        break;
    case 0x27E8:
        *pMsgNo = 0x27E5;
        break;
    case 0x27E9:
        m745 = 1;
        status = fopMsgStts_MSG_ENDS_e;
        break;
    case 0x27EB:
        status = fopMsgStts_MSG_ENDS_e;
        break;
    case 0x27EC:
        if (mpCurrMsg->mSelectNum == 0) {
            *pMsgNo = 0x27EE;
            dComIfGs_setReserveItemEmpty();
        } else {
            *pMsgNo = 0x27ED;
        }
        break;
    case 0x27EE:
        *pMsgNo = 0x27EF;
        break;
    case 0x27EF:
        m745 = 2;
        status = fopMsgStts_MSG_ENDS_e;
        break;
    case 0x1D35:
        *pMsgNo = 0x1D36;
        break;
    case 0x1D36:
        *pMsgNo = 0x1D37;
        break;
    case 0x1D37:
        if (auction->m827 == 0) {
            *pMsgNo = 0x1D38;
        } else {
            *pMsgNo = 0x1D39;
        }
        break;
    default:
        status = fopMsgStts_MSG_ENDS_e;
        break;
    }
    return status;
}

/* 00001CD4-00001F04       .text getMsg__14daNpcAuction_cFv */
u32 daNpcAuction_c::getMsg() {
    u32 msgNo;
    if (mNpcNo == 0) {
        if (dComIfGp_event_chkTalkXY()) {
            u8 itemNo = dComIfGp_event_getPreItemNo();
            if (itemNo == dItemNo_POSTMAN_STATUE_e) {
                if (!dComIfGs_isEventBit(dSv_event_flag_c::UNK_1008)) {
                    msgNo = 0x27EB;
                    m743 = 0;
                } else {
                    msgNo = 0x27F7;
                }
            } else if (itemNo == dItemNo_SHOP_GURU_STATUE_e) {
                if (!dComIfGs_isEventBit(dSv_event_flag_c::UNK_1004)) {
                    msgNo = 0x27EB;
                    m743 = 1;
                } else {
                    msgNo = 0x27F7;
                }
            } else {
                msgNo = 0x27EA;
            }
        } else if (dComIfGs_isEventBit(dSv_event_flag_c::ENDLESS_NIGHT) &&
                   !dComIfGs_checkGetItem(dItemNo_PEARL_NAYRU_e))
        {
            msgNo = 0x27F8;
        } else if (dComIfGs_isEventBit(dSv_event_flag_c::UNK_1002)) {
            if (dComIfGs_isEventBit(dSv_event_flag_c::UNK_0F01) &&
                dComIfGs_isEventBit(dSv_event_flag_c::UNK_1080) &&
                dComIfGs_isEventBit(dSv_event_flag_c::UNK_1040) &&
                dComIfGs_isEventBit(dSv_event_flag_c::UNK_1020))
            {
                msgNo = 0x27F0;
            } else {
                msgNo = 0x27DB;
            }
        } else {
            dComIfGs_onEventBit(dSv_event_flag_c::UNK_1002);
            msgNo = 0x27DA;
        }
    } else if (mNpcNo == 6) {
        msgNo = 0x1D35;
    } else {
        daAuction_c* auction = (daAuction_c*)fopAcM_SearchByName(fpcNm_AUCTION_e);
        u8 winner = auction->getNpcNo();
        if (winner == 0) {
            msgNo = l_npc_msg_id[mMdlNo][0];
        } else if (winner == mNpcNo) {
            msgNo = l_npc_msg_id[mMdlNo][1];
        } else {
            msgNo = l_npc_msg_id[mMdlNo][2];
        }
    }
    return msgNo;
}

/* 00001F04-00002070       .text setAnmFromMsgTag__14daNpcAuction_cFv */
void daNpcAuction_c::setAnmFromMsgTag() {
    int attr = dComIfGp_getMesgAnimeAttrInfo();
    if (mNpcNo == 0 || mNpcNo == 7) {
        switch (attr) {
        case 0:
        case 1:
            setAnmTbl(l_npc_anm_0);
            break;
        case 2:
            setAnmTbl(l_npc_anm_2);
            break;
        case 3:
            setAnmTbl(l_npc_anm_3);
            break;
        case 4:
            setAnmTbl(l_npc_anm_4);
            break;
        case 5:
            setAnmTbl(l_npc_anm_5);
            break;
        case 6:
            setAnmTbl(l_npc_anm_6);
            mSeNo = JA_SE_AUC_START;
            mSeTimer = 100;
            break;
        case 7:
            setAnmTbl(l_npc_anm_7);
            break;
        }
    } else {
        switch (attr) {
        case 0:
            setAnmTbl(l_npc_anm_0);
            break;
        case 1:
            setAnmTbl(l_npc_anm_talk);
            break;
        case 2:
            setAnmTbl(l_npc_anm_kuyasi);
            break;
        case 3:
        case 5:
            setAnmTbl(l_npc_anm_happy);
            break;
        case 4:
        case 7:
            setAnmTbl(l_npc_anm_talk2);
            break;
        case 6:
            setAnmTbl(l_npc_anm_talk2);
            break;
        }
    }
    dComIfGp_clearMesgAnimeAttrInfo();
}

/* 00002070-00002090       .text getPrmNpcNo__14daNpcAuction_cFv */
u8 daNpcAuction_c::getPrmNpcNo() {
    if (argument >= 0 && argument < 8) {
        return argument;
    }
    return 0;
}

/* 00002090-00002118       .text setMtx__14daNpcAuction_cFv */
void daNpcAuction_c::setMtx() {
    mpMorf->getModel()->setBaseScale(scale);
    mDoMtx_stack_c::transS(current.pos.x, current.pos.y, current.pos.z);
    mDoMtx_stack_c::YrotM(current.angle.y);
    mpMorf->getModel()->setBaseTRMtx(mDoMtx_stack_c::get());
}

/* 00002118-00002488       .text lookBack__14daNpcAuction_cFv */
void daNpcAuction_c::lookBack() {
    f32 attnY = l_npc_dat[mMdlNo].m04;
    s16 maxVel = l_npc_dat[mMdlNo].mMaxHeadTurnVel;
    s16 defaultY = current.angle.y;
    cXyz* dstPosP = NULL;
    cXyz dstPos;
    bool noTurn = true;

    if (m749 != 0) {
        fopAc_ac_c* auction = fopAcM_SearchByName(fpcNm_AUCTION_e);
        if (auction != NULL) {
            if (eyePos.x != auction->eyePos.x || eyePos.y != auction->eyePos.y || eyePos.z != auction->eyePos.z) {
                dstPos = auction->eyePos;
                dstPosP = &dstPos;
            }
        }
    } else if (mEventCut.getAttnFlag()) {
        m_jnt.setTrn();
        dstPos = mEventCut.getAttnPos();
        dstPosP = &dstPos;
        noTurn = false;
        if (m73D == 0) {
            m73D = 1;
        }
    } else {
        fopAc_ac_c* player = dComIfGp_getLinkPlayer();
        f32 maxDist = mMaxAttnDistXZ;
        int maxAng = l_npc_dat[mMdlNo].mMaxAttnAngleY;
        int lim0 = 0x4000;
        f32 dist;
        s16 ang;
        dNpc_calc_DisXZ_AngY(current.pos, player->current.pos, &dist, &ang);
        if (m73D != 0) {
            maxDist += 40.0f;
            lim0 = 0x471C;
            maxAng += 0x71C;
        }
        ang -= current.angle.y;
        if (maxDist > dist && lim0 > abs(ang)) {
            dstPos = dNpc_playerEyePos(attnY);
            dstPosP = &dstPos;
            noTurn = true;
            if (m73D == 0) {
                m73D = 1;
            }
        } else if (maxDist > dist && maxAng > abs(ang)) {
            if (mTalking != 0) {
                dstPos = dNpc_playerEyePos(attnY);
                dstPosP = &dstPos;
                noTurn = false;
                m_jnt.setTrn();
            }
            if (m73D == 0) {
                m73D = 1;
            }
        } else {
            m73D = 0;
            if (mNpcNo == 0) {
                defaultY = home.angle.y;
                noTurn = false;
                m_jnt.setTrn();
            }
        }
    }

    if (mTalking != 0) {
        noTurn = false;
        m_jnt.setTrn();
    }
    if (m_jnt.trnChk()) {
        s16 t = mEventCut.getTurnSpeed();
        if (t != 0) {
            maxVel = t;
        }
        cLib_addCalcAngleS2(&mCurrentTurnSpeed, maxVel, 4, 0x800);
    } else {
        mCurrentTurnSpeed = 0;
    }
    m_jnt.lookAtTarget(&current.angle.y, dstPosP, eyePos, defaultY, mCurrentTurnSpeed, noTurn);
    shape_angle = current.angle;
}

/* 00002488-000025AC       .text initTexPatternAnm__14daNpcAuction_cFb */
BOOL daNpcAuction_c::initTexPatternAnm(bool i_modify) {
    J3DModelData* modelData;
    if (mpHeadModel != NULL) {
        modelData = mpHeadModel->getModelData();
    } else {
        modelData = mpMorf->getModel()->getModelData();
    }
    m_head_tex_pattern = (J3DAnmTexPattern*)dComIfG_getObjectIDRes(l_arcname_tbl[mMdlNo], mBtpNo);
    JUT_ASSERT(DEMO_SELECT(0x891, 0x89B), m_head_tex_pattern != 0);
    if (!mBtpAnm.init(modelData, m_head_tex_pattern, TRUE, J3DFrameCtrl::EMode_LOOP, 1.0f, 0, -1, i_modify, FALSE)) {
        return FALSE;
    }
    mBtpFrame = 0;
    mBtpTimer = 0;
    return TRUE;
}

/* 000025AC-00002624       .text playTexPatternAnm__14daNpcAuction_cFv */
void daNpcAuction_c::playTexPatternAnm() {
    if (cLib_calcTimer(&mBtpTimer) == 0) {
        if (mBtpFrame >= m_head_tex_pattern->getFrameMax()) {
            mBtpFrame -= m_head_tex_pattern->getFrameMax();
            mBtpTimer = getRand(0x3C) + 0x3C;
        } else {
            mBtpFrame++;
        }
    }
}

/* 00002624-000026CC       .text playAnm__14daNpcAuction_cFv */
void daNpcAuction_c::playAnm() {
    if (mpMorf->play(NULL, 0, 0) && mpAnmDat != NULL && mAnmCount > 0) {
        mAnmCount--;
        if (mAnmCount == 0) {
            mpAnmDat++;
            setAnmTbl(mpAnmDat);
        } else {
            setAnm(mpAnmDat->mAnm, 0, 0.0f);
        }
    }
}

/* 000026CC-0000278C       .text setAnm__14daNpcAuction_cFUcif */
void daNpcAuction_c::setAnm(u8 idx, int mode, f32 morf) {
    J3DAnmTransform* anm = (J3DAnmTransform*)dComIfG_getObjectIDRes(l_arcname_tbl[mMdlNo], l_bck_ix_tbl[mMdlNo][idx]);
    mpMorf->setAnm(anm, mode, morf, 1.0f, 0.0f, -1.0f, NULL);
    mAnmNo = idx;
}

/* 0000278C-000027DC       .text setAnm2__14daNpcAuction_cFUcif */
void daNpcAuction_c::setAnm2(u8 idx, int mode, f32 morf) {
    if (mAnmNo != idx || mode == 0) {
        setAnm(idx, mode, morf);
        mpAnmDat = NULL;
    }
}

/* 000027DC-00002874       .text setAnmTbl__14daNpcAuction_cFP7sAnmDat */
void daNpcAuction_c::setAnmTbl(sAnmDat* pDat) {
    if (pDat->mAnm == 0xFF) {
        mpAnmDat = NULL;
        return;
    }
    mpAnmDat = pDat;
    mAnmCount = mpAnmDat->mCount;
    int mode = 2;
    if (mAnmCount > 0) {
        mode = 0;
    }
    if (mAnmNo != mpAnmDat->mAnm || mode == 0) {
        setAnm(mpAnmDat->mAnm, mode, mpAnmDat->mMorf);
    }
}

static u32 l_mdl_status[] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x27, 0x27,
};

/* 00002874-00002928       .text isExecute__14daNpcAuction_cFv */
BOOL daNpcAuction_c::isExecute() {
    fopAcM_OffStatus(this, l_mdl_status[mMdlNo]);
    daAuction_c* auction = (daAuction_c*)fopAcM_SearchByName(fpcNm_AUCTION_e);
    if (auction == NULL) {
        return FALSE;
    }
    if (!auction->chkNpcExec(mNpcNo)) {
        return FALSE;
    }
    fopAcM_OnStatus(this, l_mdl_status[mMdlNo]);
    return TRUE;
}

/* 00002928-0000298C       .text getRand__14daNpcAuction_cFi */
int daNpcAuction_c::getRand(int max) {
    int n = cM_rndF(max);
    if (n == max) {
        n = 0;
    }
    return n;
}

/* 0000298C-000029DC       .text clrEmitter__14daNpcAuction_cFv */
void daNpcAuction_c::clrEmitter() {
    JPABaseEmitter* em = mpEmitter;
    if (em != NULL) {
        em->becomeInvalidEmitter();
        JSULink<JPABaseParticle>* link = em->getParticleList()->getFirst();
        while (link != NULL) {
            link->getObject()->setDeleteParticleFlag();
            link = link->getNext();
        }
        mpEmitter = NULL;
    }
}

inline BOOL daNpcAuction_c::_delete() {
    dComIfG_resDeleteDemo(&mPhs, l_arcname_tbl[mMdlNo]);
#if VERSION == VERSION_DEMO
    if (mpMorf != NULL) {
#else
    if (heap != NULL && mpMorf != NULL) {
#endif
        mpMorf->stopZelAnime();
    }
    return TRUE;
}

inline BOOL daNpcAuction_c::_execute() {
    if (isExecute()) {
        daNpc_Auction2_HIO_c* dat = &l_npc_dat[mMdlNo];
        m_jnt.setParam(
            dat->mMaxBackboneX, dat->mMaxBackboneY, dat->mMinBackboneX, dat->mMinBackboneY,
            dat->mMaxHeadX, dat->mMaxHeadY, dat->mMinHeadX, dat->mMinHeadY, dat->mMaxTurnStep
        );
        checkOrder();
        if (!dComIfGp_event_runCheck() || (eventInfo.checkCommandTalk() && m744 != 0)) {
            m749 = 0;
            (this->*mAction)();
        } else {
            eventMove();
        }
        eventOrder();
        playTexPatternAnm();
        playAnm();
        mObjAcch.CrrPos(*dComIfG_Bgsp());
        setCollision(60.0f, 150.0f);
        attention_info.position.set(current.pos.x, current.pos.y + l_npc_dat[mMdlNo].mAttnYOffset, current.pos.z);
        eyePos.set(current.pos.x, current.pos.y + l_npc_dat[mMdlNo].field_0x28, current.pos.z);
        lookBack();
        setMtx();
        if (mSeTimer != 0) {
            mSeTimer--;
            if (mSeTimer == 0) {
                mDoAud_seStart(mSeNo);
            }
        }
        mPiconOfsY = l_npc_dat[mMdlNo].field_0x30;
    }
    return FALSE;
}

inline BOOL daNpcAuction_c::_draw() {
    if (isExecute()) {
        J3DModel* pModel = mpMorf->getModel();
        J3DModelData* pModelData = pModel->getModelData();
        if (mpHeadModel != NULL) {
            pModelData = mpHeadModel->getModelData();
            g_env_light.settingTevStruct(TEV_TYPE_ACTOR, &current.pos, &tevStr);
            g_env_light.setLightTevColorType(mpMorf->getModel(), &tevStr);
            g_env_light.setLightTevColorType(mpHeadModel, &tevStr);
            mBtpAnm.entry(pModelData, mBtpFrame);
            if (mBmtNo >= 0) {
                mpMorf->updateDL((J3DMaterialTable*)dComIfG_getObjectIDRes(l_arcname_tbl[mMdlNo], mBmtNo));
            } else {
                mpMorf->updateDL();
            }
            mpHeadModel->setBaseTRMtx(pModel->getAnmMtx(m_jnt.getHeadJntNum()));
            mDoExt_modelUpdateDL(mpHeadModel);
            mBtpAnm.remove(pModelData);
        } else {
            g_env_light.settingTevStruct(TEV_TYPE_ACTOR, &current.pos, &tevStr);
            g_env_light.setLightTevColorType(mpMorf->getModel(), &tevStr);
            mBtpAnm.entry(pModelData, mBtpFrame);
            mpMorf->updateDL();
            mBtpAnm.remove(pModelData);
        }

        cXyz shadowPos(current.pos.x, current.pos.y + 150.0f, current.pos.z);
        mShadowId = dComIfGd_setShadow(
            mShadowId, 1, mpMorf->getModel(), &shadowPos, 800.0f, 20.0f,
            current.pos.y, mObjAcch.GetGroundH(), mObjAcch.m_gnd, &tevStr
        );
        if (mShadowId != 0 && mpHeadModel != NULL) {
            dComIfGd_addRealShadow(mShadowId, mpHeadModel);
        }
        dSnap_RegistFig(l_photo_no[mMdlNo], this, 1.0f, 1.0f, 1.0f);
    }
    return TRUE;
}

/* 000029DC-00002A0C       .text daNpc_AuctionCreate__FPv */
static cPhs_State daNpc_AuctionCreate(void* i_this) {
    return ((daNpcAuction_c*)i_this)->_create();
}

/* 00002A0C-00002A70       .text daNpc_AuctionDelete__FPv */
static BOOL daNpc_AuctionDelete(void* i_this) {
    return ((daNpcAuction_c*)i_this)->_delete();
}

/* 00002A70-00002C70       .text daNpc_AuctionExecute__FPv */
static BOOL daNpc_AuctionExecute(void* i_this) {
    return ((daNpcAuction_c*)i_this)->_execute();
}

/* 00002C70-00002EB8       .text daNpc_AuctionDraw__FPv */
static BOOL daNpc_AuctionDraw(void* i_this) {
    return ((daNpcAuction_c*)i_this)->_draw();
}

/* 00002EB8-00002EC0       .text daNpc_AuctionIsDelete__FPv */
static BOOL daNpc_AuctionIsDelete(void*) {
    return TRUE;
}

static actor_method_class daNpc_AuctionMethodTable = {
    (process_method_func)daNpc_AuctionCreate,
    (process_method_func)daNpc_AuctionDelete,
    (process_method_func)daNpc_AuctionExecute,
    (process_method_func)daNpc_AuctionIsDelete,
    (process_method_func)daNpc_AuctionDraw,
};

actor_process_profile_definition g_profile_NPC_AUCTION = {
    /* Layer ID     */ fpcLy_CURRENT_e,
    /* List ID      */ 0x0007,
    /* List Prio    */ fpcPi_CURRENT_e,
    /* Proc Name    */ fpcNm_NPC_AUCTION_e,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(daNpcAuction_c),
    /* Size Other   */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Draw Prio    */ fpcDwPi_NPC_AUCTION_e,
    /* Actor SubMtd */ &daNpc_AuctionMethodTable,
    /* Status       */ fopAcStts_NOCULLEXEC_e | fopAcStts_CULL_e | fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ACTOR_e,
    /* Cull Type    */ fopAc_CULLBOX_0_e,
};
