//
// Generated by dtk
// Translation Unit: d_a_tag_kf1.cpp
//

#include "d/dolzel_rel.h" // IWYU pragma: keep
#include "d/actor/d_a_tag_kf1.h"
#include "d/actor/d_a_tsubo.h"
#include "d/d_com_inf_game.h"
#include "f_op/f_op_actor_mng.h"
#include "m_Do/m_Do_hostIO.h"

struct daTag_Kf1_prm_c {
    f32 mDistance;
    f32 mHeight;
    u8 mDebug;
};

class daTag_Kf1_HIO_c : public JORReflexible {
public:
    daTag_Kf1_HIO_c();
    virtual ~daTag_Kf1_HIO_c() {}
    void genMessage(JORMContext* ctx) { UNUSED(ctx); }
    s8 mNo;
    daTag_Kf1_prm_c mPrm;
};

static daTag_Kf1_HIO_c l_HIO;
static fopAc_ac_c* l_check_inf[100];
static int l_check_wrk;

/* 000000EC-00000120       .text __ct__15daTag_Kf1_HIO_cFv */
daTag_Kf1_HIO_c::daTag_Kf1_HIO_c() {
    static daTag_Kf1_prm_c a_prm_tbl = {150.0f, 30.0f, 0};
    mPrm = a_prm_tbl;
    mNo = -1;
}

/* 00000120-000001B0       .text searchActor_Kutani__FPvPv */
static void* searchActor_Kutani(void* actor, void*) {
    if (l_check_wrk < 100 && fopAc_IsActor(actor) && fopAcM_GetName(actor) == fpcNm_TSUBO_e && static_cast<daTsubo::Act_c*>(actor)->prm_chk_type_kutani()) {
        l_check_inf[l_check_wrk] = static_cast<fopAc_ac_c*>(actor);
        l_check_wrk++;
    }
    return NULL;
}

/* 000001B0-00000220       .text createInit__11daTag_Kf1_cFv */
BOOL daTag_Kf1_c::createInit() {
    mCut.setActorInfo("TagKf1", this);
    set_action(&daTag_Kf1_c::wait_action1, NULL);
    return TRUE;
}

/* 00000220-00000234       .text setStt__11daTag_Kf1_cFSc */
void daTag_Kf1_c::setStt(signed char state) {
    mState = state;
    switch (mState) {
    case 0:
    case 1:
    case 2:
        break;
    }
}

/* 00000234-00000294       .text next_msgStatus__11daTag_Kf1_cFPUl */
u16 daTag_Kf1_c::next_msgStatus(unsigned long* msg) {
    u16 status = fopMsgStts_MSG_CONTINUES_e;
    switch (*msg) {
    case 0x1C30:
        *msg = 0x1C35;
        break;
    case 0x1C35:
        *msg = 0x1C31;
        break;
    case 0x1C2E:
        mRupees = dComIfGs_getRupee();
    default:
        status = fopMsgStts_MSG_ENDS_e;
        break;
    }
    return status;
}

/* 00000294-00000314       .text eventOrder__11daTag_Kf1_cFv */
void daTag_Kf1_c::eventOrder() {
    static char* a_demo_name_tbl[] = {"BENSYO"};
    if (mOrder == 1 || mOrder == 2) {
        eventInfo.onCondition(1);
        if (mOrder == 1) fopAcM_orderSpeakEvent(this);
    } else if (mOrder >= 3) {
        fopAcM_orderOtherEvent2(this, a_demo_name_tbl[mOrder - 3], 1, 0xFFFF);
    }
}

/* 00000314-00000380       .text checkOrder__11daTag_Kf1_cFv */
void daTag_Kf1_c::checkOrder() {
    if (eventInfo.checkCommandDemoAccrpt() && dComIfGp_evmng_startCheck("BENSYO") && mOrder == 3) mOrder = 0;
}

/* 00000380-00000470       .text chkAttention__11daTag_Kf1_cF4cXyz */
BOOL daTag_Kf1_c::chkAttention(cXyz pos) {
    BOOL result = FALSE;
    f32 distance = pos.abs(dComIfGp_getPlayer(0)->current.pos);
    f32 height = dComIfGp_getPlayer(0)->current.pos.y - pos.y;
    if (distance < l_HIO.mPrm.mDistance && height < l_HIO.mPrm.mHeight) result = TRUE;
    return result;
}

/* 00000470-0000057C       .text partner_srch__11daTag_Kf1_cFv */
BOOL daTag_Kf1_c::partner_srch() {
    BOOL result = FALSE;
    int i;
    for (i = 0; i < 8; i++) mPotIds[i] = fpcM_ERROR_PROCESS_ID_e;
    l_check_wrk = 0;
    for (i = 0; i < 100; i++) l_check_inf[i] = NULL;
    fpcM_Search(searchActor_Kutani, this);
    if (l_check_wrk <= 8 && l_check_wrk != 0) {
        mPotCount = 0;
        for (i = 0; i < l_check_wrk; i++) {
            mPotIds[i] = fopAcM_GetID(l_check_inf[i]);
            mPotCount++;
        }
        result = TRUE;
    }
    return result;
}

/* 0000057C-00000604       .text checkPartner__11daTag_Kf1_cFv */
s16 daTag_Kf1_c::checkPartner() {
    s16 count = 0;
    for (int i = 0; i < mPotCount; i++) {
        if (fopAcM_SearchByID(mPotIds[i]) != NULL) count++;
    }
    return count;
}

/* 00000604-00000650       .text goto_nextStage__11daTag_Kf1_cFv */
void daTag_Kf1_c::goto_nextStage() {
    dComIfGp_setNextStage(dComIfGp_getStartStageName(), 0, -1);
}

/* 00000650-000006DC       .text event_talkInit__11daTag_Kf1_cFi */
void daTag_Kf1_c::event_talkInit(int staffIdx) {
    int* msg = dComIfGp_evmng_getMyIntegerP(staffIdx, "MsgNo");
    mCurrMsgBsPcId = fpcM_ERROR_PROCESS_ID_e;
    if (msg != NULL) {
        mCurrMsgNo = *msg;
        if (mCurrMsgNo == 0x1C2D) dComIfGp_setMessageCountNumber(mBrokenCount * 10);
    } else {
        mCurrMsgNo = 0;
    }
}

/* 000006DC-0000071C       .text event_mesSet__11daTag_Kf1_cFv */
bool daTag_Kf1_c::event_mesSet() {
    talk(0);
    return mCurrMsgBsPcId != fpcM_ERROR_PROCESS_ID_e;
}

/* 0000071C-00000750       .text event_mesEnd__11daTag_Kf1_cFv */
bool daTag_Kf1_c::event_mesEnd() {
    return talk(0) == fopMsgStts_BOX_CLOSED_e;
}

/* 00000750-000007A4       .text bensyoInit__11daTag_Kf1_cFv */
void daTag_Kf1_c::bensyoInit() {
    dComIfGp_setItemRupeeCount(-(mBrokenCount * 10));
    mCurrMsgBsPcId = fpcM_ERROR_PROCESS_ID_e;
    if (mRupees > mBrokenCount * 10) mCurrMsgNo = 0x1C2F;
    else mCurrMsgNo = 0x1C30;
}

/* 000007A4-000007C4       .text event_bensyo__11daTag_Kf1_cFv */
bool daTag_Kf1_c::event_bensyo() {
    return event_mesSet();
}

/* 000007C4-000007FC       .text event_cntTsubo__11daTag_Kf1_cFv */
void daTag_Kf1_c::event_cntTsubo() {
    mBrokenCount = mPotCount - checkPartner();
}

/* 000007FC-00000978       .text privateCut__11daTag_Kf1_cFv */
void daTag_Kf1_c::privateCut() {
    static char* cut_name_tbl[] = {"MES_SET", "MES_END", "TSUBO_BENSYO", "GO_NEXT", "CNT_TSUBO"};
    int staffIdx = dComIfGp_evmng_getMyStaffId("TagKf1");
    if (staffIdx != -1) {
        mCutIdx = dComIfGp_evmng_getMyActIdx(staffIdx, cut_name_tbl, 5, TRUE, 0);
        if (mCutIdx == -1) {
            dComIfGp_evmng_cutEnd(staffIdx);
        } else {
            if (dComIfGp_evmng_getIsAddvance(staffIdx)) {
                switch (mCutIdx) {
                case 0: event_talkInit(staffIdx); break;
                case 2: bensyoInit(); break;
                case 3: goto_nextStage(); break;
                case 4: event_cntTsubo(); break;
                }
            }
            bool result;
            switch (mCutIdx) {
            case 0: result = event_mesSet(); break;
            case 1: result = event_mesEnd(); break;
            case 2: result = event_bensyo(); break;
            case 3:
            default: result = true; break;
            }
            if (result) dComIfGp_evmng_cutEnd(staffIdx);
        }
    }
}

/* 00000978-00000A0C       .text event_proc__11daTag_Kf1_cFv */
void daTag_Kf1_c::event_proc() {
    if (dComIfGp_evmng_endCheck("BENSYO")) {
        setStt(2);
    } else {
        bool attention = mCut.getAttnFlag();
        if (mCut.cutProc()) {
            if (!mCut.getAttnFlag()) mCut.setAttnFlag(attention);
        } else {
            privateCut();
        }
    }
}

/* 00000A0C-00000AB8       .text set_action__11daTag_Kf1_cFM11daTag_Kf1_cFPCvPvPv_iPv */
BOOL daTag_Kf1_c::set_action(int (daTag_Kf1_c::*action)(void*), void* arg) {
    if (mAction != action) {
        if (mAction != NULL) {
            mActionState = -1;
            (this->*mAction)(arg);
        }
        mAction = action;
        mActionState = 0;
        (this->*mAction)(arg);
    }
    return TRUE;
}

/* 00000AB8-00000B14       .text wait01__11daTag_Kf1_cFv */
BOOL daTag_Kf1_c::wait01() {
    mOrder = 0;
    if (mInRange && mPotCount != checkPartner()) mOrder = 3;
    return TRUE;
}

/* 00000B14-00000B1C       .text wait02__11daTag_Kf1_cFv */
BOOL daTag_Kf1_c::wait02() {
    return TRUE;
}

/* 00000B1C-00000BE8       .text wait_action1__11daTag_Kf1_cFPv */
int daTag_Kf1_c::wait_action1(void*) {
    if (mActionState == 0) {
        setStt(1);
        mActionState++;
    } else if (mActionState != -1) {
        if (mActionState == 1) {
            partner_srch();
            mActionState = 2;
        }
        mInRange = chkAttention(current.pos);
        switch (mState) {
        case 1: wait01(); break;
        case 2: wait02(); break;
        }
    }
    return 1;
}

/* 00000BE8-00000BF0       .text _draw__11daTag_Kf1_cFv */
BOOL daTag_Kf1_c::_draw() {
    GXColor color = {255, 0, 0, 128};
    return TRUE;
}

/* 00000BF0-00000C68       .text _execute__11daTag_Kf1_cFv */
BOOL daTag_Kf1_c::_execute() {
    checkOrder();
    if (dComIfGp_event_runCheck() && !eventInfo.checkCommandTalk()) event_proc();
    else (this->*mAction)(NULL);
    eventOrder();
    return TRUE;
}

/* 00000C68-00000CBC       .text _delete__11daTag_Kf1_cFv */
BOOL daTag_Kf1_c::_delete() {
    if (l_HIO.mNo >= 0) {
        mDoHIO_deleteChild(l_HIO.mNo);
        l_HIO.mNo = -1;
    }
    return TRUE;
}

/* 00000CBC-00000E98       .text _create__11daTag_Kf1_cFv */
cPhs_State daTag_Kf1_c::_create() {
    cPhs_State phase = cPhs_COMPLEATE_e;
    fopAcM_SetupActor(this, daTag_Kf1_c);
    switch (fopAcM_GetName(this)) {
    case fpcNm_TAG_KF1_e: mType = 0; break;
    default: return cPhs_ERROR_e;
    }
    if (l_HIO.mNo < 0) l_HIO.mNo = mDoHIO_createChild("クタニ焼き監視タグ", &l_HIO);
    if (!createInit()) phase = cPhs_ERROR_e;
    return phase;
}

/* 000010C0-000010E0       .text daTag_Kf1_Create__FP10fopAc_ac_c */
static cPhs_State daTag_Kf1_Create(fopAc_ac_c* i_this) {
    return ((daTag_Kf1_c*)i_this)->_create();
}

/* 000010E0-00001100       .text daTag_Kf1_Delete__FP11daTag_Kf1_c */
static BOOL daTag_Kf1_Delete(daTag_Kf1_c* i_this) {
    return ((daTag_Kf1_c*)i_this)->_delete();
}

/* 00001100-00001120       .text daTag_Kf1_Execute__FP11daTag_Kf1_c */
static BOOL daTag_Kf1_Execute(daTag_Kf1_c* i_this) {
    return ((daTag_Kf1_c*)i_this)->_execute();
}

/* 00001120-00001140       .text daTag_Kf1_Draw__FP11daTag_Kf1_c */
static BOOL daTag_Kf1_Draw(daTag_Kf1_c* i_this) {
    return ((daTag_Kf1_c*)i_this)->_draw();
}

/* 00001140-00001148       .text daTag_Kf1_IsDelete__FP11daTag_Kf1_c */
static BOOL daTag_Kf1_IsDelete(daTag_Kf1_c*) {
    return TRUE;
}

static actor_method_class l_daTag_Kf1_Method = {
    (process_method_func)daTag_Kf1_Create,
    (process_method_func)daTag_Kf1_Delete,
    (process_method_func)daTag_Kf1_Execute,
    (process_method_func)daTag_Kf1_IsDelete,
    (process_method_func)daTag_Kf1_Draw,
};

actor_process_profile_definition g_profile_TAG_KF1 = {
    /* Layer ID     */ fpcLy_CURRENT_e,
    /* List ID      */ 0x0007,
    /* List Prio    */ fpcPi_CURRENT_e,
    /* Proc Name    */ fpcNm_TAG_KF1_e,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(daTag_Kf1_c),
    /* Size Other   */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Draw Prio    */ fpcDwPi_TAG_KF1_e,
    /* Actor SubMtd */ &l_daTag_Kf1_Method,
    /* Status       */ fopAcStts_UNK4000_e | fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ACTOR_e,
    /* Cull Type    */ fopAc_CULLBOX_0_e,
};
