//
// Generated by dtk
// Translation Unit: d_a_obj_msdan.cpp
//

#include "d/dolzel_rel.h" // IWYU pragma: keep
#include "d/actor/d_a_obj_msdan.h"
#include "d/d_com_inf_game.h"
#include "f_op/f_op_actor_mng.h"

const char daObjMsdan::Act_c::M_arcname[] = "Msdan";
const char daObjMsdan::Act_c::M_evname[] = "Msdan";

/* 00000078-000003D4       .text Mthd_Create__Q210daObjMsdan5Act_cFv */
cPhs_State daObjMsdan::Act_c::Mthd_Create() {
    fopAcM_SetupActor(this, Act_c);
    cPhs_State phase = dComIfG_resLoad(&mPhs, M_arcname);
    if (phase == cPhs_COMPLEATE_e) {
        cXyz pos = current.pos;
        csXyz angle = current.angle;
        angle.y += 0x8000;
        if (prm_get_size()) {
            pos.y += 800.0f;
            for (int i = 0; i < 31; i++) {
                pos.x += 50.0f * cM_ssin(current.angle.y);
                pos.z += 50.0f * cM_scos(current.angle.y);
                u32 parameters = (i << 8) + prm_get_swSave() + (prm_get_size() << 16);
                fopAcM_create(fpcNm_Obj_MsdanSub_e, parameters,
                             &pos, fopAcM_GetRoomNo(this), &angle);
            }
        } else {
            pos.y += 400.0f;
            for (int i = 16; i < 31; i++) {
                pos.x += 50.0f * cM_ssin(current.angle.y);
                pos.z += 50.0f * cM_scos(current.angle.y);
                u32 parameters = (i << 8) + prm_get_swSave() + (prm_get_size() << 16);
                fopAcM_create(fpcNm_Obj_MsdanSub_e, parameters,
                             &pos, fopAcM_GetRoomNo(this), &angle);
            }
        }
        if (prm_get_evId() == 0xFF) {
            mEventIdx = dComIfGp_evmng_getEventIdx("Msdan");
        } else {
            mEventIdx = dComIfGp_evmng_getEventIdx(NULL, prm_get_evId());
        }
        int sw = prm_get_swSave();
        if (dComIfGs_isSwitch(sw, home.roomNo)) {
            mState = 3;
        } else {
            mState = 0;
        }
    }
    return phase;
}

/* 000003D4-000005C0       .text Mthd_Execute__Q210daObjMsdan5Act_cFv */
BOOL daObjMsdan::Act_c::Mthd_Execute() {
    switch (mState) {
    case 3:
        break;
    case 0: {
        int sw = prm_get_swSave();
        if (dComIfGs_isSwitch(sw, fopAcM_GetHomeRoomNo(this))) {
            if (prm_get_size()) {
                mState = 3;
            } else if (prm_get_sound()) {
                mState = 3;
            } else if (mEventIdx == -1) {
                mDoAud_seStart(JA_SE_READ_RIDDLE_1);
                mState = 3;
            } else {
                fopAcM_orderOtherEventId(this, mEventIdx);
                mState = 1;
            }
        }
        break;
    }
    case 1:
        if (eventInfo.checkCommandDemoAccrpt()) {
            mState = 2;
            mDoAud_seStart(JA_SE_READ_RIDDLE_1);
        } else {
            fopAcM_orderOtherEventId(this, mEventIdx);
        }
        break;
    case 2:
        if (dComIfGp_evmng_endCheck(mEventIdx)) {
            dComIfGp_event_reset();
            mState = 3;
        }
        break;
    }
    return TRUE;
}

/* 000005C0-000005F0       .text Mthd_Delete__Q210daObjMsdan5Act_cFv */
BOOL daObjMsdan::Act_c::Mthd_Delete() {
    dComIfG_resDeleteDemo(&mPhs, M_arcname);
    return TRUE;
}

namespace daObjMsdan {
namespace {
/* 000005F0-00000610       .text Mthd_Create__Q210daObjMsdan27@unnamed@d_a_obj_msdan_cpp@FPv */
cPhs_State Mthd_Create(void* i_this) {
    return ((daObjMsdan::Act_c*)i_this)->Mthd_Create();
}

/* 00000610-00000630       .text Mthd_Delete__Q210daObjMsdan27@unnamed@d_a_obj_msdan_cpp@FPv */
BOOL Mthd_Delete(void* i_this) {
    return ((daObjMsdan::Act_c*)i_this)->Mthd_Delete();
}

/* 00000630-00000650       .text Mthd_Execute__Q210daObjMsdan27@unnamed@d_a_obj_msdan_cpp@FPv */
BOOL Mthd_Execute(void* i_this) {
    return ((daObjMsdan::Act_c*)i_this)->Mthd_Execute();
}

/* 00000650-00000658       .text Mthd_Draw__Q210daObjMsdan27@unnamed@d_a_obj_msdan_cpp@FPv */
BOOL Mthd_Draw(void*) {
    return TRUE;
}

/* 00000658-00000660       .text Mthd_IsDelete__Q210daObjMsdan27@unnamed@d_a_obj_msdan_cpp@FPv */
BOOL Mthd_IsDelete(void*) {
    return TRUE;
}

static actor_method_class Mthd_Msdan = {
    (process_method_func)Mthd_Create,
    (process_method_func)Mthd_Delete,
    (process_method_func)Mthd_Execute,
    (process_method_func)Mthd_IsDelete,
    (process_method_func)Mthd_Draw,
};
}; // namespace
}; // namespace daObjMsdan

actor_process_profile_definition g_profile_Obj_Msdan = {
    /* Layer ID     */ fpcLy_CURRENT_e,
    /* List ID      */ 0x0003,
    /* List Prio    */ fpcPi_CURRENT_e,
    /* Proc Name    */ fpcNm_Obj_Msdan_e,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(daObjMsdan::Act_c),
    /* Size Other   */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Draw Prio    */ fpcDwPi_Obj_Msdan_e,
    /* Actor SubMtd */ &daObjMsdan::Mthd_Msdan,
    /* Status       */ fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ACTOR_e,
    /* Cull Type    */ fopAc_CULLBOX_CUSTOM_e,
};
