//
// Generated by dtk
// Translation Unit: d_a_obj_search.cpp
//

#include "d/dolzel.h" // IWYU pragma: keep
#include "d/actor/d_a_obj_search.h"
#include "d/actor/d_a_bdk.h"
#include "d/actor/d_a_bk.h"
#include "d/actor/d_a_player.h"
#include "SSystem/SComponent/c_angle.h"
#include "f_pc/f_pc_name.h"
#include "d/d_bg_s_movebg_actor.h"
#include "d/d_bg_w.h"
#include "d/d_cc_d.h"
#include "d/d_com_inf_game.h"
#include "d/d_lib.h"
#include "d/d_particle_name.h"
#include "d/d_path.h"
#include "d/d_s_play.h"
#include "f_op/f_op_actor_mng.h"
#include "JSystem/J3DGraphAnimator/J3DJoint.h"
#include "JSystem/JUtility/JUTAssert.h"
#include "m_Do/m_Do_ext.h"
#include "m_Do/m_Do_lib.h"
#include "m_Do/m_Do_mtx.h"
#include "res/Object/Search.h"
#include "SSystem/SComponent/c_lib.h"
#include "SSystem/SComponent/c_math.h"
#include <math.h>
#include <stdlib.h>
#include <string.h>

#line 1 "d_a_obj_search.cpp"

static dCcD_SrcCps cps_src = {
    // dCcD_SrcGObjInf
    {
        /* Flags             */ 0,
        /* SrcObjAt  Type    */ 0,
        /* SrcObjAt  Atp     */ 0,
        /* SrcObjAt  SPrm    */ 0,
        /* SrcObjTg  Type    */ 0,
        /* SrcObjTg  SPrm    */ 0,
        /* SrcGObjCo  SPrm    */ cCcD_CoSPrm_Set_e | cCcD_CoSPrm_IsOther_e | cCcD_CoSPrm_VsEnemy_e | cCcD_CoSPrm_NoCrr_e,
        /* SrcGObjAt Se      */ 0,
        /* SrcGObjAt HitMark */ dCcG_AtHitMark_None_e,
        /* SrcGObjAt Spl     */ dCcG_At_Spl_UNK0,
        /* SrcGObjAt Mtrl    */ 0,
        /* SrcGObjAt SPrm    */ 0,
        /* SrcGObjTg Se      */ 0,
        /* SrcGObjTg HitMark */ 0,
        /* SrcGObjTg Spl     */ dCcG_Tg_Spl_UNK0,
        /* SrcGObjTg Mtrl    */ 0,
        /* SrcGObjTg SPrm    */ dCcG_TgSPrm_NoHitMark_e,
        /* SrcGObjCo SPrm    */ 0,
    },
    // cM3dGCpsS
    {{
        /* Start  */ {0.0f, 0.0f, 0.0f},
        /* End    */ {0.0f, 0.0f, 0.0f},
        /* Radius */ 50.0f,
    }},
};

const daObj_Search::Act_c::Attr_c daObj_Search::Act_c::m_attr = {
    /* mSkipExecute */ 0,
    /* mSkipDraw    */ 0,
    /* m02          */ 0x14,
    /* m04          */ 16000.0f,
    /* m08          */ 0,
    /* m0A          */ {0, 0, 0, 0, 0, 0},
    /* m10          */ 4000.0f,
    /* m14          */ 0.05f,
    /* m18          */ -0.09870148f,
    /* m1C          */ 0.10170001f,
    /* m20          */ 4.0f,
    /* m24          */ 1,
    /* m25          */ {0, 0, 0},
    /* mCpsR        */ 460.0f,
    /* m2C          */ {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    /* m38          */ 1,
    /* m39          */ 0,
    /* m3A          */ {0, 0},
    /* m3C          */ 0x14,
    /* m3E          */ 0,
    /* m3F          */ {0, 0, 0},
    /* m42          */ 0,
    /* m43          */ 0,
    /* m44          */ 0,
    /* m45          */ 0,
    /* m46          */ 0,
    /* m47          */ 0,
    /* m48          */ {0, 0, 0, 0},
    /* m4C          */ 2000.0f,
    /* m50          */ 0x2D,
    /* m52          */ {0, 0},
    /* m54          */ 600.0f,
    /* m58          */ 1500.0f,
    /* m5C          */ 2000,
    /* m5E          */ 14,
};

const char daObj_Search::Act_c::m_arc_name[] = "Search";

/* 800FDAFC-800FDB1C       .text createHeap_CB__FP10fopAc_ac_c */
static BOOL createHeap_CB(fopAc_ac_c* i_this) {
    return static_cast<daObj_Search::Act_c*>(i_this)->_createHeap();
}

/* 800FDB1C-800FDB8C       .text _createHeap__Q212daObj_Search5Act_cFv */
BOOL daObj_Search::Act_c::_createHeap() {
    if ((u8)searchCreateHeap() == 0) {
        return FALSE;
    }
    if ((u8)beamCreateHeap(0) == 0) {
        return FALSE;
    }
    return (u8)beamCreateHeap(1) ? TRUE : FALSE;
}

/* 800FDB8C-800FDCAC       .text searchCreateHeap__Q212daObj_Search5Act_cFv */
BOOL daObj_Search::Act_c::searchCreateHeap() {
    J3DModelData* modelData = static_cast<J3DModelData*>(dComIfG_getObjectRes(m_arc_name, dRes_INDEX_SEARCH_BDL_S_SEARCH_e));
    JUT_ASSERT(0x39, modelData != 0);
    mpModel = mDoExt_J3DModel__create(modelData, 0x80000, 0x11000022);
    if (mpModel == NULL) {
        return FALSE;
    }
    mpBgW = new dBgW();
    if (mpBgW == NULL) {
        return FALSE;
    }
    if (mpBgW->Set((cBgD_t*)dComIfG_getObjectRes(m_arc_name, dRes_INDEX_SEARCH_DZB_S_BASE_e), cBgW::MOVE_BG_e, &mBgMtx) == TRUE) {
        return FALSE;
    }
    return TRUE;
}

/* 800FDCAC-800FDDBC       .text beamCreateHeap__Q212daObj_Search5Act_cFi */
BOOL daObj_Search::Act_c::beamCreateHeap(int i) {
    static int dzb[] = {
        dRes_INDEX_SEARCH_DZB_S_SEARCH_LIGHTA_e,
        dRes_INDEX_SEARCH_DZB_S_SEARCH_LIGHTB_e,
    };

    J3DModelData* modelData = (J3DModelData*)dComIfG_getObjectRes(m_arc_name, dRes_INDEX_SEARCH_BDL_S_BEAM_e);
    if (modelData == NULL) {
        return FALSE;
    }
    mpBeamModel[i] = mDoExt_J3DModel__create(modelData, 0x80000, 0x11000022);
    if (mpBeamModel[i] == NULL) {
        return FALSE;
    }
    mpBeamBgW[i] = new dBgW();
    if (mpBeamBgW[i] == NULL) {
        return FALSE;
    }
    if (mpBeamBgW[i]->Set((cBgD_t*)dComIfG_getObjectRes(m_arc_name, dzb[i]), cBgW::MOVE_BG_e, &mBeamMtx[i]) == TRUE) {
        return FALSE;
    }
    return TRUE;
}

/* 800FDDBC-800FDE08       .text nodeControl_CB__FP7J3DNodei */
static BOOL nodeControl_CB(J3DNode* node, int calcTiming) {
    if (calcTiming == J3DNodeCBCalcTiming_In) {
        J3DModel* model = j3dSys.getModel();
        daObj_Search::Act_c* i_this = (daObj_Search::Act_c*)model->getUserArea();
        if (i_this != NULL) {
            i_this->_nodeControl(node, model);
        }
    }
    return TRUE;
}

/* 800FDE08-800FE10C       .text _nodeControl__Q212daObj_Search5Act_cFP7J3DNodeP8J3DModel */
void daObj_Search::Act_c::_nodeControl(J3DNode* node, J3DModel* model) {
    J3DJoint* joint = (J3DJoint*)node;
    int jntNo = joint->getJntNo();
    mDoMtx_stack_c::copy(model->getAnmMtx(jntNo));

    s16 diff = mLightAng[0].y - m7B0;
    s16 scaled = (s16)(diff * (1.0f + attr()->m20));
    m7AE = 0x2700;

    switch (jntNo) {
    case S_SEARCH_JNT_LIGHTA_e:
        mDoMtx_XrotM(mDoMtx_stack_c::now, mLightAng[0].y);
        mDoMtx_YrotM(mDoMtx_stack_c::now, mLightAng[0].x);
        break;
    case S_SEARCH_JNT_LIGHTB_e:
        mDoMtx_XrotM(mDoMtx_stack_c::now, mLightAng[1].y);
        mDoMtx_YrotM(mDoMtx_stack_c::now, mLightAng[1].x);
        break;
    case S_SEARCH_JNT_SHAFT_e:
        mDoMtx_YrotM(mDoMtx_stack_c::now, m7AE);
        break;
    case S_SEARCH_JNT_HANDLE_e:
        mDoMtx_YrotM(mDoMtx_stack_c::now, m7AE);
        mDoMtx_XrotM(mDoMtx_stack_c::now, m7AC);
        break;
    }

    if (mMode != MODE_STOP_e) {
        s16 tmp = scaled;
        switch (jntNo) {
        case S_SEARCH_JNT_GEAR_S_e:
            m7AC = (s16)(m7AC + tmp * (2.0f + attr()->m1C));
            mDoMtx_XrotM(mDoMtx_stack_c::now, m7AC);
            break;
        case S_SEARCH_JNT_GEAR_M_e:
            m7AA = (s16)(m7AA - tmp * (1.5f + attr()->m18));
            mDoMtx_XrotM(mDoMtx_stack_c::now, m7AA);
            break;
        case S_SEARCH_JNT_GEAR_L_e:
            m7A8 = (s16)(m7A8 + tmp * (1.0f + attr()->m14));
            mDoMtx_XrotM(mDoMtx_stack_c::now, m7A8);
            break;
        }
    }

    cMtx_copy(mDoMtx_stack_c::get(), J3DSys::mCurrentMtx);
    model->setAnmMtx(jntNo, mDoMtx_stack_c::get());
}

/* 800FE10C-800FE110       .text modeSearchRndInit__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::modeSearchRndInit() {}

/* 800FE110-800FE200       .text modeSearchRnd__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::modeSearchRnd() {
    if (m834 != 0 && attr()->m38 != 0 && player_check()) {
        modeProcInit(MODE_FIND_e);
    }
    m7B2 = mLightAng[0].x;
    m7B4 = mLightAng[1].x;
    m7B0 = mLightAng[0].y;
    mLightAng[0].x = attr()->m08;
    mLightAng[0].y = (s16)(mLightAng[0].y + 16.0f * (1.0f + attr()->m20));
    mLightAng[1].x = -mLightAng[0].x;
    mLightAng[1].y = mLightAng[0].y;
}

/* 800FE200-800FE244       .text modeSearchPathInit__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::modeSearchPathInit() {
    if (!is_path_info()) {
        modeProcInit(MODE_SEARCH_RND_e);
    }
}

/* 800FE244-800FEA6C       .text modeSearchPath__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::modeSearchPath() {
    dLib_pathMove(&mPathPos, &mPathPntIdx, mpPath, (f32)attr()->m02, NULL, NULL);

    if (m834 != 0) {
        fopAc_ac_c* fganon = fopAcM_SearchByName(fpcNm_FGANON_e);
        if (mSwSave != 0xFF && fganon != NULL) {
            bk_class* bk = (bk_class*)fopAcM_SearchByID(mChildId);
            if (bk != NULL) {
                bk->m1224 = m7AC;
            }
            if (attr()->m39 != 0 || m8D0 == 4) {
                modeProcInit(MODE_TO_STOP_e);
                return;
            }
            if (attr()->m3A[0] != 0) {
                daPy_py_c* player = (daPy_py_c*)dComIfGp_getPlayer(0);
                static cXyz pos = cXyz(0.0f, 100.0f, 0.0f);
                cXyz dir = pos;
                dir = (dir + player->current.pos) - mBeamStart[0];
                m7B0 = mLightAng[0].y;
                s16 yaw = cM_atan2s(dir.x, dir.z) - current.angle.y;
                int pitch = cM_atan2s(dir.y, std::sqrtf(dir.x * dir.x + dir.z * dir.z));
                cLib_addCalcAngleS2(&mLightAng[m830].y, yaw, 10, 0x400);
                cLib_addCalcAngleS2(&mLightAng[m830].x, pitch, 10, 0x400);
                return;
            }
            if (m8D0 == 2) {
                daPy_py_c* player = (daPy_py_c*)dComIfGp_getPlayer(0);
                static cXyz pos = cXyz(0.0f, 100.0f, 0.0f);
                cXyz dir = pos;
                dir = (dir + player->current.pos) - mBeamStart[0];
                m7B0 = mLightAng[0].y;
                s16 yaw = cM_atan2s(dir.x, dir.z) - current.angle.y;
                int pitch = cM_atan2s(dir.y, std::sqrtf(dir.x * dir.x + dir.z * dir.z));
                cLib_addCalcAngleS2(&mLightAng[m830].y, yaw, 10, 0x400);
                cLib_addCalcAngleS2(&mLightAng[m830].x, pitch, 10, 0x400);
                return;
            }
            if (m8D0 == 3) {
                static cXyz pos = cXyz(0.0f, 100.0f, 0.0f);
                cXyz dir = pos;
                dir = (dir + fganon->current.pos) - mBeamStart[0];
                m7B0 = mLightAng[0].y;
                s16 yaw = cM_atan2s(dir.x, dir.z) - current.angle.y;
                int pitch = cM_atan2s(dir.y, std::sqrtf(dir.x * dir.x + dir.z * dir.z));
                cLib_addCalcAngleS2(&mLightAng[m830].y, yaw, 10, 0x400);
                cLib_addCalcAngleS2(&mLightAng[m830].x, pitch, 10, 0x400);
                return;
            }
        } else {
            if (attr()->m38 != 0) {
                if (player_check()) {
                    if (dComIfGp_demo_mode() != 1) {
                        m7A0++;
                        if (m7A0 > attr()->m5E) {
                            modeProcInit(MODE_FIND_e);
                            m7A0 = 0;
                        }
                    }
                } else {
                    m7A0 = 0;
                }
            }
        }
    }

    m60C[0] = mPathPos;
    cXyz dir = m60C[0] - mBeamStart[0];
    m7B0 = mLightAng[0].y;
    m7B2 = mLightAng[0].x;
    m7B4 = mLightAng[1].x;
    s16 yaw = cM_atan2s(dir.x, dir.z) - current.angle.y;
    int pitch = cM_atan2s(dir.y, std::sqrtf(dir.x * dir.x + dir.z * dir.z));
    if (attr()->m3E != 0) {
        s16 tgtY = yaw;
        s16 tgtX = pitch;
        cLib_addCalcAngleS2(&mLightAng[0].y, tgtY, 0x1E, 0x400);
        cLib_addCalcAngleS2(&mLightAng[0].x, tgtX, 0x1E, 0x400);
        mLightAng[1].y = mLightAng[0].y;
    } else if (REG12_S(4) == 0) {
        s16 tgtY = yaw;
        s16 tgtX = pitch;
        cLib_addCalcAngleS2(&mLightAng[0].y, tgtY, 0x1E, 0x400);
        cLib_addCalcAngleS2(&mLightAng[0].x, tgtX, 0x1E, 0x400);
        mLightAng[1].y = mLightAng[0].y;
    } else {
        mLightAng[0].y = yaw;
        mLightAng[0].x = pitch;
        mLightAng[1].y = mLightAng[0].y;
    }
    mLightAng[1].x = (s16)(attr()->m3C * DEG2S_CONSTANT);
}

/* 800FEA6C-800FEA80       .text modeStopInit__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::modeStopInit() {
    mLightAng[0].x = 0x2300;
    mLightAng[1].x = -0x2300;
}

/* 800FEA80-800FEA84       .text modeStop__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::modeStop() {}

/* 800FEA84-800FEA88       .text modeToSearchInit__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::modeToSearchInit() {}

/* 800FEA88-800FEB30       .text modeToSearch__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::modeToSearch() {
    bool yawA = false;
    bool yawB = false;
    if (cLib_addCalcAngleS(&mLightAng[0].x, m7B2, 10, 0x200, 0x100) < 0x100) {
        yawA = true;
    }
    if (cLib_addCalcAngleS(&mLightAng[1].x, m7B4, 10, 0x200, 0x100) < 0x100) {
        yawB = true;
    }
    if (yawA && yawB) {
        modeProcInit(MODE_SEARCH_PATH_e);
    }
}

/* 800FEB30-800FEBB4       .text modeToStopInit__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::modeToStopInit() {
    m7B0 = mLightAng[0].y;
    if (dComIfGs_isEventBit(dSv_event_flag_c::UNK_0201)) {
        mDoAud_seStart(JA_SE_OBJ_SEARCH_LIGHT_UP, &eyePos, 0, dComIfGp_getReverb(fopAcM_GetRoomNo(this)));
    }
}

/* 800FEBB4-800FEECC       .text modeToStop__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::modeToStop() {
    bool ang0 = false;
    bool ang1 = false;

    if (!(dComIfGs_isEventBit(dSv_event_flag_c::UNK_0201) && attr()->m42 == 0) && mSwSave == 0xFF) {
        if (eventInfo.checkCommandDemoAccrpt()) {
            m77E = 0xFF;
            int staffId = dComIfGp_evmng_getMyStaffId("Search");
            dEvent_manager_c* evtMgr = dComIfGp_getPEvtManager();
            if (evtMgr->endCheckOld("Search_Light_Up")) {
                dComIfGp_event_reset();
                dComIfGs_onEventBit(dSv_event_flag_c::UNK_0201);
                modeProcInit(MODE_STOP_e);
            } else {
                bk_class* bk = (bk_class*)fopAcM_SearchByID(mChildId);
                if (bk != NULL) {
                    if (bk->m0300[1] < 5) {
                        bk->m0300[1] = 5;
                    }
                }
                char* cutName = evtMgr->getMyNowCutName(staffId);
                if (strcmp(cutName, "BK_FIND") == 0) {
                    evtMgr->cutEnd(staffId);
                }
                if (strcmp(cutName, "LIGHT_UP_SOUND") == 0) {
                    mDoAud_seStart(JA_SE_OBJ_SEARCH_LIGHT_UP, &eyePos, 0, dComIfGp_getReverb(fopAcM_GetRoomNo(this)));
                    evtMgr->cutEnd(staffId);
                }
                if (strcmp(cutName, "LIGHT_UP") == 0) {
                    if (abs(cLib_addCalcAngleS(&mLightAng[0].x, 0x2300, 0x1E, 0x300, 0x10)) < 0x100) {
                        ang0 = true;
                    }
                    if (abs(cLib_addCalcAngleS(&mLightAng[1].x, -0x2300, 0x1E, 0x300, 0x10)) < 0x100) {
                        ang1 = true;
                    }
                    if (ang0 && ang1) {
                        smoke_set(5.0f, 10);
                        evtMgr->cutEnd(staffId);
                    }
                }
            }
        } else {
            fopAcM_orderOtherEvent2(this, "Search_Light_Up", dEvtFlag_NOPARTNER_e, -1);
        }
    } else {
        if (abs(cLib_addCalcAngleS(&mLightAng[0].x, 0x2300, 0x14, 0x200, 0x10)) < 0x100) {
            ang0 = true;
        }
        if (abs(cLib_addCalcAngleS(&mLightAng[1].x, -0x2300, 0x14, 0x200, 0x10)) < 0x100) {
            ang1 = true;
        }
        if (ang0 && ang1) {
            smoke_set(5.0f, 10);
            modeProcInit(MODE_STOP_e);
        }
    }
}

/* 800FEECC-800FEF80       .text modeFindInit__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::modeFindInit() {
    if (mSwSave != 0xFF) {
        modeProcInit(MODE_FIND_2ND_e);
    } else {
        if (m8D0 != 0) {
            dComIfGs_onEventBit(dSv_event_flag_c::UNK_0340);
        }
        if (!eventInfo.checkCommandDemoAccrpt()) {
            mDoAud_seStart(JA_SE_MAJUTOU_ALERM, NULL);
        }
        m7B2 = mLightAng[0].x;
        m7B4 = mLightAng[1].x;
        m7B0 = mLightAng[0].y;
    }
}

/* 800FEF80-800FF44C       .text modeFind__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::modeFind() {
    dComIfGp_evmng_getEventIdx("Search_Light_Find");
    dComIfGp_evmng_getEventIdx("Search_Light_Find_With_Barrel");
    dComIfGp_evmng_getEventIdx("Search_Light_Find_Wall");

    daPy_py_c* player = daPy_getPlayerActorClass();
    player_check();
    mLightInf.mColor.r = attr()->m5C;
    mLightInf.mColor.g = attr()->m5C;

    static cXyz pos = cXyz(0.0f, 100.0f, 0.0f);
    cXyz dir = pos;
    dir = (dir + player->current.pos) - mBeamStart[m830];
    m7B0 = mLightAng[0].y;
    u16 yaw = cM_atan2s(dir.x, dir.z) - current.angle.y;
    s16 pitch = (s16)cM_atan2s(dir.y, std::sqrtf(dir.x * dir.x + dir.z * dir.z));
    if (m830 == 0) {
        mLightAng[1].y = yaw;
    } else {
        yaw += 0x8000;
        pitch = -pitch;
        mLightAng[0].y = yaw;
    }
    cLib_addCalcAngleS2(&mLightAng[m830].y, yaw, 10, 0x400);
    cLib_addCalcAngleS2(&mLightAng[m830].x, pitch, 10, 0x400);

    if (eventInfo.checkCommandDemoAccrpt()) {
        int staffId = dComIfGp_evmng_getMyStaffId("Search");
        if (dComIfGp_evmng_endCheck("Search_Light_Find") || dComIfGp_evmng_endCheck("Search_Light_Find_With_Barrel") ||
            dComIfGp_evmng_endCheck("Search_Light_Find_Wall"))
        {
            mDoAud_seStop(JA_SE_MAJUTOU_ALERM, 0x14);
            if (attr()->m43 != 0) {
                dComIfGp_event_onEventFlag(8);
                modeProcInit(MODE_SEARCH_PATH_e);
            } else {
                dComIfGp_setNextStage("majroom", 0, 0, -1, 0.0f, 0, 1, 0);
            }
        } else {
            if (!dComIfGp_checkPlayerStatus0(0, daPyStts0_UNK1_e) &&
                !dComIfGp_checkPlayerStatus0(0, daPyStts0_HANG_e))
            {
                player->changeOriginalDemo();
                s16 ang = mLightAng[m830].y + current.angle.y;
                if (m830 == 0) {
                    ang += 0x8000;
                }
                s16 tgtAng = ang;
                cLib_addCalcAngleS2(&mPlayerTurnY, tgtAng, 4, 0x400);
                player->setPlayerPosAndAngle(&player->current.pos, mPlayerTurnY);
                if (cLib_distanceAngleS(ang, mPlayerTurnY) < 0x500) {
                    player->cancelOriginalDemo();
                }
            }
            dComIfGp_evmng_cutEnd(staffId);
        }
    } else {
        if (!player->checkPlayerFly()) {
            if (player->checkGrabWear()) {
                fopAcM_orderOtherEvent2(this, "Search_Light_Find_With_Barrel", dEvtFlag_NOPARTNER_e, -1);
            } else if (dComIfGp_checkPlayerStatus0(0, daPyStts0_UNK1_e)) {
                fopAcM_orderOtherEvent2(this, "Search_Light_Find_Wall", dEvtFlag_NOPARTNER_e, -1);
            } else {
                fopAcM_orderOtherEvent2(this, "Search_Light_Find", dEvtFlag_NOPARTNER_e, -1);
            }
        }
    }
}

/* 800FF44C-800FF49C       .text modeFind2ndInit__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::modeFind2ndInit() {
    m7B2 = mLightAng[0].x;
    m7B4 = mLightAng[1].x;
    m7B0 = mLightAng[0].y;
    dComIfGs_onSwitch(mSwSave, dComIfGp_roomControl_getStayNo());
}

/* 800FF49C-800FF7A4       .text modeFind2nd__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::modeFind2nd() {
    daPy_py_c* player = (daPy_py_c*)dComIfGp_getPlayer(0);
    player_check();

    static cXyz pos = cXyz(0.0f, 100.0f, 0.0f);
    cXyz offset = pos;
    offset = (offset + player->current.pos) - mBeamStart[m830];
    m7B0 = mLightAng[0].y;
    s16 yaw = cM_atan2s(offset.x, offset.z) - current.angle.y;
    int angle = yaw;
    s16 pitch = (s16)cM_atan2s(offset.y, std::sqrtf(offset.x * offset.x + offset.z * offset.z));
    bool hit = false;

    BOOL below;
    BOOL above;
    s16 maxP = REG12_S(0) + 0x6590;
    s16 minP = REG12_S(1) - 0x2710;
    below = pitch <= minP;
    above = pitch >= maxP;
    if (above) {
        pitch = cLib_minLimit<s16>(pitch, maxP);
    }
    if (below) {
        pitch = cLib_maxLimit<s16>(pitch, minP);
    }
    if (above || below) {
        hit = true;
    }

    cXyz head = player->getHeadTopPos();
    mLinChk.Set(&mBeamStart[m830], &head, this);
    if (dComIfG_Bgsp()->LineCross(&mLinChk)) {
        hit = true;
    }
    if (hit) {
        modeProcInit(MODE_SEARCH_PATH_e);
    }

    if (m830 == 0) {
        mLightAng[1].y = angle;
    } else {
        angle = yaw + 0x8000;
        pitch = -pitch;
        mLightAng[0].y = angle;
    }
    cLib_addCalcAngleS2(&mLightAng[m830].y, angle, 10, 0x400);
    cLib_addCalcAngleS2(&mLightAng[m830].x, pitch, 10, 0x400);
}

/* 800FF7A4-800FF7A8       .text modeSearchBdkInit__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::modeSearchBdkInit() {}

/* 800FF7A8-800FFE78       .text modeSearchBdk__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::modeSearchBdk() {
    fopAc_ac_c* pBdk;
    if (!fopAcM_SearchByName(fpcNm_BDK_e, &pBdk)) {
        return;
    }
    if (pBdk == NULL) {
        return;
    }

    bdk_class* bdk = (bdk_class*)pBdk;
    f32 radius = REG12_F(0);
    cXyz target = pBdk->current.pos;
    target.y += REG12_F(2);
    bool track = true;

    mDebugFanPos.set(3600.0f, 10000.0f, -3800.0f);
    mDebugCircleRadius = 4000.0f + REG8_F(0);
    mDebugFanRadius = 15000.0f + REG8_F(5);
    mDebugFanSpread = REG8_S(0) + 0x3500;
    mDebugFanAngleY = REG8_S(1);

    f32 mag = (mDebugFanPos - pBdk->current.pos).absXZ();

    mDebugFanOk = dLib_checkActorInFan(mDebugFanPos, pBdk, mDebugFanAngleY, mDebugFanSpread, mDebugFanRadius, 3000.0f);
    if (dLib_checkActorInCircle(mDebugFanPos, pBdk, mDebugCircleRadius, 10000.0f)) {
        mDebugFanOk = 0;
    }

    switch (bdk->mAction) {
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 8:
    case 9:
        if (mDebugFanOk != 0) {
            radius += 3000.0f;
            target.y += 1000.0f;
        } else {
            track = false;
        }
        break;
    case 15:
        track = false;
        break;
    case 0:
    case 1:
    case 7:
        if (mDebugFanOk != 0) {
            radius += 500.0f;
            target.y += 100.0f;
        } else {
            track = false;
        }
        break;
    case 10:
        if (bdk->mState == 8) {
            if (cLib_calcTimer(&mBdkTimer) == 0) {
                track = false;
            } else {
                target = mHoldPos;
            }
        } else if (bdk->mState == 7) {
            mBdkTimer = (int)(cM_rndF(100.0f) + 300.0f + REG8_S(4));
            target = mHoldPos;
        } else if (bdk->mState >= 6) {
            mHoldPos = target;
        } else if (bdk->mState >= 5) {
            radius += 100.0f;
            target.y += 100.0f;
        } else {
            track = false;
        }
        break;
    default:
        track = false;
        break;
    }

    fpc_ProcID id = fopAcM_GetID(this);
    s16 dir = 1;
    if ((id & 1) == 1) {
        dir = -1;
    }

    if (track) {
        cLib_addCalc2(&mCirclePath.mRadius, radius, 0.1f, 100.0f);
        mCirclePath.mWobbleAmplitude = 200.0f + REG12_F(1);
        mCirclePath.mAngleSpeed = (REG12_S(0) + 0x150) * dir;
        mCirclePath.mTranslation = target;
        dLib_setCirclePath(&mCirclePath);

        static cXyz pos = cXyz(0.0f, 100.0f, 0.0f);
        cXyz aim = pos;
        aim = (aim + mCirclePath.mPos) - mBeamStart[0];
        m7B0 = mLightAng[0].y;
        s16 yaw = cM_atan2s(aim.x, aim.z) - current.angle.y;
        int pitch = cM_atan2s(aim.y, std::sqrtf(aim.x * aim.x + aim.z * aim.z));
        s16 tgtY = yaw;
        s16 tgtX = pitch;
        cLib_addCalcAngleS2(&mLightAng[0].y, tgtY, 10, 0x100);
        cLib_addCalcAngleS2(&mLightAng[0].x, tgtX, 10, 0x100);
        mLightAng[1].y = mLightAng[0].y;
        mLightAng[1].x = -mLightAng[0].x;
    } else {
        static cXyz pos = cXyz(0.0f, 100.0f, 0.0f);
        cXyz offset = pos;
        (void)offset;

        s16 pitch;
        if (mSearchSide == 1) {
            pitch = REG8_S(7) + 0x3400;
        } else {
            pitch = REG8_S(8) + 0x2600;
        }
        if (cLib_calcTimer(&mIdleTimer) == 0) {
            mIdleTimer = (int)(cM_rndF(60.0f + REG8_F(5)) + (REG8_S(2) + 0x3C));
            if (mSearchSide == 1) {
                mSearchSide = -1;
            } else {
                mSearchSide = 1;
            }
        }
        m7B0 = mLightAng[0].y;
        s16 tgtX = pitch;
        cLib_addCalcAngleS2(&mLightAng[0].x, tgtX, 0x14, 0x20);
        mLightAng[1].x = -mLightAng[0].x;
    }
}

/* 800FFE78-80100080       .text modeProc__Q212daObj_Search5Act_cFQ312daObj_Search5Act_c6Proc_ei */
void daObj_Search::Act_c::modeProc(daObj_Search::Act_c::Proc_e proc, int newMode) {
    typedef void (Act_c::*mode_func_t)();
    struct mode_entry_t {
        mode_func_t init;
        mode_func_t run;
        const char* name;
    };

    static mode_entry_t mode_tbl[] = {
        {&Act_c::modeSearchRndInit, &Act_c::modeSearchRnd, "MODE_SEARCH_RND"},
        {&Act_c::modeSearchPathInit, &Act_c::modeSearchPath, "MODE_SEARCH_PATH"},
        {&Act_c::modeStopInit, &Act_c::modeStop, "MODE_STOP"},
        {&Act_c::modeToSearchInit, &Act_c::modeToSearch, "MODE_TO_SEARCH"},
        {&Act_c::modeToStopInit, &Act_c::modeToStop, "MODE_TO_STOP"},
        {&Act_c::modeFindInit, &Act_c::modeFind, "MODE_FIND"},
        {&Act_c::modeFind2ndInit, &Act_c::modeFind2nd, "MODE_FIND_2ND"},
        {&Act_c::modeSearchBdkInit, &Act_c::modeSearchBdk, "MODE_SEARCH_BDK"},
    };

    if (proc == PROC_INIT_e) {
        mMode = newMode;
        (this->*mode_tbl[mMode].init)();
    } else if (proc == PROC_EXEC_e) {
        (this->*mode_tbl[mMode].run)();
    }
}

/* 80100080-801001C4       .text __ct__Q212daObj_Search5Bgc_cFv */
daObj_Search::Bgc_c::Bgc_c() {}

/* 801001C4-801002D4       .text wall_pos__Q212daObj_Search5Bgc_cFPCQ212daObj_Search5Act_cP4cXyzP4cXyzPbPf */
void daObj_Search::Bgc_c::wall_pos(const daObj_Search::Act_c* actor, cXyz* i_start, cXyz* i_end, bool* i_hit, float* i_dot) {
    mLinChk.Set(i_start, i_end, (fopAc_ac_c*)actor);
    if (dComIfG_Bgsp()->LineCross(&mLinChk)) {
        cM3dGPla* pla = dComIfG_Bgsp()->GetTriPla(mLinChk.GetBgIndex(), mLinChk.GetPolyIndex());
        cXyz n = (*i_end - *i_start).normZP();
        *i_dot = n.getDotProduct(pla->mNormal);
        mWallPos = mLinChk.GetCross();
        *i_end = mWallPos;
        *i_hit = true;
    } else {
        *i_hit = false;
    }
}

bool daObj_Search::Act_c::m_find_flag;

/* 801002D4-801002E0       .text attr__Q212daObj_Search5Act_cCFv */
const daObj_Search::Act_c::Attr_c* daObj_Search::Act_c::attr() const {
    return &m_attr;
}

/* 801002E0-8010035C       .text SetArgData__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::SetArgData() {
    u32 param = fopAcM_GetParam(this);
    m7E2 = param >> 24;
    mPathId = param >> 16;
    mScaleType = param;
    m8D0 = param >> 8;
    if (m8D0 == 0xFF) {
        m8D0 = 0;
    }
    if (mScaleType == 0xFF) {
        scale.setall(1.0f);
    } else if (mScaleType == 1) {
        scale.setall(1.27f);
    }
    mSwSave = (home.angle.x >> 8) & 0xFF;
}

/* 8010035C-8010071C       .text CreateInit__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::CreateInit() {
    set_path_info();
    mCullBeamA = 0;
    mCullBeamB = 0;
    mCullBase = 0;
    fopAcM_SetMtx(this, mpBeamModel[0]->getBaseTRMtx());
    fopAcM_setCullSizeBox(this, -1000.0f, 0.0f, -1000.0f, 1000.0f, 1500.0f, 1000.0f);
    mpBeamBgW[0]->SetCrrFunc(dBgS_MoveBGProc_Typical);
    mpBeamBgW[1]->SetCrrFunc(dBgS_MoveBGProc_Typical);
    mpBgW->SetCrrFunc(dBgS_MoveBGProc_Typical);
    dComIfG_Bgsp()->Regist(mpBeamBgW[0], this);
    dComIfG_Bgsp()->Regist(mpBeamBgW[1], this);
    dComIfG_Bgsp()->Regist(mpBgW, this);

    mStts[0].Init(0xFF, 0xFF, this);
    mCps[0].Set(cps_src);
    mCps[0].SetStts(&mStts[0]);
    mCps[0].SetStartEnd(current.pos, current.pos);
    mCps[0].SetR(m_attr.mCpsR);
    mStts[1].Init(0xFF, 0xFF, this);
    mCps[1].Set(cps_src);
    mCps[1].SetStts(&mStts[1]);
    mCps[1].SetStartEnd(current.pos, current.pos);
    mCps[1].SetR(m_attr.mCpsR);

    set_mtx_base();
    set_moveBG_mtx_base();
    mpModel->setUserArea((u32)this);
    J3DModelData* modelData = mpModel->getModelData();
    for (u16 i = 0; i < modelData->getJointNum(); i++) {
        switch (i) {
        case 1:
        case 2:
        case 3:
        case 4:
        case 5:
        case 6:
        case 7:
            modelData->getJointNodePointer(i)->setCallBack(nodeControl_CB);
            break;
        }
    }
    mpModel->calc();

    if (is_path_info()) {
        mpPath = dPath_GetRoomPath(mPathId, fopAcM_GetRoomNo(this));
        dLib_pathMove(&mPathPos, &mPathPntIdx, mpPath, (f32)m_attr.m02, NULL, NULL);
        m60C[0] = mPathPos;
        cXyz dir = m60C[0] - mBeamStart[0];
        m7B0 = mLightAng[0].y;
        m7B2 = mLightAng[0].x;
        m7B4 = mLightAng[1].x;
        s16 yaw = cM_atan2s(dir.x, dir.z) - current.angle.y;
        s16 pitch = cM_atan2s(dir.y, std::sqrtf(dir.x * dir.x + dir.z * dir.z));
        mLightAng[0].y = yaw;
        mLightAng[0].x = pitch;
        mLightAng[1].y = mLightAng[0].y;
    }
    if (m8D0 == 6) {
        mLightAng[0].x = 0x4000;
        mLightAng[1].x = -mLightAng[0].x;
    }
    set_mtx_light_A();
    set_mtx_light_B();
    set_moveBG_mtx_light_A();
    set_moveBG_mtx_light_B();
    m7A0 = 0;
}

/* 8010071C-80100B08       .text _create__Q212daObj_Search5Act_cFv */
cPhs_State daObj_Search::Act_c::_create() {
    fopAcM_SetupActor(this, Act_c);
    cPhs_State phase = dComIfG_resLoad(&mPhase, m_arc_name);
    if (phase == cPhs_COMPLEATE_e) {
        SetArgData();
        if (!fopAcM_entrySolidHeap(this, createHeap_CB, 0x4620)) {
            return cPhs_ERROR_e;
        }
        CreateInit();
        mBeamStart[0] = current.pos;
        mBeamStart[1] = current.pos;
        if (m8D0 == 6) {
            modeProcInit(MODE_SEARCH_BDK_e);
        } else if (m8D0 == 5) {
            m860 = 1;
            modeProcInit(MODE_STOP_e);
        } else if (is_path_info()) {
            cXyz one(1.0f, 1.0f, 1.0f);
            m60C[0] = mPathPos;
            m60C[1] = mBeamStart[1] + one;
            if (dComIfGs_isSwitch(m7E2, dComIfGp_roomControl_getStayNo())) {
                mBkControl = false;
                modeProcInit(MODE_STOP_e);
            } else {
                mBkControl = true;
                modeProcInit(MODE_SEARCH_PATH_e);
                set_mtx_light_A();
                set_mtx_light_B();
                cXyz dir = m60C[0] - mBeamStart[0];
                s16 yaw = cM_atan2s(dir.x, dir.z) - current.angle.y;
                s16 pitch = cM_atan2s(dir.y, std::sqrtf(dir.x * dir.x + dir.z * dir.z));
                mLightAng[0].y = yaw;
                mLightAng[0].x = pitch;
                mLightAng[1].y = mLightAng[0].y;
            }
        } else {
            cXyz one(1.0f, 1.0f, 1.0f);
            m60C[0] = mBeamStart[0] + one;
            m60C[1] = mBeamStart[1] + one;
            modeProcInit(MODE_STOP_e);
        }
        mBeamEnd[0] = m60C[0];
        mBeamEnd[1] = m60C[1];
        dKy_plight_set(&mLightInf);
        mLightInf.mPos = current.pos;
        mLightInf.mColor.r = 0;
        mLightInf.mColor.g = 0;
        mLightInf.mColor.b = 0;
        mLightInf.mPower = 0.0f;
        mLightInf.mFluctuation = 0.0f;
        if (m8D0 == 5) {
            m77E = 0;
        } else {
            f32 time = dComIfGs_getTime();
            if (time < 240.0f && time > 60.0f) {
                m77E = 0;
            } else {
                m77E = 0xFF;
            }
        }
        m82C = 0xEB;
        m82D = 0x7D;
        _execute();
        _execute();
    }
    return phase;
}

/* 80100F9C-801010C4       .text smoke_set__Q212daObj_Search5Act_cFfi */
void daObj_Search::Act_c::smoke_set(float rate, int timer) {
    mSmokePos = m600;
    mSmokeRot.set(0, 0, 0);
    if (mSmokeCb.getEmitter() == NULL) {
        dComIfGp_particle_setToon(dPa_name::ID_AK_JT_ELEMENTSMOKE00, &mSmokePos, &mSmokeRot, NULL, 0xB9, &mSmokeCb, fopAcM_GetRoomNo(this));
    }
    if (mSmokeCb.getEmitter() != NULL) {
        mSmokeCb.getEmitter()->setRate(rate);
        mSmokeCb.getEmitter()->setSpread(1.0f);
        f32 dyn = 2.5f + REG12_F(10);
        JGeometry::TVec3<f32> dynScale(dyn, dyn, dyn);
        mSmokeCb.getEmitter()->setGlobalScale(dynScale);
        f32 ptcl = 3.5f + REG12_F(11);
        JGeometry::TVec3<f32> ptclScale(ptcl, ptcl, ptcl);
        mSmokeCb.getEmitter()->setGlobalParticleScale(ptclScale);
    }
    mSmokeTimer = timer;
}

/* 801010C4-801013AC       .text _execute__Q212daObj_Search5Act_cFv */
BOOL daObj_Search::Act_c::_execute() {
    if (m_attr.mSkipExecute) {
        return TRUE;
    }
    if (cLib_calcTimer(&mSmokeTimer) == 0) {
        mSmokeCb.remove();
    }
    if (m8D0 != 6 && m8D0 != 5) {
        bk_class* bk = (bk_class*)fopAcM_SearchByID(mChildId);
        if (bk != NULL) {
            m850 = bk->m02B7;
        } else if (m850 != 0xFF && !dComIfGs_isSwitch(m850, dComIfGp_roomControl_getStayNo())) {
            dComIfGs_onSwitch(m850, dComIfGp_roomControl_getStayNo());
        }
    }
    eyePos = current.pos;
    if ((s16)abs(mLightAng[0].y - m7B0) != 0 && mMode != MODE_STOP_e) {
        fopAcM_seStart(this, JA_SE_OBJ_SEARCH_LIGHT, 0);
    }
    mpModel->calc();
    cXyz src;
    cXyz unused(0.0f, 0.0f, 0.0f);
    src.set(0.0f, 0.0f, 0.0f);
    mDoMtx_stack_c::copy(mpModel->getAnmMtx(S_SEARCH_JNT_LIGHTA_e));
    mDoMtx_stack_c::multVec(&src, &m600);
    set_mtx_light_A();
    set_mtx_light_B();
    m7A4++;
    if (m7A4 >= 4) {
        m7A4 = 0;
    }
    f32 time = dComIfGs_getTime();
    if (time < 240.0f && time > 60.0f) {
        m834 = 0;
    } else if (m860) {
        m834 = 0;
    } else {
        m834 = 1;
    }
    if (m834) {
        cLib_chaseS(&m77E, 0xFF, REG12_S(0) + 0x14);
    } else {
        cLib_chaseS(&m77E, 0, REG12_S(0) + 0x14);
        mLightInf.mPower = 0.0f;
    }
    fopAc_ac_c* actor = fopAcM_SearchByName(fpcNm_FGANON_e);
    if (mSwSave == 0xFF || actor == NULL) {
        if (m8D0 != 5) {
            check_bk_control();
        }
    }
    modeProc(PROC_EXEC_e, 8);
    bg_check();
    return TRUE;
}

/* 801013AC-80101464       .text check_bk_control__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::check_bk_control() {
    bk_class* bk = (bk_class*)fopAcM_SearchByID(mChildId);
    if (bk != NULL) {
        m860 = 0;
        bk->m1224 = m7AC;
        if (mBkControl == true) {
            if (mMode == MODE_TO_STOP_e || mMode == MODE_STOP_e) {
                modeProcInit(MODE_TO_SEARCH_e);
                return;
            }
        }
        if (mBkControl == false) {
            if (mMode != MODE_TO_STOP_e && mMode != MODE_STOP_e) {
                modeProcInit(MODE_TO_STOP_e);
            }
        }
    }
}

/* 80101464-801014E4       .text set_mtx_base__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::set_mtx_base() {
    mpModel->setBaseScale(scale);
    mDoMtx_stack_c::transS(current.pos);
    mDoMtx_YrotM(mDoMtx_stack_c::now, current.angle.y);
    mpModel->setBaseTRMtx(mDoMtx_stack_c::now);
}

/* 801014E4-801018A8       .text set_mtx_light_A__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::set_mtx_light_A() {
    cXyz srcStart(0.0f, 0.0f, 0.0f);
    cXyz srcEnd(0.0f, 0.0f, m_attr.m04);
    mDoMtx_stack_c::copy(mpModel->getAnmMtx(S_SEARCH_JNT_LIGHTA_e));
    mDoMtx_stack_c::transM(1004.0f, 376.0f, 1111.0f);
    mDoMtx_XYZrotM(mDoMtx_stack_c::now, 0, -0xC8, 0);
    mDoMtx_stack_c::multVec(&srcStart, &mBeamStart[0]);
    if (m7A4 == setID % 4 || m_attr.m24 != 0) {
        f32 dot = 0.0f;
        mDoMtx_stack_c::multVec(&srcEnd, &mBeamEnd[0]);
        if (m_attr.m3E != 0 || mMode != MODE_FIND_e) {
            mBgc.wall_pos(this, &mBeamStart[0], &mBeamEnd[0], &mWallHit[0], &dot);
        }
        f32 dist = mBeamStart[0].abs(mBeamEnd[0]);
        if (setID == 0) {
            if (mWallHit[0]) {
                f32 adj = 1800.0f * (1.02f + dot);
                if (m8D0 == 6) {
                    adj = -(1.02f + dot) * (500.0f + m_attr.m10 - REG12_F(0));
                }
                dist += adj;
                cXyz n = (mBeamEnd[0] - mBeamStart[0]).normZP();
                mBeamEnd[0] = mBeamEnd[0] + n * adj;
            }
        } else if (mWallHit[0]) {
            f32 adj = (1.02f + dot) * m_attr.m10;
            if (m8D0 == 6) {
                adj = -(1.02f + dot) * (REG12_F(0) + (6500.0f + m_attr.m10));
            }
            dist += adj;
            cXyz n = (mBeamEnd[0] - mBeamStart[0]).normZP();
            mBeamEnd[0] = mBeamEnd[0] + n * adj;
        }
        m65C = dist;
        m654 = m65C;
    }
    mDoMtx_XYZrotM(mDoMtx_stack_c::now, 0, 0, 0xC80);
    mDoMtx_stack_c::scaleM(scale.x, scale.y, 0.0001043f * m654);
    mpBeamModel[0]->setBaseTRMtx(mDoMtx_stack_c::now);
    mDoMtx_copy(mDoMtx_stack_c::now, mAlphaMtx[0]);
}

/* 801018A8-80101BAC       .text set_mtx_light_B__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::set_mtx_light_B() {
    cXyz srcStart;
    cXyz srcEnd;
    cXyz n;
    cXyz unused0(0.0f, 0.0f, 0.0f);
    srcStart.set(0.0f, 0.0f, 0.0f);
    cXyz tmpEnd(0.0f, 0.0f, m_attr.m04);
    srcEnd = tmpEnd;
    mDoMtx_stack_c::copy(mpModel->getAnmMtx(S_SEARCH_JNT_LIGHTB_e));
    mDoMtx_stack_c::transM(742.0f, -402.0f, -1010.0f);
    mDoMtx_XYZrotM(mDoMtx_stack_c::now, -0x8000, 0xC8, 0);
    mDoMtx_stack_c::multVec(&srcStart, &mBeamStart[1]);
    if (m7A4 == setID % 4 || m_attr.m24 != 0) {
        f32 dot = 0.0f;
        mDoMtx_stack_c::multVec(&srcEnd, &mBeamEnd[1]);
        if (m_attr.m3E != 0 || mMode != MODE_FIND_e) {
            mBgc.wall_pos(this, &mBeamStart[1], &mBeamEnd[1], &mWallHit[1], &dot);
        }
        f32 dist = mBeamStart[1].abs(mBeamEnd[1]);
        if (mWallHit[1]) {
            f32 adj = (1.02f + dot) * m_attr.m10;
            if (m8D0 == 6) {
                adj = -(1.02f + dot) * (REG12_F(0) + (6500.0f + m_attr.m10));
            }
            dist += adj;
            n = (mBeamEnd[1] - mBeamStart[1]).normZP();
            mBeamEnd[1] = mBeamEnd[1] + n * adj;
        }
        m660 = dist;
        m658 = m660;
    }
    mDoMtx_XYZrotM(mDoMtx_stack_c::now, 0, 0, 0xC80);
    mDoMtx_stack_c::scaleM(scale.x, scale.y, 0.0001043f * m658);
    mpBeamModel[1]->setBaseTRMtx(mDoMtx_stack_c::now);
    mDoMtx_copy(mDoMtx_stack_c::now, mAlphaMtx[1]);
}

/* 80101BAC-80101C30       .text set_moveBG_mtx_base__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::set_moveBG_mtx_base() {
    mpModel->setBaseScale(scale);
    mDoMtx_stack_c::transS(current.pos);
    mDoMtx_YrotM(mDoMtx_stack_c::now, current.angle.y);
    mDoMtx_copy(mDoMtx_stack_c::now, mBgMtx);
    mpBgW->Move();
}

/* 80101C30-80101CB0       .text set_moveBG_mtx_light_A__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::set_moveBG_mtx_light_A() {
    mDoMtx_stack_c::copy(mpModel->getAnmMtx(S_SEARCH_JNT_LIGHTA_e));
    mDoMtx_XYZrotM(mDoMtx_stack_c::now, 0, 0, -0x4000);
    mDoMtx_stack_c::transM(40.0f, -270.0f, 30.0f);
    mDoMtx_copy(mDoMtx_stack_c::now, mBeamMtx[0]);
    mpBeamBgW[0]->Move();
}

/* 80101CB0-80101D30       .text set_moveBG_mtx_light_B__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::set_moveBG_mtx_light_B() {
    mDoMtx_stack_c::copy(mpModel->getAnmMtx(S_SEARCH_JNT_LIGHTB_e));
    mDoMtx_XYZrotM(mDoMtx_stack_c::now, 0, 0, -0x4000);
    mDoMtx_stack_c::transM(45.0f, -270.0f, 35.0f);
    mDoMtx_copy(mDoMtx_stack_c::now, mBeamMtx[1]);
    mpBeamBgW[1]->Move();
}

/* 80101D30-80101D94       .text bg_check__Q212daObj_Search5Act_cFv */
void daObj_Search::Act_c::bg_check() {
    if (fopAcM_searchActorDistance(this, dComIfGp_getPlayer(0)) > 2000.0f || mCullBase != 0) {
        return;
    }
    set_moveBG_mtx_light_A();
    set_moveBG_mtx_light_B();
}

/* 80101D94-8010234C       .text player_check__Q212daObj_Search5Act_cFv */
bool daObj_Search::Act_c::player_check() {
    daPy_py_c* player = daPy_getPlayerActorClass();
    cXyz diff;
    diff = player->current.pos - mBeamStart[0];
    f32 distA = diff.abs();
    diff = player->current.pos - mBeamStart[1];
    f32 distB = diff.abs();

    mCps[0].SetStartEnd(mBeamStart[0], mBeamEnd[0]);
    mCps[0].SetR(m_attr.mCpsR);
    dComIfG_Ccsp()->Set(&mCps[0]);
    if (mCps[0].ChkCoHit()) {
        fopAc_ac_c* hit = mCps[0].GetCoHitAc();
        cXyz toHit;
        toHit = hit->current.pos - mBeamStart[0];
        cXyz n;
        cXyz beam;
        beam = mBeamEnd[0] - mBeamStart[0];
        n = beam.normZP();
        f32 t = VECDotProduct(&n, &toHit) - 250.0f;
        mLightInf.mPos = mBeamStart[0] + n * t;
        mLightInf.mColor.r = m_attr.m50;
        mLightInf.mColor.g = m_attr.m50;
        mLightInf.mPower = m_attr.m54;
        if (fopAcM_GetName(hit) == fpcNm_PLAYER_e) {
            if (distA < 2000.0f || distB < 2000.0f) {
                return false;
            }
            if (!(std::fabsf(player->speedF) < 0.1f && player->checkGrabWear())) {
                return true;
            }
        }
    }

    mCps[1].SetStartEnd(mBeamStart[1], mBeamEnd[1]);
    mCps[1].SetR(m_attr.mCpsR);
    dComIfG_Ccsp()->Set(&mCps[1]);
    if (mCps[1].ChkCoHit()) {
        fopAc_ac_c* hit = mCps[1].GetCoHitAc();
        cXyz toHit;
        toHit = hit->current.pos - mBeamStart[1];
        cXyz n;
        cXyz beam;
        beam = mBeamEnd[1] - mBeamStart[1];
        n = beam.normZP();
        f32 t = VECDotProduct(&n, &toHit) - 250.0f;
        mLightInf.mPos = mBeamStart[1] + n * t;
        mLightInf.mColor.r = m_attr.m50;
        mLightInf.mColor.g = m_attr.m50;
        mLightInf.mPower = m_attr.m54;
        if (distA < 2000.0f || distB < 2000.0f) {
            return false;
        }
        if (!(std::fabsf(player->speedF) < 0.1f && player->checkGrabWear())) {
            return true;
        }
    }

    if (!mCps[0].ChkCoHit() && !mCps[1].ChkCoHit()) {
        cXyz toPt;
        toPt = m60C[0] - mBeamStart[0];
        cXyz n;
        cXyz beam;
        beam = mBeamEnd[0] - mBeamStart[0];
        n = beam.normZP();
        f32 t = VECDotProduct(&n, &toPt) - 250.0f;
        mLightInf.mPos = mBeamStart[0] + n * t;
        mLightInf.mColor.r = m_attr.m50;
        mLightInf.mColor.g = m_attr.m50;
        mLightInf.mPower = m_attr.m54;
    }
    return false;
}

/* 8010234C-80102384       .text set_path_info__Q212daObj_Search5Act_cFv */
bool daObj_Search::Act_c::set_path_info() {
    if (mPathId != 0xFF) {
        return dLib_pathInfo(&mpPath, mPathId);
    }
    return false;
}

/* 80102384-80102398       .text is_path_info__Q212daObj_Search5Act_cFv */
bool daObj_Search::Act_c::is_path_info() {
    return mPathId != 0xFF;
}

/* 80102398-801026F8       .text _draw__Q212daObj_Search5Act_cFv */
BOOL daObj_Search::Act_c::_draw() {
    if (m_attr.mSkipDraw) {
        return TRUE;
    }

    if (mMode != MODE_TO_STOP_e || mMode != MODE_FIND_e) {
        mDoLib_clipper::changeFar(1000000.0f);
        if (m_attr.m44 == 0) {
            mCullBase = fopAcM_checkCullingBox(mpModel->getBaseTRMtx(), -1000.0f, 0.0f, -1000.0f, 1000.0f, 1500.0f, 1000.0f);
        }
        if (m_attr.m45 == 0) {
            mCullBeamA = fopAcM_checkCullingBox(mpBeamModel[0]->getBaseTRMtx(), -600.0f, -600.0f, -100.0f, 600.0f, 600.0f, 9585.62f);
        }
        if (m_attr.m46 == 0) {
            mCullBeamB = fopAcM_checkCullingBox(mpBeamModel[1]->getBaseTRMtx(), -600.0f, -600.0f, -100.0f, 600.0f, 600.0f, 9585.62f);
        }
        mDoLib_clipper::resetFar();
    }

    if (mCullBase == 0) {
        if (mScaleType == 1) {
            g_env_light.settingTevStruct(TEV_TYPE_BG0, &current.pos, &tevStr);
            tevStr.mColorC0 = g_env_light.mActorC0;
            tevStr.mColorK0.r = g_env_light.mActorK0.r;
            tevStr.mColorK0.g = g_env_light.mActorK0.g;
            tevStr.mColorK0.b = g_env_light.mActorK0.b;
        } else {
            g_env_light.settingTevStruct(TEV_TYPE_ACTOR, &current.pos, &tevStr);
        }
        g_env_light.setLightTevColorType(mpModel, &tevStr);
        mDoExt_modelEntryDL(mpModel);
    }

    if (mCullBeamA == 0) {
        mDoExt_modelUpdateDL(mpBeamModel[0]);
        if (m77E > 0x80) {
            dComIfGd_setAlphaModel(dDlst_alphaModel_c::TYPE_SEARCHLIGHT, mAlphaMtx[0], 0x20);
            dComIfGd_setAlphaModelColor((GXColor){m82C, m82D});
        }
    }

    if (mCullBeamB == 0) {
        mDoExt_modelUpdateDL(mpBeamModel[1]);
        if (m77E > 0x80) {
            dComIfGd_setAlphaModel(dDlst_alphaModel_c::TYPE_SEARCHLIGHT, mAlphaMtx[1], 0x20);
            dComIfGd_setAlphaModelColor((GXColor){m82C, m82D});
        }
    }

    J3DGXColor* kcolor = mpBeamModel[0]->getModelData()->getMaterialNodePointer(0)->getTevBlock()->getTevKColor(0);
    kcolor->mColor.a = m77E;

    if (m_attr.m47 != 0) {
        static const GXColor color_ok = {0x00, 0xFF, 0x00, 0x80};
        static const GXColor color_ng = {0xFF, 0x00, 0x00, 0x80};
        GXColor color = color_ng;
        if (mDebugFanOk != 0) {
            color = color_ok;
        }
        dLib_debugDrawFan(mDebugFanPos, mDebugFanAngleY, mDebugFanSpread, mDebugFanRadius, color);
    }
    return TRUE;
}

/* 801026F8-8010283C       .text _delete__Q212daObj_Search5Act_cFv */
BOOL daObj_Search::Act_c::_delete() {
    dKy_plight_cut(&mLightInf);
    if (mpBeamBgW[0] != NULL && mpBeamBgW[0]->ChkUsed()) {
        dComIfG_Bgsp()->Release(mpBeamBgW[0]);
    }
    if (mpBeamBgW[1] != NULL && mpBeamBgW[1]->ChkUsed()) {
        dComIfG_Bgsp()->Release(mpBeamBgW[1]);
    }
    if (mpBgW != NULL && mpBgW->ChkUsed()) {
        dComIfG_Bgsp()->Release(mpBgW);
    }
    dComIfG_resDelete(&mPhase, m_arc_name);
    mSmokeCb.remove();
    if (mDoAud_checkSePlaying(JA_SE_MAJUTOU_ALERM)) {
        mDoAud_seStop(JA_SE_MAJUTOU_ALERM, 0);
    }
    return TRUE;
}

/* 8010283C-80102844       .text _isdelete__Q212daObj_Search5Act_cFv */
BOOL daObj_Search::Act_c::_isdelete() {
    return TRUE;
}

/* 80102844-80102864       .text Create__Q212daObj_Search4MthdFPv */
cPhs_State daObj_Search::Mthd::Create(void* i_this) {
    return static_cast<Act_c*>(i_this)->_create();
}

/* 80102864-80102884       .text Delete__Q212daObj_Search4MthdFPv */
BOOL daObj_Search::Mthd::Delete(void* i_this) {
    return static_cast<Act_c*>(i_this)->_delete();
}

/* 80102884-801028A4       .text Execute__Q212daObj_Search4MthdFPv */
BOOL daObj_Search::Mthd::Execute(void* i_this) {
    return static_cast<Act_c*>(i_this)->_execute();
}

/* 801028A4-801028C4       .text Draw__Q212daObj_Search4MthdFPv */
BOOL daObj_Search::Mthd::Draw(void* i_this) {
    return static_cast<Act_c*>(i_this)->_draw();
}

/* 801028C4-801028E4       .text IsDelete__Q212daObj_Search4MthdFPv */
BOOL daObj_Search::Mthd::IsDelete(void* i_this) {
    return static_cast<Act_c*>(i_this)->_isdelete();
}

actor_method_class daObj_Search::Mthd::Table = {
    (process_method_func)daObj_Search::Mthd::Create,
    (process_method_func)daObj_Search::Mthd::Delete,
    (process_method_func)daObj_Search::Mthd::Execute,
    (process_method_func)daObj_Search::Mthd::IsDelete,
    (process_method_func)daObj_Search::Mthd::Draw,
};

actor_process_profile_definition g_profile_OBJ_SEARCH = {
    /* Layer ID     */ fpcLy_CURRENT_e,
    /* List ID      */ 0x0003,
    /* List Prio    */ fpcPi_CURRENT_e,
    /* Proc Name    */ fpcNm_OBJ_SEARCH_e,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(daObj_Search::Act_c),
    /* Size Other   */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Draw Prio    */ fpcDwPi_OBJ_SEARCH_e,
    /* Actor SubMtd */ &daObj_Search::Mthd::Table,
    /* Status       */ fopAcStts_UNK4000_e | fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ACTOR_e,
    /* Cull Type    */ fopAc_CULLBOX_CUSTOM_e,
};
