//
// Generated by dtk
// Translation Unit: d_a_obj_firewall.cpp
//

#include "d/dolzel_rel.h" // IWYU pragma: keep
#include "d/actor/d_a_obj_firewall.h"
#include "d/d_com_inf_game.h"
#include "d/d_s_play.h"
#include "d/actor/d_a_player.h"
#include "JSystem/JUtility/JUTAssert.h"
#include "m_Do/m_Do_mtx.h"
#include "m_Do/m_Do_audio.h"
#include "res/Object/Yswdr00.h"
#include "m_Do/m_Do_hostIO.h"

namespace {
const char l_arcname[] = "Yswdr00";
const dCcD_SrcCyl l_cyl_src = {
    {0, 0x200, 1, 7, 0, 0, 0, 0, 0, 9, 0, 3, 0, 0, 0, 0, 0, 0},
    {{{0.0f, 0.0f, 0.0f}, 1000.0f, 10000.0f}},
};
const char l_ev_name[] = "btl_of_swroom";
const char l_ev_name2[] = "btl_of_swroom2";
const char* l_ev_name_table[] = {l_ev_name, l_ev_name2};
#if VERSION > VERSION_DEMO
const int l_enter_angl_band = abs(0xE00);
#endif
}

#if VERSION == VERSION_DEMO
class daObjFirewall_HIO_c : public JORReflexible {
public:
    daObjFirewall_HIO_c();
    virtual ~daObjFirewall_HIO_c() {}

    void genMessage(JORMContext* ctx) { UNUSED(ctx); }

public:
    /* 0x04 */ s8 mNo;
    /* 0x08 */ f32 mEventRange;
    /* 0x0C */ f32 mEventZ;
    /* 0x10 */ f32 mRadius;
    /* 0x14 */ f32 mHeight;
    /* 0x18 */ f32 mRadiusInset;
    /* 0x1C */ f32 mHeightOffset;
    /* 0x20 */ f32 m20;
    /* 0x24 */ f32 mParticleScale;
    /* 0x28 */ u8 m28[0x34 - 0x28];
    /* 0x34 */ u8 mBurning;
    /* 0x35 */ u8 m35;
    /* 0x36 */ u8 mCollision;
    /* 0x37 */ u8 mDebugDraw;
}; // size = 0x38

static daObjFirewall_HIO_c l_HIO;

/* 000000EC-0000015C       .text __ct__19daObjFirewall_HIO_cFv */
daObjFirewall_HIO_c::daObjFirewall_HIO_c() {
    mNo = -1;
    mEventRange = 950.0f;
    mEventZ = -7000.0f;
    mRadius = 1000.0f;
    mHeight = 10000.0f;
    mRadiusInset = 200.0f;
    mHeightOffset = 300.0f;
    m20 = 1.0f;
    mParticleScale = 1.0f;
    mBurning = 0;
    m35 = 0;
    mCollision = 0;
    mDebugDraw = 0;
}
#endif


/* 00000078-000000EC       .text init_mtx__15daObjFirewall_cFv */
void daObjFirewall_c::init_mtx() {
    mpModel->setBaseScale(scale);
    mDoMtx_stack_c::transS(0.0f, 0.0f, 0.0f);
    mpModel->setBaseTRMtx(mDoMtx_stack_c::get());
}

/* 000000EC-00000110       .text solidHeapCB__15daObjFirewall_cFP10fopAc_ac_c */
BOOL daObjFirewall_c::solidHeapCB(fopAc_ac_c* actor) {
    return ((daObjFirewall_c*)actor)->create_heap();
}

/* 00000110-000002DC       .text create_heap__15daObjFirewall_cFv */
bool daObjFirewall_c::create_heap() {
    J3DModelData* modelData;
    bool success = true;
    modelData = static_cast<J3DModelData*>(dComIfG_getObjectRes(l_arcname, dRes_INDEX_YSWDR00_BDL_YSWDR00_e));
    J3DAnmTextureSRTKey* btk = static_cast<J3DAnmTextureSRTKey*>(dComIfG_getObjectRes(l_arcname, dRes_INDEX_YSWDR00_BTK_YSWDR00_e));
    J3DAnmTevRegKey* brk = static_cast<J3DAnmTevRegKey*>(dComIfG_getObjectRes(l_arcname, dRes_INDEX_YSWDR00_BRK_YSWDR00_e));
    if (modelData == NULL || btk == NULL || brk == NULL) {
        JUT_ASSERT(DEMO_SELECT(338, 0x171), 0);
        success = false;
    } else {
        mpModel = mDoExt_J3DModel__create(modelData, 0x80000, 0x11000222);
        mpBgW = dBgW_NewSet((cBgD_t*)dComIfG_getObjectRes(l_arcname, dRes_INDEX_YSWDR00_DZB_FWALL_e), cBgW::MOVE_BG_e, &mpModel->getBaseTRMtx());
        BOOL btkSuccess = mBtk.init(modelData, btk, TRUE, J3DFrameCtrl::EMode_LOOP, 1.0f, 0, -1, false, 0);
        BOOL brkSuccess = mBrk.init(modelData, brk, TRUE, J3DFrameCtrl::EMode_NONE, 1.0f, 0, -1, false, 0);
        if (mpModel == NULL || mpBgW == NULL || !btkSuccess || !brkSuccess) {
            success = false;
        }
    }
    return success;
}

/* 000002DC-00000568       .text registCollisionTable__15daObjFirewall_cFv */
void daObjFirewall_c::registCollisionTable() {
#if VERSION == VERSION_DEMO
    f32 radius, height;
    cXyz pos;
    f32 inset = l_HIO.mRadiusInset;
    f32 ofs = l_HIO.mHeightOffset;
    pos = current.pos;
    pos.y -= ofs;
    radius = 1000.0f * scale.x;
    height = ofs + 10000.0f * scale.y;
    mCyl.SetC(pos);
    mCyl.SetR(radius - inset);
    mCyl.SetH(height);
    cXyz vec = current.pos - dComIfGp_getPlayer(0)->current.pos;
    mCyl.SetAtVec(vec);
    if (l_HIO.mCollision == 1) {
        dComIfG_Ccsp()->Set(&mCyl);
    }
#else
    fopAc_ac_c* player = dComIfGp_getPlayer(0);
    f32 radius, height;
    f32 inset = -1.0f;
    s16 angle = cM_atan2s(player->current.pos.x - current.pos.x, player->current.pos.z - current.pos.z);
    int magnitude = abs(angle);
    if (magnitude < l_enter_angl_band) {
        inset = 100.0f + 30.0f * cM_scos(16384.0f * ((f32)magnitude / l_enter_angl_band));
    } else {
        static s16 zou_chk_angl[5] = {-0x2AAA, 0x2AAA, 0x5555, -0x5555, -0x8000};
        for (int i = 0; i < 5; ++i) {
            int diff = abs((s16)(angle - zou_chk_angl[i]));
            if (diff < 0x1A00) {
                inset = 100.0f + 115.0f * cM_scos(16384.0f * ((f32)diff / 6656.0f));
                break;
            }
        }
        if (inset == -1.0f) {
            inset = 100.0f;
        }
    }
    cXyz pos = current.pos;
    pos.y -= 300.0f;
    radius = 1000.0f * scale.x;
    height = 300.0f + 10000.0f * scale.y;
    mCyl.SetC(pos);
    mCyl.SetR(radius - inset);
    mCyl.SetH(height);
    cXyz vec = current.pos - player->current.pos;
    mCyl.SetAtVec(vec);
    dComIfG_Ccsp()->Set(&mCyl);
#endif
}

/* 000005A4-00000794       .text setPointLight__15daObjFirewall_cFv */
void daObjFirewall_c::setPointLight() {
    if (mAction == &daObjFirewall_c::burn_wait_act_proc || mAction == &daObjFirewall_c::demo_end_wait_act_proc || mAction == &daObjFirewall_c::appear_act_proc) {
        cLib_addCalc2(&mLightStrength, 1.0f + cM_rndF(0.5f), 0.5f, 0.04f);
    } else {
        mLightStrength = 0.0f;
    }
    for (int i = 0; i < 64; ++i) {
        mLights[i].mPos = mLightPos[i];
        mLights[i].mColor.r = 600;
        mLights[i].mColor.g = 400;
        mLights[i].mColor.b = 120;
        mLights[i].mPower = (s16)((800.0f + REG12_F(0)) * mLightStrength);
        mLights[i].mFluctuation = 250.0f;
        if (mLightStrength > 1.0f) {
            cXyz pos = mLightPos[i];
            cXyz scl;
            scl.setall(1.5f * mLightStrength);
            pos.y += 1.1f * ((220.0f + REG12_F(1)) * mLightStrength);
#if VERSION == VERSION_DEMO
            if (mpKageroEmitter[i] == NULL) {
                mpKageroEmitter[i] = dComIfGp_particle_setProjection(0x4004, &pos, NULL, &scl);
            } else {
                mpKageroEmitter[i]->setGlobalParticleScale(JGeometry::TVec3<f32>(scl.x, scl.y, scl.z));
                if (REG12_S(1) == 0) {
                    mpKageroEmitter[i]->setGlobalTranslation(pos.x, pos.y, pos.z);
                }
                mpKageroEmitter[i]->setEmitterCallBackPtr(dPa_control_c::getKageroEcallBack());
            }
#endif
        }
    }
    f32 strength = mLightStrength;
    if (strength > 1.0f) {
        strength = 1.0f;
    }
    if (strength > 0.5f) {
        dKy_custom_colset(0, 3, strength);
    } else {
        strength = 1.0f - strength;
        dKy_custom_colset(3, 0, strength);
    }
}

/* 00000794-00000970       .text particle_set__15daObjFirewall_cFv */
void daObjFirewall_c::particle_set() {
#if VERSION == VERSION_DEMO
    static s16 angles[6] = {0x1555, -0x1555, 0x4000, -0x4000, 0x6AAA, -0x6AAA};
    static s16 angles2[5] = {0, -0x2AAA, 0x2AAA, 0x5555, -0x5555};
#else
    s16 angles[6] = {0x1555, -0x1555, 0x4000, -0x4000, 0x6AAA, -0x6AAA};
    s16 angles2[5] = {0, -0x2AAA, 0x2AAA, 0x5555, -0x5555};
#endif
    csXyz angle(0, 0, 0);
#if VERSION == VERSION_DEMO
    for (int i = 0; i < 6; ++i) {
        angle.y = angles[i];
        mpEmitter[i] = dComIfGp_particle_set(0x82B6, &current.pos, &angle);
    }
    for (int i = 0; i < 5; ++i) {
        angle.y = angles2[i];
        mpEmitter2[i] = dComIfGp_particle_set(0x82B7, &current.pos, &angle);
    }
    mpEmitter3 = dComIfGp_particle_set(0x82B8, &current.pos);
#else
    for (int i = 0; i < 6; ++i) {
        if (mpEmitter[i] == NULL) {
            angle.y = angles[i];
            mpEmitter[i] = dComIfGp_particle_set(0x82B6, &current.pos, &angle);
        }
    }
    for (int i = 0; i < 5; ++i) {
        if (mpEmitter2[i] == NULL) {
            angle.y = angles2[i];
            mpEmitter2[i] = dComIfGp_particle_set(0x82B7, &current.pos, &angle);
        }
    }
    if (mpEmitter3 == NULL) {
        mpEmitter3 = dComIfGp_particle_set(0x82B8, &current.pos);
    }
#endif
}

/* 00000970-00000A1C       .text particle_delete__15daObjFirewall_cFv */
void daObjFirewall_c::particle_delete() {
    int i;
    for (i = 0; i < 6; ++i) {
        if (mpEmitter[i] != NULL) {
            mpEmitter[i]->becomeInvalidEmitter();
            mpEmitter[i] = NULL;
        }
    }
    for (i = 0; i < 5; ++i) {
        if (mpEmitter2[i] != NULL) {
            mpEmitter2[i]->becomeInvalidEmitter();
            mpEmitter2[i] = NULL;
        }
    }
    if (mpEmitter3 != NULL) {
        mpEmitter3->becomeInvalidEmitter();
        mpEmitter3 = NULL;
    }
}

/* 00000A1C-00000AB0       .text seStart__15daObjFirewall_cFUl */
void daObjFirewall_c::seStart(unsigned long sound) {
#if VERSION == VERSION_DEMO
    cXyz pos;
    s16 angle = 0;
    for (int i = 0; i < 8; angle += 0x2000, ++i) {
        pos.set(current.pos.x + scale.x * (1000.0f * cM_ssin(angle)), current.pos.y,
                current.pos.z + scale.x * (1000.0f * cM_scos(angle)));
        mDoAud_seStart(sound, &pos);
    }
#else
    for (int i = 0; i < 8; ++i) {
        mDoAud_seStart(sound, &mSoundPos[i]);
    }
#endif
}

/* 00000AB0-00000B28       .text set_se__15daObjFirewall_cFb */
void daObjFirewall_c::set_se(bool on) {
    if (mSoundOn != on) {
        if (mSoundOn == 1) {
            seStart(JA_SE_OBJ_BAR_FRAME_OFF);
        } else {
            seStart(JA_SE_OBJ_BAR_FRAME_ON);
        }
    } else {
        if (mSoundOn == 1) seStart(JA_SE_OBJ_BAR_FRAME_BURN);
    }
    mSoundOn = on;
}

/* 00000B28-00000B94       .text seDelete__15daObjFirewall_cFv */
void daObjFirewall_c::seDelete() {
#if VERSION > VERSION_DEMO
    if (mSoundInitialized == 1) {
        for (int i = 0; i < 8; ++i) {
            mDoAud_seDeleteObject(&mSoundPos[i]);
        }
    }
#endif
}

/* 00000B94-00000C64       .text set_pl_se__15daObjFirewall_cFv */
void daObjFirewall_c::set_pl_se() {
    static char chk_word0[] = "050smile";
    static char chk_word1[] = "049s_surp";
    static char chk_word2[] = "dummy";
    static char* chk_word_table[] = {chk_word0, chk_word1, chk_word2};
    static u32 voice_table[] = {0x2E, 0x31, 0};
    int staff = dComIfGp_evmng_getMyStaffId("Link");
    if (staff != -1) {
        if (strcmp(dComIfGp_getPEvtManager()->getMyNowCutName(staff), chk_word_table[mVoiceIndex]) == 0) {
            daPy_py_c* player = (daPy_py_c*)dComIfGp_getPlayer(0);
            if (player != NULL) {
                player->voiceStart(voice_table[mVoiceIndex]);
                ++mVoiceIndex;
            }
        }
    }
}

/* 00000C64-00000DDC       .text setup_burn_up__15daObjFirewall_cFv */
void daObjFirewall_c::setup_burn_up() {
    particle_set();
    if (mpBgW != NULL && !mpBgW->ChkUsed()) {
        dComIfG_Bgsp()->Regist(mpBgW, this);
    }
    set_se(true);
    s16 angle;
    for (int i = 0; i < 64; ++i) {
        dKy_plight_set(&mLights[i]);
        f32 radius = 1000.0f * scale.x;
        angle = i * 0x3FF;
        mDoMtx_stack_c::transS(current.pos);
        mDoMtx_stack_c::YrotM(angle);
        mDoMtx_stack_c::transM(radius, 0.0f, 0.0f);
        mDoMtx_stack_c::multVecZero(&mLightPos[i]);
    }
    mAction = &daObjFirewall_c::appear_act_proc;
#if VERSION == VERSION_DEMO
    l_HIO.mBurning = 1;
#endif
    mBurning = 1;
}

/* 00000DDC-00000EAC       .text setup_put_the_fire_out__15daObjFirewall_cFv */
void daObjFirewall_c::setup_put_the_fire_out() {
    if (mBurning == 1) {
        particle_delete();
#if VERSION == VERSION_DEMO
        if (mpBgW != NULL && mpBgW->ChkUsed()) {
            dComIfG_Bgsp()->Release(mpBgW);
        }
#else
        if (heap != NULL && mpBgW != NULL) {
            if (mpBgW->ChkUsed()) {
                dComIfG_Bgsp()->Release(mpBgW);
            }
            mpBgW = NULL;
        }
#endif
        set_se(false);
        for (int i = 0; i < 64; ++i) {
            dKy_plight_cut(&mLights[i]);
#if VERSION == VERSION_DEMO
            if (mpKageroEmitter[i] != NULL) {
                mpKageroEmitter[i]->becomeInvalidEmitter();
                mpKageroEmitter[i]->setEmitterCallBackPtr(NULL);
                mpKageroEmitter[i] = NULL;
            }
#endif
        }
#if VERSION == VERSION_DEMO
        l_HIO.mBurning = 0;
#endif
        mBurning = 0;
    }
}

/* 00000EAC-000011F8       .text _create__15daObjFirewall_cFv */
cPhs_State daObjFirewall_c::_create() {
    fopAcM_SetupActor(this, daObjFirewall_c);
    cPhs_State phase = dComIfG_resLoad(&mPhase, l_arcname);
    if (phase == cPhs_COMPLEATE_e) {
        if (fopAcM_entrySolidHeap(this, solidHeapCB, 0x1420)) {
            fopAcM_SetMtx(this, mpModel->getBaseTRMtx());
            init_mtx();
            mStts.Init(255, 255, this);
            mCyl.Set(l_cyl_src);
            mCyl.SetStts(&mStts);
            mCyl.OnBsRevHit();
#if VERSION > VERSION_DEMO
            s16 angle = 0;
            for (int i = 0; i < 8; angle += 0x2000, ++i) {
                mSoundPos[i].set(current.pos.x + scale.x * (1000.0f * cM_ssin(angle)), current.pos.y,
                                 current.pos.z + scale.x * (1000.0f * cM_scos(angle)));
            }
            mSoundInitialized = 1;
#endif
            mSwitch = param_get_swSave();
            if (dComIfGs_isEventBit(0x3520) == TRUE) {
                mEventType = 1;
                mEvent = dComIfGp_evmng_getEventIdx(l_ev_name_table[1]);
                mAction = &daObjFirewall_c::wait2_act_proc;
            } else {
                mEventType = 0;
                mEvent = -1;
                mAction = &daObjFirewall_c::wait_act_proc;
            }
        } else {
            phase = cPhs_ERROR_e;
        }
    }
#if VERSION == VERSION_DEMO
    if (l_HIO.mNo < 0) {
        l_HIO.mNo = mDoHIO_createChild("剣の間の炎の壁", &l_HIO);
    }
#endif
    return phase;
}

/* 00001550-000015F4       .text _delete__15daObjFirewall_cFv */
bool daObjFirewall_c::_delete() {
    dComIfG_resDelete(&mPhase, l_arcname);
#if VERSION == VERSION_DEMO
    setup_put_the_fire_out();
    l_HIO.mBurning = 0;
    if (l_HIO.mNo >= 0) {
        mDoHIO_deleteChild(l_HIO.mNo);
        l_HIO.mNo = -1;
    }
#else
    if (heap != NULL && mpBgW != NULL) {
        if (mpBgW->ChkUsed()) {
            dComIfG_Bgsp()->Release(mpBgW);
        }
        mpBgW = NULL;
    }
    setup_put_the_fire_out();
    seDelete();
#endif
    return true;
}

/* 000015F4-000016D4       .text wait_act_proc__15daObjFirewall_cFv */
void daObjFirewall_c::wait_act_proc() {
    int staff = -1;
    if (dComIfGp_getPEvtManager()->getEventData(dComIfGp_evmng_getEventIdx(l_ev_name_table[0])) != NULL) {
        staff = dComIfGp_evmng_getMyStaffId("Yswdr00");
    }
    if (staff != -1) {
        if (strcmp(dComIfGp_getPEvtManager()->getMyNowCutName(staff), "BurnUp") == 0) {
            dComIfGs_onEventBit(0x3520);
            setup_burn_up();
        } else {
            set_pl_se();
        }
    }
#if VERSION == VERSION_DEMO
    else if (l_HIO.mBurning == 1) {
        J3DAnmTevRegKey* brk_anm_p = (J3DAnmTevRegKey*)dComIfG_getObjectRes(l_arcname, dRes_INDEX_YSWDR00_BRK_YSWDR00_e);
        JUT_ASSERT(900, brk_anm_p != 0);
        mBrk.init(mpModel->getModelData(), brk_anm_p, TRUE, J3DFrameCtrl::EMode_NONE, 1.0f, 0, -1, true, 0);
        setup_burn_up();
    }
#endif
}

/* 000016D4-00001820       .text wait2_act_proc__15daObjFirewall_cFv */
void daObjFirewall_c::wait2_act_proc() {
    fopAc_ac_c* player = dComIfGp_getPlayer(0);
    if (player != NULL) {
        f32 dist = (player->current.pos - current.pos).absXZ();
        if (dist < DEMO_SELECT(l_HIO.mEventRange, 950.0f) && player->current.pos.z < DEMO_SELECT(l_HIO.mEventZ, -7000.0f)) {
            if (eventInfo.checkCommandDemoAccrpt()) {
                mAction = &daObjFirewall_c::wait3_act_proc;
            } else {
                fopAcM_orderOtherEventId(this, mEvent);
            }
        }
    }
}

/* 00001820-000018E0       .text wait3_act_proc__15daObjFirewall_cFv */
void daObjFirewall_c::wait3_act_proc() {
    int staff = -1;
    if (dComIfGp_getPEvtManager()->getEventData(dComIfGp_evmng_getEventIdx(l_ev_name_table[1])) != NULL) {
        staff = dComIfGp_evmng_getMyStaffId("Yswdr00");
    }
    if (staff != -1 && strcmp(dComIfGp_getPEvtManager()->getMyNowCutName(staff), "BurnUp") == 0) {
        setup_burn_up();
    }
}

/* 000018E0-000019B0       .text appear_act_proc__15daObjFirewall_cFv */
void daObjFirewall_c::appear_act_proc() {
    mBrk.play();
    if (mBrk.isStop() == TRUE) {
        mLightStrength = 1.0f;
        if (mEvent != -1) {
            mAction = &daObjFirewall_c::demo_end_wait_act_proc;
        } else {
            mAction = &daObjFirewall_c::burn_wait_act_proc;
        }
    }
    set_se(true);
}

/* 000019B0-00001A34       .text demo_end_wait_act_proc__15daObjFirewall_cFv */
void daObjFirewall_c::demo_end_wait_act_proc() {
    if (dComIfGp_evmng_endCheck(mEvent)) {
        dComIfGp_event_reset();
        mAction = &daObjFirewall_c::burn_wait_act_proc;
    }
    set_se(true);
}

/* 00001A34-00001B68       .text burn_wait_act_proc__15daObjFirewall_cFv */
void daObjFirewall_c::burn_wait_act_proc() {
    mStts.Move();
    registCollisionTable();
    if (mSwitch != 0xFF && fopAcM_isSwitch(this, mSwitch) == TRUE) {
        J3DAnmTevRegKey* brk_anm_p = (J3DAnmTevRegKey*)dComIfG_getObjectRes(l_arcname, dRes_INDEX_YSWDR00_BRK_YSWDR00_e);
        JUT_ASSERT(DEMO_SELECT(1041, 0x4e4), brk_anm_p != 0);
        mBrk.init(mpModel->getModelData(), brk_anm_p, TRUE, J3DFrameCtrl::EMode_NONE, -1.0f, 0, -1, true, 0);
        setup_put_the_fire_out();
        mAction = &daObjFirewall_c::retire_act_proc;
#if VERSION == VERSION_DEMO
        l_HIO.mBurning = 0;
    } else if (l_HIO.mBurning == 0) {
        J3DAnmTevRegKey* brk_anm_p = (J3DAnmTevRegKey*)dComIfG_getObjectRes(l_arcname, dRes_INDEX_YSWDR00_BRK_YSWDR00_e);
        JUT_ASSERT(1066, brk_anm_p != 0);
        mBrk.init(mpModel->getModelData(), brk_anm_p, TRUE, J3DFrameCtrl::EMode_NONE, -1.0f, 0, -1, true, 0);
        setup_put_the_fire_out();
        mAction = &daObjFirewall_c::retire_act_proc;
#endif
    } else {
        set_se(true);
    }
}

/* 00001B68-00001BEC       .text retire_act_proc__15daObjFirewall_cFv */
void daObjFirewall_c::retire_act_proc() {
    mBrk.play();
    if (mBrk.isStop() == TRUE) {
        dComIfGs_onEventBit(0x2C01);
        fopAcM_delete(this);
    }
}

/* 00001BEC-00001C70       .text _execute__15daObjFirewall_cFv */
bool daObjFirewall_c::_execute() {
    if (mpBgW != NULL && mpBgW->ChkUsed()) {
        mpBgW->Move();
    }
    mBtk.play();
    setPointLight();
#if VERSION == VERSION_DEMO
    cXyz scl(l_HIO.mParticleScale, l_HIO.mParticleScale, l_HIO.mParticleScale);
    for (int i = 0; i < 6; ++i) {
        if (mpEmitter[i] != NULL) {
            mpEmitter[i]->setGlobalScale(scl);
        }
    }
    for (int i = 0; i < 5; ++i) {
        if (mpEmitter2[i] != NULL) {
            mpEmitter2[i]->setGlobalScale(scl);
        }
    }
    if (mpEmitter3 != NULL) {
        mpEmitter3->setGlobalScale(scl);
    }
#endif
    (this->*mAction)();
    return true;
}

/* 00001C70-00001CD4       .text _draw__15daObjFirewall_cFv */
bool daObjFirewall_c::_draw() {
#if VERSION == VERSION_DEMO
    if (l_HIO.mDebugDraw == 1) {
        for (int i = 0; i < 64; i++) {
            GXColor color = {0xFF, 0x00, 0x00, 0x80};
        }
    }
#endif
    mBtk.entry(mpModel->getModelData());
    mBrk.entry(mpModel->getModelData());
    mDoExt_modelUpdateDL(mpModel);
    return true;
}

/* 00001CD4-00001CF4       .text daObjFirewall_Create__FP10fopAc_ac_c */
static cPhs_State daObjFirewall_Create(fopAc_ac_c* i_this) {
    return ((daObjFirewall_c*)i_this)->_create();
}

/* 00001CF4-00001D18       .text daObjFirewall_Delete__FP15daObjFirewall_c */
static BOOL daObjFirewall_Delete(daObjFirewall_c* i_this) {
    return ((daObjFirewall_c*)i_this)->_delete();
}

/* 00001D18-00001D3C       .text daObjFirewall_Execute__FP15daObjFirewall_c */
static BOOL daObjFirewall_Execute(daObjFirewall_c* i_this) {
    return ((daObjFirewall_c*)i_this)->_execute();
}

/* 00001D3C-00001D60       .text daObjFirewall_Draw__FP15daObjFirewall_c */
static BOOL daObjFirewall_Draw(daObjFirewall_c* i_this) {
    return ((daObjFirewall_c*)i_this)->_draw();
}

/* 00001D60-00001D68       .text daObjFirewall_IsDelete__FP15daObjFirewall_c */
static BOOL daObjFirewall_IsDelete(daObjFirewall_c*) {
    return TRUE;
}

static actor_method_class l_daObjFirewall_Method = {
    (process_method_func)daObjFirewall_Create,
    (process_method_func)daObjFirewall_Delete,
    (process_method_func)daObjFirewall_Execute,
    (process_method_func)daObjFirewall_IsDelete,
    (process_method_func)daObjFirewall_Draw,
};

actor_process_profile_definition g_profile_Obj_Firewall = {
    /* Layer ID     */ fpcLy_CURRENT_e,
    /* List ID      */ 0x0007,
    /* List Prio    */ fpcPi_CURRENT_e,
    /* Proc Name    */ fpcNm_Obj_Firewall_e,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(daObjFirewall_c),
    /* Size Other   */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Draw Prio    */ fpcDwPi_Obj_Firewall_e,
    /* Actor SubMtd */ &l_daObjFirewall_Method,
    /* Status       */ fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ACTOR_e,
    /* Cull Type    */ fopAc_CULLBOX_CUSTOM_e,
};
